// THE FIRST SCREEN THIS APP EVER SHOWS, AND THE SENTENCE IT PUTS IN FRONT OF
// A CHILD WHEN THE CODE DOES NOT WORK.
//
// It used to render `e.message` — the transport's own English, HTTP status
// code and all — in a coral box next to Sparky. These pin the replacement,
// and specifically pin the one thing a first-run error must never do: make a
// seven-year-old think they broke something.
//
// TONE NOTE (CONTEXT §3 principle 7, NO PUNITIVE UX): the copy asserted here
// is Egyptian-colloquial and warm on purpose. A test that asserted a
// Modern-Standard-Arabic rewrite would be asserting the wrong product.
//
// EXECUTION STATUS: NEVER RUN. No Flutter or Dart SDK is reachable from the
// environment this was authored in (pub.dev, dl.google.com and
// storage.googleapis.com all answer 403 to CONNECT), so `flutter test` was
// never invoked. STATIC VERIFIED ONLY by `scripts/dart_preflight.py`, which
// executes nothing. First execution is on a GitHub runner.

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:child_app/core/di/providers.dart';
import 'package:child_app/core/errors/api_failure.dart';
import 'package:child_app/core/localization/locale_controller.dart';
import 'package:child_app/core/localization/localization_engine.dart';
import 'package:child_app/core/network/api_exception.dart';
import 'package:child_app/core/theme/kid_theme.dart';
import 'package:child_app/features/pairing/data/pairing_repository.dart';
import 'package:child_app/features/pairing/presentation/pairing_screen.dart';

/// See the parent app's harness for why this is hand-written rather than
/// generated by `mockito`: codegen needs `pub get`, and pub.dev is not
/// reachable from where this was written.
class _FakePairingRepository implements ChildPairingRepository {
  _FakePairingRepository({this.onRegister});

  final Future<void> Function()? onRegister;

  int calls = 0;
  String? lastCode;

  @override
  Future<void> registerWithCode(String code) {
    calls++;
    lastCode = code;
    final slot = onRegister;
    if (slot == null) {
      throw StateError('_FakePairingRepository.registerWithCode not stubbed.');
    }
    return slot();
  }

  @override
  dynamic noSuchMethod(Invocation invocation) => throw StateError(
        '_FakePairingRepository has no stub for ${invocation.memberName}.',
      );
}

/// The 401 `/pairing/accept` really answers a wrong or expired code with —
/// built by running the REAL conversion over the REAL shape, so this tests
/// the code and not the test. Its `messageAr` is B3's per-status fallback
/// «انتهت جلستك…», which is exactly the sentence that must NOT reach a child.
ApiFailure _wrongCodeFailure() => ApiFailure.from(ApiException(
      'Invitation code is invalid or has expired.',
      401,
      code: 'UNAUTHENTICATED',
      messageAr: 'انتهت جلستك. سجّل الدخول مرة أخرى للمتابعة.',
      requestId: 'req_pair_1',
    ));

ApiFailure _proxyFailure() => ApiFailure.from(ApiException(
      'The request returned an invalid status code of 502.',
      502,
    ));

ApiFailure _offlineFailure() => ApiFailure.from(ApiException(
      'No internet connection.',
      0,
      code: 'CLIENT_OFFLINE',
      messageAr: 'مفيش نت دلوقتي.',
    ));

ApiFailure _throttledFailure() => ApiFailure.from(ApiException(
      'Too many requests.',
      429,
      code: 'RATE_LIMITED',
      messageAr: 'استنى شوية وجرّب تاني.',
    ));

Future<T> _failing<T>(ApiFailure failure) => Future<T>.error(failure);

Future<T> _pending<T>() => Completer<T>().future;

String _ar(String key) => translate(AppLocale.ar, key);

Future<void> _pump(
  WidgetTester tester,
  _FakePairingRepository repository, {
  VoidCallback? onPaired,
}) async {
  GoogleFonts.config.allowRuntimeFetching = false;
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        childPairingRepositoryProvider.overrideWithValue(repository),
        localeControllerProvider.overrideWith(
          (ref) => LocaleController(storage: InMemoryLocaleStorage(AppLocale.ar)),
        ),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: KidTheme.theme,
        locale: const Locale('ar'),
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [Locale('ar'), Locale('en')],
        home: PairingScreen(onPaired: onPaired ?? () {}),
      ),
    ),
  );
  // Not pumpAndSettle: the submitting state holds an indeterminate
  // CircularProgressIndicator whose animation never settles.
  await tester.pump();
}

Future<void> _enterCode(WidgetTester tester, String code) async {
  await tester.enterText(find.byType(TextField), code);
  await tester.pump();
  await tester.tap(find.byType(FilledButton));
  await tester.pump();
  await tester.pump();
}

void main() {
  group('PairingScreen — the code itself was refused', () {
    testWidgets('says the code is not working, and NEVER shows B3\'s '
        '«انتهت جلستك» — a child on this screen has no session and has never '
        'logged in', (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(
          onRegister: () => _failing<void>(_wrongCodeFailure()),
        ),
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(find.text(_ar('pairing.codeNotAccepted')), findsOneWidget);
      expect(find.text(_ar('pairing.cannotReach')), findsNothing);
      expect(find.textContaining('سجّل الدخول'), findsNothing);
      expect(find.textContaining('انتهت جلستك'), findsNothing);
    });

    testWidgets('the copy points at a grown-up, not at the child', (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(
          onRegister: () => _failing<void>(_wrongCodeFailure()),
        ),
      );

      await _enterCode(tester, 'ABCD-1234');

      // Nothing in either line accuses. This is the guard against a future
      // copy edit quietly turning «الكود ده مش شغّال» into «إنت غلطان».
      expect(find.textContaining('غلط'), findsNothing);
      expect(find.textContaining('خطأ'), findsNothing);
      expect(find.textContaining('ممنوع'), findsNothing);
    });
  });

  group('PairingScreen — nothing the child did', () {
    testWidgets('A 502 IS NOT THE CHILD\'S FAULT AND IS NOT WORDED AS IF IT '
        'WERE, and the transport sentence never reaches the screen',
        (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(onRegister: () => _failing<void>(_proxyFailure())),
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(find.text(_ar('pairing.cannotReach')), findsOneWidget);
      // Not the "your code is wrong" branch — the server never judged it.
      expect(find.text(_ar('pairing.codeNotAccepted')), findsNothing);
      // And the bug this whole pass exists to close.
      expect(find.textContaining('502'), findsNothing);
      expect(find.textContaining('invalid status code'), findsNothing);
    });

    testWidgets('no connection reads the same way — the grown-ups\' problem, '
        'not the child\'s', (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(onRegister: () => _failing<void>(_offlineFailure())),
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(find.text(_ar('pairing.cannotReach')), findsOneWidget);
      expect(find.text(_ar('pairing.codeNotAccepted')), findsNothing);
    });

    testWidgets('THE THROTTLE IS NOT A VERDICT ON THE CODE. A child carefully '
        'retyping a code read out to them is exactly who trips 429',
        (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(onRegister: () => _failing<void>(_throttledFailure())),
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(find.text(_ar('pairing.cannotReach')), findsOneWidget);
      expect(find.text(_ar('pairing.codeNotAccepted')), findsNothing);
    });
  });

  group('PairingScreen — the paths that must keep working', () {
    testWidgets('a code that pairs calls onPaired and shows no error',
        (tester) async {
      var paired = 0;
      await _pump(
        tester,
        _FakePairingRepository(onRegister: () async {}),
        onPaired: () => paired++,
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(paired, 1);
      expect(find.text(_ar('pairing.codeNotAccepted')), findsNothing);
      expect(find.text(_ar('pairing.cannotReach')), findsNothing);
    });

    testWidgets('the typed code reaches the repository trimmed', (tester) async {
      final repository = _FakePairingRepository(onRegister: () async {});
      await _pump(tester, repository);

      await _enterCode(tester, '  ABCD-1234  ');

      expect(repository.lastCode, 'ABCD-1234');
    });

    testWidgets('THE ERROR CARD DOES NOT REPLACE THE SCREEN. The code field '
        'and the «يلا بينا!» button are still there, so pressing it again is '
        'still the way forward', (tester) async {
      final repository = _FakePairingRepository(
        onRegister: () => _failing<void>(_proxyFailure()),
      );
      await _pump(tester, repository);

      await _enterCode(tester, 'ABCD-1234');
      expect(repository.calls, 1);
      expect(find.text(_ar('pairing.cannotReach')), findsOneWidget);
      expect(find.byType(TextField), findsOneWidget);

      await tester.tap(find.byType(FilledButton));
      await tester.pump();
      await tester.pump();

      expect(repository.calls, 2);
      expect(repository.lastCode, 'ABCD-1234');
    });

    testWidgets('a send in flight shows the spinner and no error card',
        (tester) async {
      await _pump(
        tester,
        _FakePairingRepository(onRegister: () => _pending<void>()),
      );

      await _enterCode(tester, 'ABCD-1234');

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
      expect(find.text(_ar('pairing.cannotReach')), findsNothing);
      expect(find.text(_ar('pairing.codeNotAccepted')), findsNothing);
    });
  });
}
