// SMOKE LAYER FOR THE F4 REWARD JOURNEY — child app.
//
// The child app already had 11 test files, but every one of them tests a
// SERVICE (pairing, heartbeat, offline queue, policy cache, telemetry). Not
// one widget test existed, so none of the F4 goal screens — the screens the
// child actually opens — had ever been constructed by anything.
//
// Same shape and same claims as the parent app's
// `test/features/rewards/reward_screens_smoke_test.dart`: for each screen,
// does it BUILD, does it show LOADING, does it show EMPTY in Arabic, does it
// show ERROR with the server's own Arabic sentence. Nothing about behaviour.
//
// TONE NOTE (CONTEXT §3 principle 7, NO PUNITIVE UX): the copy asserted here
// is Egyptian-colloquial and warm on purpose — «مفيش أهداف النهاردة»,
// «حاول تاني». A test that asserted a Modern-Standard-Arabic rewrite would be
// asserting the wrong product.
//
// EXECUTION STATUS: NEVER RUN. No Flutter SDK is reachable from the authoring
// environment. STATIC VERIFIED by `scripts/dart_preflight.py` only.

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:child_app/core/design_system/design_system.dart';
import 'package:child_app/core/di/providers.dart';
import 'package:child_app/core/errors/api_failure.dart';
import 'package:child_app/core/localization/locale_controller.dart';
import 'package:child_app/core/localization/localization_engine.dart';
import 'package:child_app/core/theme/kid_theme.dart';
import 'package:child_app/features/goals/data/achievements_repository.dart';
import 'package:child_app/features/goals/domain/catalogue_domain.dart';
import 'package:child_app/features/goals/domain/child_achievement.dart';
import 'package:child_app/features/goals/domain/child_goal.dart';
import 'package:child_app/features/goals/domain/child_rewards.dart';
import 'package:child_app/features/goals/presentation/my_attempts_screen.dart';
import 'package:child_app/features/goals/presentation/my_rewards_screen.dart';
import 'package:child_app/features/goals/presentation/today_goals_screen.dart';

/// See the parent app's harness for why this is hand-written rather than
/// generated by `mockito`: codegen needs `pub get`, and pub.dev is not
/// reachable from where these were written.
class _FakeAchievementsRepository implements ChildAchievementsRepository {
  _FakeAchievementsRepository({this.onToday, this.onMine, this.onRewards});

  final Future<List<TodayGoal>> Function()? onToday;
  final Future<List<MyAttempt>> Function()? onMine;
  final Future<ChildRewardsSnapshot> Function()? onRewards;

  @override
  Future<List<TodayGoal>> today() => _need(onToday, 'today');

  @override
  Future<List<MyAttempt>> mine() => _need(onMine, 'mine');

  @override
  Future<ChildRewardsSnapshot> rewards() => _need(onRewards, 'rewards');

  Future<T> _need<T>(Future<T> Function()? slot, String name) {
    if (slot == null) {
      throw StateError(
        '_FakeAchievementsRepository.$name was called but this test did not '
        'stub it.',
      );
    }
    return slot();
  }

  @override
  dynamic noSuchMethod(Invocation invocation) => throw StateError(
        '_FakeAchievementsRepository has no stub for ${invocation.memberName}.',
      );
}

const ApiFailure _failure = ApiFailure(
  message: 'Upstream refused',
  messageAr: 'حصلت مشكلة، جرّب تاني',
  code: 'INTERNAL_ERROR',
  statusCode: 500,
  requestId: 'req_test_0001',
);

Future<T> _pending<T>() => Completer<T>().future;

Future<T> _failing<T>() => Future<T>.error(_failure);

String _ar(String key) => translate(AppLocale.ar, key);

String _arWith(String key, Map<String, Object> options) =>
    translate(AppLocale.ar, key, options: options);

/// A grant whose `expiresAt` is already in the past on WHATEVER device runs
/// this test. Anything that draws its standing from the local clock will call
/// it finished; the server, in the tests below, still counts it.
ChildScreenTimeGrant _grant({required String id, int minutes = 15}) =>
    ChildScreenTimeGrant(
      id: id,
      minutes: minutes,
      expiresAt: DateTime.utc(2020),
    );

Future<void> _pump(
  WidgetTester tester,
  Widget screen,
  _FakeAchievementsRepository repo, {
  List<CatalogueDomainRow> catalogue = const <CatalogueDomainRow>[],
}) async {
  GoogleFonts.config.allowRuntimeFetching = false;
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        childAchievementsRepositoryProvider.overrideWithValue(repo),
        // The chooser's catalogue, stubbed so nothing in this file reaches for
        // a real `ApiClient`. The default — an empty list — is also exactly
        // what the screen sees when the catalogue call FAILS, so every test
        // that does not pass one is asserting the fallback path.
        catalogueDomainsProvider.overrideWith((ref) async => catalogue),
        localeControllerProvider.overrideWith(
          (ref) => LocaleController(storage: InMemoryLocaleStorage(AppLocale.ar)),
        ),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: KidTheme.theme,
        locale: const Locale('ar'),
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [Locale('ar'), Locale('en')],
        home: screen,
      ),
    ),
  );
  // Not pumpAndSettle: the loading state animates forever — it was an
  // indeterminate progress indicator and is now a pulsing skeleton, and
  // neither ever settles.
  await tester.pump();
}

TodayGoal _goal() => const TodayGoal(
      programId: 'prog_1',
      category: 'FAITH',
      activity: 'QURAN_MEMORIZE_SURAH',
      targetSummaryAr: 'احفظ سورة الفاتحة',
      durationMinutes: 10,
      reward: GoalReward(type: 'POINTS', amount: 50),
      verificationLevel: 'PARENT',
      available: true,
    );

void main() {
  group('TodayGoalsScreen — the child\'s first screen', () {
    testWidgets('loading while the repository is silent', (tester) async {
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () => _pending<List<TodayGoal>>()),
      );
      expect(find.byType(KidLoadingState), findsOneWidget);
    });

    testWidgets('empty renders the warm Arabic copy, not an error',
        (tester) async {
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () async => const <TodayGoal>[]),
      );
      await tester.pump();

      expect(find.text(_ar('today.emptyTitle')), findsOneWidget);
      expect(find.byType(KidErrorState), findsNothing);
    });

    testWidgets("error renders the server's own Arabic sentence",
        (tester) async {
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () => _failing<List<TodayGoal>>()),
      );
      await tester.pump();

      expect(find.text(_ar('today.errorTitle')), findsOneWidget);
      expect(find.text(_failure.messageAr!), findsOneWidget);
      expect(find.text(_ar('common.retry')), findsOneWidget);
    });

    testWidgets('a goal renders its Arabic target summary', (tester) async {
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () async => [_goal()]),
      );
      await tester.pump();

      expect(find.text('احفظ سورة الفاتحة'), findsOneWidget);
      expect(find.byType(KidEmptyState), findsNothing);
    });

    testWidgets('the chooser shows the server’s domains, including ones with no goal today',
        (tester) async {
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () async => [_goal()]),
        catalogue: const [
          CatalogueDomainRow(code: 'FAITH', labelAr: 'إيمان', suggestedAtThisAge: true),
          CatalogueDomainRow(
              code: 'PROGRAMMING', labelAr: 'برمجة', suggestedAtThisAge: true),
        ],
      );
      // One pump for the goals future, one for the catalogue's.
      await tester.pump();
      await tester.pump();

      // The server's own Arabic, verbatim — not `t('category.PROGRAMMING')`.
      expect(find.text('إيمان'), findsOneWidget);
      // DIMMED, NEVER HIDDEN: nothing is programmed in PROGRAMMING today and
      // the child still learns that it exists.
      expect(find.text('برمجة'), findsOneWidget);
    });

    testWidgets('an unreadable catalogue still leaves a usable screen', (tester) async {
      // The empty catalogue is what a failed `GET /self/catalogue/domains`
      // produces. The day's goal must render exactly as before.
      await _pump(
        tester,
        const TodayGoalsScreen(),
        _FakeAchievementsRepository(onToday: () async => [_goal()]),
      );
      await tester.pump();
      await tester.pump();

      expect(find.text('احفظ سورة الفاتحة'), findsOneWidget);
      expect(find.byType(KidErrorState), findsNothing);
    });
  });

  group('MyAttemptsScreen', () {
    testWidgets('loading', (tester) async {
      await _pump(
        tester,
        const MyAttemptsScreen(),
        _FakeAchievementsRepository(onMine: () => _pending<List<MyAttempt>>()),
      );
      expect(find.byType(KidLoadingState), findsOneWidget);
    });

    testWidgets('empty, in Arabic', (tester) async {
      await _pump(
        tester,
        const MyAttemptsScreen(),
        _FakeAchievementsRepository(onMine: () async => const <MyAttempt>[]),
      );
      await tester.pump();
      expect(find.text(_ar('attempts.emptyTitle')), findsOneWidget);
    });

    testWidgets('error, in Arabic', (tester) async {
      await _pump(
        tester,
        const MyAttemptsScreen(),
        _FakeAchievementsRepository(onMine: () => _failing<List<MyAttempt>>()),
      );
      await tester.pump();
      expect(find.text(_ar('attempts.errorTitle')), findsOneWidget);
      expect(find.text(_failure.messageAr!), findsOneWidget);
    });
  });

  group('MyRewardsScreen', () {
    testWidgets('loading', (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          onRewards: () => _pending<ChildRewardsSnapshot>(),
        ),
      );
      expect(find.byType(KidLoadingState), findsOneWidget);
    });

    testWidgets('error, in Arabic', (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          onRewards: () => _failing<ChildRewardsSnapshot>(),
        ),
      );
      await tester.pump();
      expect(find.text(_ar('myRewards.errorTitle')), findsOneWidget);
      expect(find.text(_failure.messageAr!), findsOneWidget);
    });

    testWidgets('a snapshot with nothing in it is EMPTY, not an error',
        (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          onRewards: () async => const ChildRewardsSnapshot(
            activeBonusMinutes: 0,
            grants: <ChildScreenTimeGrant>[],
            fulfilments: <ChildFulfilment>[],
          ),
        ),
      );
      await tester.pump();
      expect(find.byType(KidErrorState), findsNothing);
    });

    // -----------------------------------------------------------------------
    // THE REGRESSION GUARD FOR THE DEVICE CLOCK.
    //
    // This screen rendered the server's `activeBonusMinutes` and, in the rows
    // immediately under it, dimmed and badged each grant with
    // `grant.isActiveAt(DateTime.now())` — the handset's own clock re-deciding
    // something the server had already decided. A phone running fast, or an
    // expiry crossing while the screen sat open, and the total and the rows
    // disagreed in front of the child about minutes the child earned.
    //
    // Every grant below expires in 2020, so it is ALREADY PAST on any device
    // that runs these tests. That is the point: a local re-derivation gives a
    // different answer from the server's, which is the only way a test can
    // tell the two apart. These fail if anything ever puts the device clock
    // back in charge of a grant's standing.
    // -----------------------------------------------------------------------
    testWidgets(
        'shows the SERVER total even when every row looks expired to this '
        'device', (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          onRewards: () async => ChildRewardsSnapshot(
            // The server still counts both. The device clock says otherwise.
            activeBonusMinutes: 30,
            grants: [_grant(id: 'g_1'), _grant(id: 'g_2')],
            fulfilments: const <ChildFulfilment>[],
          ),
        ),
      );
      await tester.pump();

      expect(find.text('30'), findsOneWidget);
      // What a local sum over `expiresAt < now` would have produced.
      expect(find.text('0'), findsNothing);
      expect(
        find.text(_arWith('myRewards.grantMinutes', {'count': 15})),
        findsNWidgets(2),
      );
    });

    testWidgets('never draws a row as live or finished on its own authority',
        (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          onRewards: () async => ChildRewardsSnapshot(
            activeBonusMinutes: 30,
            grants: [_grant(id: 'g_1'), _grant(id: 'g_2')],
            fulfilments: const <ChildFulfilment>[],
          ),
        ),
      );
      await tester.pump();

      // `GET /self/achievements/rewards` returns the unrevoked HISTORY with no
      // per-grant live flag, and the route that has one
      // (`…/screen-time-policy/effective`) is `@ParentSurface()` — unreachable
      // with a device token. So no row carries a standing badge at all, and
      // nothing here is greyed out for having "finished".
      expect(find.byType(KidBadge), findsNothing);
      expect(
        tester.widgetList<KidCard>(find.byType(KidCard)).every((c) => !c.dimmed),
        isTrue,
      );
      expect(find.text(_ar('myRewards.grantsHistoryHint')), findsOneWidget);
    });

    testWidgets(
        'a total the server did not send reads as unknown, in Arabic, not as '
        'zero', (tester) async {
      await _pump(
        tester,
        const MyRewardsScreen(),
        _FakeAchievementsRepository(
          // Straight through the parser, because the fabricated zero lived
          // there: `activeBonusMinutes` used to default to 0 when the field
          // was absent, which tells a child their earned minutes are gone.
          onRewards: () async => ChildRewardsSnapshot.fromJson(
            const <String, dynamic>{
              'screenTimeGrants': <Map<String, dynamic>>[
                <String, dynamic>{
                  'id': 'g_1',
                  'minutes': 15,
                  'expiresAt': '2020-01-01T00:00:00.000Z',
                },
              ],
              'fulfilments': <Map<String, dynamic>>[],
            },
          ),
        ),
      );
      await tester.pump();

      expect(find.text(_ar('myRewards.bonusUnknown')), findsOneWidget);
      expect(find.byType(KidStatTile), findsNothing);
      expect(find.text('0'), findsNothing);
      // An unread total is not an empty screen and not an error screen.
      expect(find.byType(KidErrorState), findsNothing);
      expect(find.text(_ar('myRewards.emptyTitle')), findsNothing);
    });
  });
}
