// A TAP ON A MESSAGE CARD NOW LANDS SOMEWHERE — the in-app half of `abny://`.
//
// `test/core/routing/deep_link_test.dart` proves the parser and the map. This
// file proves the WIRING: that the card a child actually touches reaches
// `ChildDeepLinkRouter`, that the tab underneath changes, that a card with no
// link offers no tap at all, and that the entry point a future push handler
// will call goes through the same resolver rather than a second one.
//
// THE HARNESS MIRRORS PRODUCTION, and that is load-bearing here.
// `MyGrowthScreen` is PUSHED, under the same route name `ChildHomeShell` uses
// for its app-bar icon, because half of what this file asserts is about which
// route the child is standing on when they tap.
//
// THE FIXTURE IS THE SERVER'S OWN ROW. `/life-intelligence/self/messages` now
// serves `data` on every message — `{"deepLink": "abny://<surface>"}` for a
// message that names a screen, and `null` for one that does not (a
// parent-authored note, or any row written before that field existed). Both
// shapes are exercised below, and `the server's own inbox row` group asserts
// the WHOLE row rather than the two fields this widget happens to read, so a
// field the server adds tomorrow cannot quietly change what a tap does.
//
// WHAT IS DELIBERATELY NOT ASSERTED: which surface a given notification type
// leads to. That map is the SERVER'S — `notification-destination.ts` — and this
// app parses a resolved link instead of re-deriving one. A client that decided
// would be a second opinion nobody can audit.
//
// EXECUTION STATUS: NEVER RUN. There is no Flutter SDK and no Dart SDK in the
// authoring environment, and pub.dev is unreachable, so these tests have never
// been executed. They are STATIC VERIFIED by `scripts/dart_preflight.py`,
// `scripts/verify_dart_imports.py` and `scripts/verify_l10n_parity.py` only.

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:child_app/core/di/providers.dart';
import 'package:child_app/core/localization/locale_controller.dart';
import 'package:child_app/core/localization/localization_engine.dart';
import 'package:child_app/core/routing/child_deep_link_router.dart';
import 'package:child_app/core/routing/child_home_tab.dart';
import 'package:child_app/features/family_growth/api/family_growth_api.dart';
import 'package:child_app/features/family_growth/presentation/my_growth_screen.dart';

/// Hand-written rather than generated by `mockito`: codegen needs `pub get`,
/// and pub.dev is not reachable from where these were written. `implements` +
/// `noSuchMethod` is the convention this app's other tests already use.
///
/// Only the calls `MyGrowthScreen` blocks its first render on are answered.
/// The five supplementary ones (health, learning, rewards, coaching, smart
/// tasks) fall through to [noSuchMethod] and throw, which is a REAL case and
/// not a shortcut: that screen wraps each of them in `_softly` precisely so
/// one section's failure cannot blank the others.
class _FakeGrowthApi implements FamilyGrowthApi {
  _FakeGrowthApi({required this.messages});

  final List<dynamic> messages;
  final List<String> acknowledged = [];

  @override
  Future<Map<String, dynamic>> getProfile() async =>
      <String, dynamic>{'firstName': 'سلمى'};

  @override
  Future<List<dynamic>> getHabits() async => const <dynamic>[];

  @override
  Future<List<dynamic>> getFaithPractices() async => const <dynamic>[];

  @override
  Future<List<dynamic>> getMessages() async => messages;

  @override
  Future<void> acknowledgeMessage(String messageId) async {
    acknowledged.add(messageId);
  }

  @override
  dynamic noSuchMethod(Invocation invocation) => throw StateError(
        '_FakeGrowthApi has no stub for ${invocation.memberName} — if this is '
        'a section MyGrowthScreen now blocks on, stub it here.',
      );
}

const String _title = 'بابا بعتلك رسالة';

/// «this key was not present at all», which is a THIRD state next to «present
/// and null» and «present with a payload» — and the one an older server, or a
/// response trimmed by a proxy, produces. A sentinel rather than `null` because
/// `null` is itself one of the states under test.
const Object _absent = Object();

/// One server-authored message. `body` is Arabic and is rendered verbatim —
/// it passed the safety engine at this child's own age band, and no `t()` key
/// stands in for it.
Map<String, dynamic> _message({String? link}) => <String, dynamic>{
      'id': 'msg_1',
      'title': _title,
      'body': 'شطورة يا سلمى! كمّلي كده.',
      'acknowledgedAt': '2026-01-01T00:00:00.000Z',
      if (link != null) 'data': <String, dynamic>{'deepLink': link},
    };

/// Pumps an app whose first route stands in for `ChildHomeShell` and then
/// pushes `MyGrowthScreen` exactly as the shell's app-bar icon does — same
/// route name, same push. Returns the root container so a test can read the
/// selected tab.
Future<ProviderContainer> _pumpGrowth(
  WidgetTester tester,
  _FakeGrowthApi api,
) async {
  GoogleFonts.config.allowRuntimeFetching = false;
  final navigator = GlobalKey<NavigatorState>();

  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        familyGrowthApiProvider.overrideWithValue(api),
        localeControllerProvider.overrideWith(
          (ref) => LocaleController(storage: InMemoryLocaleStorage(AppLocale.ar)),
        ),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        navigatorKey: navigator,
        locale: const Locale('ar'),
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [Locale('ar'), Locale('en')],
        // Stands in for the tabbed shell, which is not what this file is
        // about — the tab it shows is read from the provider instead.
        home: const Scaffold(body: SizedBox.shrink()),
      ),
    ),
  );

  navigator.currentState!.push(
    MaterialPageRoute<void>(
      builder: (_) => const MyGrowthScreen(),
      settings: const RouteSettings(
        name: ChildDeepLinkRouter.myGrowthRouteName,
      ),
    ),
  );

  // Not pumpAndSettle: the mascot and the progress ring animate, and a screen
  // that never settles would hang the test rather than fail it. One frame to
  // start the transition, one long one to finish it and to let the four
  // awaited fetches complete.
  await tester.pump();
  await tester.pump(const Duration(seconds: 1));

  return ProviderScope.containerOf(
    tester.element(find.byType(MaterialApp)),
    listen: false,
  );
}

void main() {
  group('a message card with a link', () {
    testWidgets('tapping it selects the tab the server named', (tester) async {
      final api = _FakeGrowthApi(messages: [_message(link: 'abny://rewards')]);
      final container = await _pumpGrowth(tester, api);

      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(find.text(_title), findsOneWidget);

      await tester.tap(find.text(_title));
      await tester.pump();

      // THE TAB, not a pushed screen: the child's rewards live in the shell,
      // which the router popped back to.
      expect(container.read(childHomeTabProvider), ChildHomeTab.rewards);
    });

    testWidgets('the coach link selects the coach tab', (tester) async {
      final api = _FakeGrowthApi(messages: [_message(link: 'abny://coach')]);
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.coach);
    });

    testWidgets('an id-bearing goal link still lands on the goals tab',
        (tester) async {
      // Today's goals are not loaded in this harness, so the router cannot
      // open the goal itself — and lands on the list, which is the whole
      // point of the degradation.
      final api = _FakeGrowthApi(
        messages: [
          _message(link: 'abny://goal/3f7c1b2a-9d4e-4c8b-a1f0-2e5d6c7b8a90'),
        ],
      );
      final container = await _pumpGrowth(tester, api);
      container.read(childHomeTabProvider.notifier).state = ChildHomeTab.coach;

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });

    testWidgets('a link a child must never follow lands on their own home',
        (tester) async {
      // An approval queue is a parent's screen. The server will not send this
      // to a child; if it ever did, the child sees their own goals.
      final api = _FakeGrowthApi(messages: [_message(link: 'abny://approvals')]);
      final container = await _pumpGrowth(tester, api);
      container.read(childHomeTabProvider.notifier).state = ChildHomeTab.coach;

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
    });

    testWidgets(
        'a malformed link does not throw and does not reopen this screen',
        (tester) async {
      final api = _FakeGrowthApi(messages: [_message(link: 'not-a-link')]);
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      // The fallback IS this screen — «نموّي» is the child's inbox — and the
      // router recognises that the child is already standing on it, so no
      // second copy is pushed on top of the one they are reading.
      expect(find.byType(MyGrowthScreen), findsOneWidget);
      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });
  });

  group('a message card with no link', () {
    testWidgets('offers no tap affordance at all', (tester) async {
      final api = _FakeGrowthApi(messages: [_message()]);
      await _pumpGrowth(tester, api);

      // No chevron: the card looks exactly as inert as it is.
      expect(find.byIcon(Icons.chevron_left_rounded), findsNothing);
      expect(find.byIcon(Icons.chevron_right_rounded), findsNothing);
    });

    testWidgets('tapping it changes nothing and throws nothing',
        (tester) async {
      final api = _FakeGrowthApi(messages: [_message()]);
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });

    testWidgets('a card that carries a link shows the one affordance',
        (tester) async {
      final api = _FakeGrowthApi(messages: [_message(link: 'abny://rewards')]);
      await _pumpGrowth(tester, api);

      // Arabic is RTL, so the glyph points the way the child reads.
      expect(find.byIcon(Icons.chevron_left_rounded), findsOneWidget);
    });
  });

  // ==========================================================================
  // THE SERVER'S OWN INBOX ROW — the whole shape, not the two fields this
  // widget happens to read.
  //
  // `GET /life-intelligence/self/messages` serves a `child_messages` row:
  // every column the child is allowed to see, with the destination on `data`
  // beside them. The fixtures below are that row, so a change on either side of
  // the contract — a renamed field, a `data` that arrives as an explicit JSON
  // `null`, a payload that grows a second key — is a failing test here rather
  // than a card that stops being tappable in a child's hand.
  // ==========================================================================
  group('the server\'s own inbox row', () {
    /// One APPROVED, delivered row, field for field as the endpoint returns it.
    /// `data` is the ONLY field this app reads a destination from.
    Map<String, dynamic> serverRow({Object? data = _absent}) =>
        <String, dynamic>{
          'id': '9a1f7c2b-3d4e-4a5b-8c6d-7e8f9a0b1c2d',
          'childId': 'c0ffee00-1111-4222-8333-444455556666',
          'fromUserId': null,
          'authorType': 'AI',
          'approvalStatus': 'APPROVED',
          'category': 'BADGE_EARNED',
          'title': _title,
          'body': 'شطورة يا سلمى! كمّلي كده.',
          'deliveredAt': '2026-01-01T00:00:00.000Z',
          'acknowledgedAt': null,
          if (!identical(data, _absent)) 'data': data,
        };

    testWidgets('a delivered row carrying a destination opens it', (tester) async {
      final api = _FakeGrowthApi(
        messages: [
          serverRow(data: <String, dynamic>{'deepLink': 'abny://rewards'}),
        ],
      );
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.rewards);
    });

    testWidgets('an explicit `data: null` is not a link — the card stays inert',
        (tester) async {
      // The shape EVERY row written before that field existed arrives in, and
      // every message a parent typed. Nothing backfills a guess into it, so the
      // honest rendering is the one the child already had.
      final api = _FakeGrowthApi(messages: [serverRow(data: null)]);
      final container = await _pumpGrowth(tester, api);

      expect(find.byIcon(Icons.chevron_left_rounded), findsNothing);
      expect(find.byIcon(Icons.chevron_right_rounded), findsNothing);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });

    testWidgets('a row with no `data` key at all is the same non-answer',
        (tester) async {
      final api = _FakeGrowthApi(messages: [serverRow()]);
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(find.byIcon(Icons.chevron_left_rounded), findsNothing);
      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });

    testWidgets('the DESTINATION decides, never the category on the same row',
        (tester) async {
      // `category` is `BADGE_EARNED`, which the SERVER maps to the progress
      // surface — and this row says `abny://coach`. The child lands on the
      // coach, because this app parses the server's answer and does not
      // re-derive one from a notification type. A client that derived would
      // drift from its server inside a sprint, and nobody could audit which of
      // the two was right.
      final api = _FakeGrowthApi(
        messages: [serverRow(data: <String, dynamic>{'deepLink': 'abny://coach'})],
      );
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.coach);
    });

    testWidgets('a payload whose destination is malformed opens nothing new',
        (tester) async {
      // The server narrows this payload to one validated key, so this cannot
      // arrive today. If a future server ever widened it, the fallback is the
      // screen the child is already reading — never a crash, never a blank.
      final api = _FakeGrowthApi(
        messages: [
          serverRow(data: <String, dynamic>{'deepLink': 'https://evil.example/x'}),
        ],
      );
      final container = await _pumpGrowth(tester, api);

      await tester.tap(find.text(_title));
      await tester.pump();

      expect(find.byType(MyGrowthScreen), findsOneWidget);
      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
      expect(tester.takeException(), isNull);
    });

    testWidgets('the row is still acknowledged, destination or not',
        (tester) async {
      // A payload must not change what an inbox already did. `acknowledgedAt`
      // is null on this fixture, so the screen still tells the server the child
      // has seen it — the behaviour that predates deep links entirely.
      final api = _FakeGrowthApi(
        messages: [
          serverRow(data: <String, dynamic>{'deepLink': 'abny://progress'}),
        ],
      );
      await _pumpGrowth(tester, api);

      expect(api.acknowledged, ['9a1f7c2b-3d4e-4a5b-8c6d-7e8f9a0b1c2d']);
    });
  });

  group('followNotification — the entry point a push handler will call', () {
    /// The same shape a future `FirebaseMessaging` tap handler receives: the
    /// whole payload, not a parsed link.
    Future<ProviderContainer> pumpButton(
      WidgetTester tester,
      Object? payload,
    ) async {
      GoogleFonts.config.allowRuntimeFetching = false;
      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            familyGrowthApiProvider
                .overrideWithValue(_FakeGrowthApi(messages: const <dynamic>[])),
            localeControllerProvider.overrideWith(
              (ref) =>
                  LocaleController(storage: InMemoryLocaleStorage(AppLocale.ar)),
            ),
          ],
          child: MaterialApp(
            debugShowCheckedModeBanner: false,
            localizationsDelegates: const [
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: const [Locale('ar'), Locale('en')],
            home: Consumer(
              builder: (context, ref, _) => Scaffold(
                body: TextButton(
                  onPressed: () => ChildDeepLinkRouter.followNotification(
                    context,
                    ref,
                    payload,
                  ),
                  child: const Text('tap'),
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pump();
      return ProviderScope.containerOf(
    tester.element(find.byType(MaterialApp)),
    listen: false,
  );
    }

    testWidgets('routes a raw FCM-shaped data map through the same resolver',
        (tester) async {
      final container = await pumpButton(
        tester,
        const <String, dynamic>{
          'deepLink': 'abny://progress',
          'title': 'استمرّي!',
        },
      );

      await tester.tap(find.text('tap'));
      await tester.pump();

      expect(container.read(childHomeTabProvider), ChildHomeTab.progress);
    });

    testWidgets('a payload with no link at all opens the child\'s own inbox',
        (tester) async {
      final container = await pumpButton(
        tester,
        const <String, dynamic>{'title': 'no link here'},
      );

      await tester.tap(find.text('tap'));
      await tester.pump();
      await tester.pump(const Duration(seconds: 1));

      // The universal fallback: «نموّي», where the messages are. Never a
      // crash, never a blank screen.
      expect(tester.takeException(), isNull);
      expect(find.byType(MyGrowthScreen), findsOneWidget);
      expect(container.read(childHomeTabProvider), ChildHomeTab.today);
    });
  });
}
