// THE CHILD MAY ASK FOR A REWARD THEY CANNOT YET AFFORD.
//
// The server is explicit about this. `RewardsEngineService.requestRedemption`
// carries the reason above the method: «Requesting is allowed even if the
// child is currently short on coins — a parent may grant bonus coins after
// seeing the request. The balance check that actually matters happens at
// approval time.» It refuses only an unknown or inactive catalogue item.
//
// This screen used to disagree with it. `coins >= costCoins` decided locally,
// the button went grey and `onRedeem` went null, so a child ten coins short
// tapped a dead control and the parent never learned the child wanted the
// thing — a request that the server would have accepted was stopped by the
// client that had no authority to stop it.
//
// These tests fail if the gate ever comes back: one taps a store item priced
// ABOVE the balance and asserts the call reaches the API.
//
// EXECUTION STATUS: NEVER RUN. There is no Flutter SDK and no Dart SDK in the
// authoring environment, and pub.dev is unreachable, so this file has never
// been executed. It is STATIC VERIFIED by `scripts/dart_preflight.py`,
// `scripts/verify_dart_imports.py` and `scripts/verify_l10n_parity.py` only.

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:child_app/core/di/providers.dart';
import 'package:child_app/core/localization/locale_controller.dart';
import 'package:child_app/core/localization/localization_engine.dart';
import 'package:child_app/features/family_growth/api/family_growth_api.dart';
import 'package:child_app/features/family_growth/presentation/rewards_screen.dart';

/// Hand-written rather than generated by `mockito`, for the reason every other
/// fake in this app gives: codegen needs `pub get`, and pub.dev is not
/// reachable from where these were written.
class _FakeGrowthApi implements FamilyGrowthApi {
  _FakeGrowthApi({required this.coins, required this.store});

  final int coins;
  final List<dynamic> store;

  /// The catalogue ids `redeemReward` was actually called with. A screen that
  /// silently drops the tap leaves this empty, which is the failure this file
  /// is written to catch.
  final List<String> requested = <String>[];

  @override
  Future<Map<String, dynamic>> getRewardsAccount() async =>
      <String, dynamic>{'coins': coins, 'xp': 40, 'level': 2};

  @override
  Future<List<dynamic>> getRewardsStore() async => store;

  @override
  Future<void> redeemReward(String catalogItemId) async {
    requested.add(catalogItemId);
  }

  @override
  dynamic noSuchMethod(Invocation invocation) => throw StateError(
        '_FakeGrowthApi has no stub for ${invocation.memberName} — if the '
        'rewards screen now calls it, stub it here.',
      );
}

Map<String, dynamic> _item({
  String id = 'item_1',
  String title = 'رحلة الملاهي',
  int costCoins = 100,
}) =>
    <String, dynamic>{'id': id, 'title': title, 'costCoins': costCoins};

Future<void> _pumpRewards(WidgetTester tester, _FakeGrowthApi api) async {
  GoogleFonts.config.allowRuntimeFetching = false;

  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        familyGrowthApiProvider.overrideWithValue(api),
        localeControllerProvider.overrideWith(
          (ref) => LocaleController(storage: InMemoryLocaleStorage(AppLocale.ar)),
        ),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        locale: const Locale('ar'),
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: const [Locale('ar'), Locale('en')],
        home: const RewardsScreen(),
      ),
    ),
  );

  // Not pumpAndSettle: the celebration overlay animates and would never
  // settle. One frame for the tree, one long one for the two awaited fetches.
  await tester.pump();
  await tester.pump(const Duration(seconds: 1));
}

String _ar(String key, {Map<String, Object>? options}) =>
    translate(AppLocale.ar, key, options: options);

void main() {
  group('a reward the child cannot yet afford', () {
    testWidgets('still reaches the server when tapped', (tester) async {
      final api = _FakeGrowthApi(
        coins: 90,
        store: [_item(costCoins: 100)],
      );
      await _pumpRewards(tester, api);

      await tester.tap(find.text(_ar('rewards.getIt')));
      await tester.pump();

      expect(api.requested, <String>['item_1']);
    });

    testWidgets('offers the SAME button as one the child can afford — no '
        '«need more» dead end', (tester) async {
      final api = _FakeGrowthApi(coins: 90, store: [_item(costCoins: 100)]);
      await _pumpRewards(tester, api);

      final button = tester.widget<FilledButton>(find.byType(FilledButton));
      expect(button.onPressed, isNotNull);
      expect(find.text(_ar('rewards.getIt')), findsOneWidget);
    });

    testWidgets('says how short the child is, and that asking is allowed',
        (tester) async {
      final api = _FakeGrowthApi(coins: 90, store: [_item(costCoins: 100)]);
      await _pumpRewards(tester, api);

      expect(
        find.text(_ar('rewards.askAnyway', options: {'count': 10})),
        findsOneWidget,
      );
    });

    testWidgets('says nothing about a shortfall when there is none',
        (tester) async {
      final api = _FakeGrowthApi(coins: 120, store: [_item(costCoins: 100)]);
      await _pumpRewards(tester, api);

      expect(
        find.text(_ar('rewards.askAnyway', options: {'count': 10})),
        findsNothing,
      );
      expect(find.text(_ar('rewards.getIt')), findsOneWidget);
    });
  });

  group('an empty family store', () {
    testWidgets('says so instead of showing a bare screen', (tester) async {
      final api = _FakeGrowthApi(coins: 10, store: const <dynamic>[]);
      await _pumpRewards(tester, api);

      expect(find.text(_ar('rewards.noRewardsYet')), findsOneWidget);
    });
  });
}
