-- HAND-AUTHORED MIGRATION — NOT GENERATED BY `prisma migrate dev`.
-- The Prisma CLI cannot reach binaries.prisma.sh in this sandboxed
-- environment (confirmed via repeated real attempts, not assumed).
-- This file is written by hand to match Prisma's own DDL conventions
-- as closely as possible, but has NEVER been run against a real
-- Postgres instance in this session (no database is reachable here either).
--
-- REQUIRED BEFORE THIS IS TRUSTED: run `prisma migrate dev` in a real,
-- network-unrestricted environment to generate and cross-check the
-- authoritative version of this file, then replace this file with that output.

CREATE TYPE "SmartTaskStatus" AS ENUM ('SUGGESTED', 'ACCEPTED', 'COMPLETED', 'DISMISSED');
CREATE TYPE "RewardType" AS ENUM ('XP', 'COINS', 'BADGE');
CREATE TYPE "RedemptionStatus" AS ENUM ('REQUESTED', 'APPROVED', 'DENIED', 'FULFILLED');
CREATE TYPE "MessageAuthorType" AS ENUM ('PARENT', 'AI');
CREATE TYPE "MessageApprovalStatus" AS ENUM ('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "ActivitySocialContext" AS ENUM ('SOLO', 'GROUP', 'TEAM');
CREATE TYPE "TimelineCategory" AS ENUM ('HEALTH', 'LEARNING', 'FAITH', 'REWARDS', 'SAFETY', 'HABITS', 'FAMILY');

CREATE TABLE "habits" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "is_custom" BOOLEAN NOT NULL DEFAULT true,
    "is_shared" BOOLEAN NOT NULL DEFAULT false,
    "created_by_user_id" UUID,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP(3),
    CONSTRAINT "habits_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "habits_child_id_is_active_idx" ON "habits"("child_id", "is_active");

CREATE TABLE "habit_completions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "habit_id" UUID NOT NULL,
    "child_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "completed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "habit_completions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "habit_completions_habit_id_date_key" ON "habit_completions"("habit_id", "date");
CREATE INDEX "habit_completions_child_id_date_idx" ON "habit_completions"("child_id", "date");

CREATE TABLE "rewards_accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "xp" INTEGER NOT NULL DEFAULT 0,
    "coins" INTEGER NOT NULL DEFAULT 0,
    "stars" INTEGER NOT NULL DEFAULT 0,
    "level" INTEGER NOT NULL DEFAULT 1,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "rewards_accounts_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "rewards_accounts_child_id_key" ON "rewards_accounts"("child_id");

CREATE TABLE "rewards_ledger_entries" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "reward_type" "RewardType" NOT NULL,
    "amount" INTEGER NOT NULL,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "rewards_ledger_entries_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "rewards_ledger_entries_child_id_created_at_idx" ON "rewards_ledger_entries"("child_id", "created_at");

CREATE TABLE "badge_definitions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "criteria" JSONB NOT NULL,
    "is_group_achievement" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "badge_definitions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "badge_definitions_key_key" ON "badge_definitions"("key");

CREATE TABLE "child_badge_awards" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "badge_id" UUID NOT NULL,
    "awarded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "child_badge_awards_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "child_badge_awards_child_id_badge_id_key" ON "child_badge_awards"("child_id", "badge_id");

CREATE TABLE "reward_catalog_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "family_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "cost_coins" INTEGER NOT NULL,
    "created_by_user_id" UUID NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "reward_catalog_items_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reward_catalog_items_family_id_is_active_idx" ON "reward_catalog_items"("family_id", "is_active");

CREATE TABLE "reward_redemptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "reward_catalog_item_id" UUID NOT NULL,
    "status" "RedemptionStatus" NOT NULL DEFAULT 'REQUESTED',
    "requested_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "decided_at" TIMESTAMP(3),
    "decided_by_user_id" UUID,
    CONSTRAINT "reward_redemptions_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reward_redemptions_child_id_status_idx" ON "reward_redemptions"("child_id", "status");

CREATE TABLE "reward_rules" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "family_id" UUID,
    "trigger_engine" TEXT NOT NULL,
    "trigger_condition" JSONB NOT NULL,
    "reward_type" "RewardType" NOT NULL,
    "reward_amount_or_badge_id" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "reward_rules_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reward_rules_family_id_is_active_idx" ON "reward_rules"("family_id", "is_active");

CREATE TABLE "child_messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "from_user_id" UUID,
    "author_type" "MessageAuthorType" NOT NULL,
    "approval_status" "MessageApprovalStatus" NOT NULL DEFAULT 'NOT_REQUIRED',
    "category" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "delivered_at" TIMESTAMP(3),
    "acknowledged_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "child_messages_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "child_messages_child_id_delivered_at_idx" ON "child_messages"("child_id", "delivered_at");
CREATE INDEX "child_messages_approval_status_idx" ON "child_messages"("approval_status");

CREATE TABLE "family_broadcast_messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "family_id" UUID NOT NULL,
    "authored_by_user_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "family_broadcast_messages_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "life_timeline_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "child_id" UUID NOT NULL,
    "source_engine" TEXT NOT NULL,
    "category" "TimelineCategory" NOT NULL,
    "event_type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,
    CONSTRAINT "life_timeline_events_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "life_timeline_events_child_id_occurred_at_idx" ON "life_timeline_events"("child_id", "occurred_at");
CREATE INDEX "life_timeline_events_child_id_category_idx" ON "life_timeline_events"("child_id", "category");

CREATE TABLE "child_digital_twin_projections" (
    "child_id" UUID NOT NULL,
    "health_slice" JSONB,
    "learning_slice" JSONB,
    "faith_slice" JSONB,
    "behavior_slice" JSONB,
    "habits_slice" JSONB,
    "social_slice" JSONB,
    "safety_slice" JSONB,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "child_digital_twin_projections_pkey" PRIMARY KEY ("child_id")
);

-- Foreign keys
ALTER TABLE "habits" ADD CONSTRAINT "habits_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "habits" ADD CONSTRAINT "habits_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL;
ALTER TABLE "habit_completions" ADD CONSTRAINT "habit_completions_habit_id_fkey" FOREIGN KEY ("habit_id") REFERENCES "habits"("id") ON DELETE CASCADE;
ALTER TABLE "habit_completions" ADD CONSTRAINT "habit_completions_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "rewards_accounts" ADD CONSTRAINT "rewards_accounts_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "rewards_ledger_entries" ADD CONSTRAINT "rewards_ledger_entries_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "child_badge_awards" ADD CONSTRAINT "child_badge_awards_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "child_badge_awards" ADD CONSTRAINT "child_badge_awards_badge_id_fkey" FOREIGN KEY ("badge_id") REFERENCES "badge_definitions"("id") ON DELETE CASCADE;
ALTER TABLE "reward_catalog_items" ADD CONSTRAINT "reward_catalog_items_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE;
ALTER TABLE "reward_catalog_items" ADD CONSTRAINT "reward_catalog_items_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE;
ALTER TABLE "reward_redemptions" ADD CONSTRAINT "reward_redemptions_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "reward_redemptions" ADD CONSTRAINT "reward_redemptions_reward_catalog_item_id_fkey" FOREIGN KEY ("reward_catalog_item_id") REFERENCES "reward_catalog_items"("id") ON DELETE CASCADE;
ALTER TABLE "reward_rules" ADD CONSTRAINT "reward_rules_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE;
ALTER TABLE "child_messages" ADD CONSTRAINT "child_messages_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "child_messages" ADD CONSTRAINT "child_messages_from_user_id_fkey" FOREIGN KEY ("from_user_id") REFERENCES "users"("id") ON DELETE SET NULL;
ALTER TABLE "family_broadcast_messages" ADD CONSTRAINT "family_broadcast_messages_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "families"("id") ON DELETE CASCADE;
ALTER TABLE "family_broadcast_messages" ADD CONSTRAINT "family_broadcast_messages_authored_by_user_id_fkey" FOREIGN KEY ("authored_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE;
ALTER TABLE "life_timeline_events" ADD CONSTRAINT "life_timeline_events_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
ALTER TABLE "child_digital_twin_projections" ADD CONSTRAINT "child_digital_twin_projections_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE;
