/// Mirrors apps/admin-dashboard/src/shared/i18n/localizationEngine.ts's
/// design exactly: fallback strategy (requested locale -> default locale
/// -> the raw key itself), simple `_one`/`_other` pluralization,
/// interpolation via `{{token}}`. Resources are embedded as Dart const
/// maps rather than loaded from JSON assets — with no Flutter toolchain
/// available to verify `pubspec.yaml` asset bundling actually works in
/// this environment, embedding is the only path verifiable via static
/// review alone. Migrating to bundled `.arb`/JSON resources (matching
/// the Dashboard's approach exactly) is a real, trivial follow-up once
/// a real `flutter build` can confirm the asset pipeline works.
library;

enum AppLocale { en, ar }

const Map<AppLocale, Map<String, String>> _resources = {
  AppLocale.en: {
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong.',
    'common.retry': 'Retry',
    'common.offlineBanner': 'No internet connection',
    'digitalTwin.title': 'Digital Twin',
    'digitalTwin.notARankingTool': 'A picture of your child\u2019s current progress across areas \u2014 not a score for ranking or comparing children.',
    'digitalTwin.growthScore': 'Growth Score',
    'digitalTwin.basedOnSubScores': 'Based on {{count}} of {{total}} available indicators',
    'digitalTwin.health': 'Health',
    'digitalTwin.learning': 'Learning',
    'digitalTwin.faith': 'Faith',
    'digitalTwin.habits': 'Habits',
    'digitalTwin.social': 'Social',
    'digitalTwin.behavior': 'Behavior',
    'digitalTwin.safety': 'Safety',
    'digitalTwin.notYetAvailable': 'Not yet available',
    'lifeTimeline.title': 'Life Timeline',
    'lifeTimeline.all': 'All',
    'lifeTimeline.empty': 'No milestones yet.',
    'lifeTimeline.category.health': 'Health',
    'lifeTimeline.category.learning': 'Learning',
    'lifeTimeline.category.faith': 'Faith',
    'lifeTimeline.category.rewards': 'Rewards',
    'lifeTimeline.category.safety': 'Safety',
    'lifeTimeline.category.habits': 'Habits',
    'lifeTimeline.category.family': 'Family',
    'habitTracker.title': 'Habits',
    'habitTracker.empty': 'No habits yet.',
    'habitTracker.shared': 'Shared',
    'habitTracker.markDone': 'Mark done',
    'healthTrend.title': 'Health',
    'healthTrend.score': 'Health Score',
    'healthTrend.hydration': 'Hydration',
    'learningProgress.title': 'Learning',
    'pendingApprovals.title': 'Pending Approvals',
    'pendingApprovals.empty': 'Nothing waiting for your approval right now.',
    'pendingApprovals.approve': 'Approve',
    'pendingApprovals.reject': 'Decline',
    'learningProgress.streak': 'Learning Streak',
    'learningProgress.streakDays': '{{count}} days',
    'learningProgress.sessions': 'Study sessions (30d)',
    'learningProgress.minutes': 'Total minutes (30d)',
    'learningProgress.avgScore': 'Average score',
    'learningProgress.notYetAvailable': 'Not yet available',
    'healthTrend.activity': 'Activity',
    'healthTrend.sleep': 'Sleep',
    'healthTrend.meals': 'Meals logged',
    'healthTrend.minutes': 'min',
    'healthTrend.hours': 'hrs',
    'healthTrend.notLogged': 'Not logged',
    'healthTrend.logWater': 'Log water',
    'faithProgress.title': 'Faith',
    'faithProgress.empty': 'No practices yet.',
    'faithProgress.logToday': 'Log today',
    'familyStore.title': 'Family Store',
    'familyStore.empty': 'No rewards in the store yet.',
    'familyStore.coins': 'coins',
    'coaching.title': 'Coaching',
    'coaching.empty': 'No recommendations right now.',
    'coaching.track.parent': 'For you',
    'coaching.track.child': 'For your child',
    'coaching.track.family': 'For the family',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'auth.loginTitle': 'Parent Login',
    'auth.loginTagline': 'Follow, protect, and guide your children\u2019s digital journey',
    'wellbeing.title': 'Digital Wellbeing',
    'wellbeing.insightTitle': "Today's Insight",
    'wellbeing.noData': 'No wellbeing data yet \u2014 it will appear once the device has synced at least one day.',
    'wellbeing.avgScreenTime': 'Average screen time',
    'wellbeing.avgPickups': 'Average pickups',
    'wellbeing.nightUsage': 'Average night usage',
    'wellbeing.blockedAttempts': 'Blocked attempts',
    'wellbeing.minutesPerDay': 'min/day',
    'wellbeing.windowNote': 'Based on {daysWithData} of the last {days} days',
    'subscription.title': 'Subscription',
    'subscription.availablePlans': 'Available Plans',
    'subscription.trialTitle': 'Free Trial Active',
    'subscription.trialBody': '{days} day(s) remaining in your trial',
    'subscription.activeTitle': 'Subscription Active',
    'subscription.activeBody': 'You are on the {plan} plan',
    'subscription.pastDueTitle': 'Payment Issue',
    'subscription.pastDueBody': 'Your last payment failed. Please update your payment method to keep your subscription active.',
    'subscription.inactiveTitle': 'No Active Subscription',
    'subscription.inactiveBody': 'Choose a plan below to continue using premium features.',
    'subscription.noneTitle': 'Get Started',
    'subscription.noneBody': 'Choose a plan to begin.',
    'subscription.free': 'Free',
    'subscription.currentPlan': 'Current Plan',
    'subscription.choosePlan': 'Choose Plan',
    'subscription.cancel': 'Cancel Subscription',
    'subscription.viewHistory': 'View Billing History',
    'billingHistory.title': 'Billing History',
    'billingHistory.empty': 'No invoices yet.',
    'support.title': 'Help & Support',
    'support.faqTitle': 'Frequently Asked Questions',
    'support.faq.q1': 'How do I pair my child\u2019s device?',
    'support.faq.a1': 'Go to Settings > Add Child on this app, generate a pairing code, then enter that code in the Child App on your child\u2019s device within the time shown.',
    'support.faq.q2': 'Why does my child\u2019s status show as offline?',
    'support.faq.a2': 'This usually means the device hasn\u2019t sent a heartbeat recently \u2014 check that the Child App has Battery Optimization disabled and Accessibility Service still enabled on their device.',
    'support.faq.q3': 'How do screen time limits work?',
    'support.faq.a3': 'Limits you set are synced to the device and enforced even without an internet connection, using the last successfully synced policy.',
    'support.faq.q4': 'Can I change my subscription plan?',
    'support.faq.a4': 'Yes \u2014 go to Settings > Subscription to see available plans and switch at any time.',
    'support.faq.q5': 'Is my child\u2019s data private?',
    'support.faq.a5': 'We collect only aggregated usage summaries, never raw message content, photos, or keystrokes. See our Privacy Policy for full details.',
    'support.stillNeedHelp': 'Still need help?',
    'support.contactBody': 'Send us a message and we\u2019ll get back to you by email.',
    'support.contactButton': 'Contact Us',
    'support.contactTitle': 'Contact Support',
    'support.email': 'Your Email',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.send': 'Send Message',
    'support.sentTitle': 'Message Sent!',
    'support.sentBody': 'We\u2019ve received your message and will reply by email soon.',
    'dashboard.pairDevice': 'Pair a Device',
    'createChild.title': 'Add a Child',
    'createChild.firstName': 'First Name',
    'createChild.lastNameOptional': 'Last Name (optional)',
    'createChild.dateOfBirth': 'Date of Birth',
    'createChild.selectDate': 'Select a date',
    'createChild.consentTitle': 'Before you continue',
    'createChild.consentBody': 'By adding this child, you agree to basic data collection, location tracking, app usage monitoring, and AI behavior analysis for their protection. You can review and change any of these anytime in Settings > Manage Consents.',
    'createChild.submit': 'Add Child',
    'consents.title': 'Manage Consents',
    'consents.selectChild': 'Select Child',
    'consents.noChildren': 'Add a child first to manage their consent settings.',
    'consents.explanation': 'Control exactly what data is collected for each child. You can turn any of these off at any time \u2014 some features may stop working if you do.',
    'consents.type.DATA_COLLECTION.title': 'Basic Data Collection',
    'consents.type.DATA_COLLECTION.description': 'Core account and usage data needed for the app to function.',
    'consents.type.LOCATION_TRACKING.title': 'Location Tracking',
    'consents.type.LOCATION_TRACKING.description': 'Track your child\u2019s device location.',
    'consents.type.APP_USAGE_MONITORING.title': 'App Usage Monitoring',
    'consents.type.APP_USAGE_MONITORING.description': 'Collect aggregated app usage summaries \u2014 never raw content.',
    'consents.type.AI_BEHAVIOR_ANALYSIS.title': 'AI Behavior Analysis',
    'consents.type.AI_BEHAVIOR_ANALYSIS.description': 'Let AI analyze behavioral patterns to provide insights and coaching.',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.title': 'Keyboard Behavior Analysis',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.description': 'Not yet available \u2014 reserved for a future safety feature under separate review.',
    'consents.type.HEALTH_DATA.title': 'Health Data',
    'consents.type.HEALTH_DATA.description': 'Collect health-related data like hydration and activity logs.',
    'deleteAccount.title': 'Delete Account',
    'deleteAccount.warningTitle': 'This cannot be undone',
    'deleteAccount.warningBody': 'Deleting your account will remove access for every child profile, cancel your subscription, and sign you out of all devices. Your data will be anonymized immediately.',
    'deleteAccount.confirmCheckbox': 'I understand this action is permanent',
    'deleteAccount.currentPassword': 'Enter your current password to confirm',
    'deleteAccount.submit': 'Permanently Delete My Account',
    'auth.acceptTerms': 'I agree to the Terms of Service and Privacy Policy',
    'redeemCode.entryPoint': 'Have a Partner Code?',
    'redeemCode.title': 'Redeem a Code',
    'redeemCode.explanation': 'Enter a code from a partner (like your employer, bank, or telecom provider) to unlock a benefit for your account.',
    'redeemCode.codeLabel': 'Enter Code',
    'redeemCode.submit': 'Redeem Code',
    'dashboard.notificationsTooltip': 'Notifications',
    'dashboard.settingsTooltip': 'Settings',
    'common.done': 'Done',
    'dashboard.firstChildTitle': 'Welcome! Let\u2019s add your first child',
    'dashboard.firstChildBody': 'Add a child profile, then pair their device to start protecting and guiding their digital journey.',
    'dashboard.addFirstChild': 'Add Your First Child',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Log In',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create a new account',
    'auth.registerTitle': 'Create Your Family Account',
    'auth.fullName': 'Full Name',
    'auth.phone': 'Phone',
    'auth.register': 'Create Account',
    'auth.haveAccount': 'Already have an account?',
    'family.setupTitle': 'Set Up Your Family',
    'family.name': 'Family Name',
    'family.country': 'Country',
    'family.numberOfChildren': 'Number of Children',
    'family.continueButton': 'Continue',
    'dashboard.title': 'Home',
    'dashboard.familySummary': 'Family Summary',
    'dashboard.children': '{{count}} children',
    'dashboard.children_one': '{{count}} child',
    'dashboard.children_other': '{{count}} children',
    'dashboard.devices': '{{count}} devices',
    'dashboard.alerts': '{{count}} alerts',
    'dashboard.addChild': 'Add Child',
    'dashboard.viewReports': 'View Reports',
    'dashboard.notifications': 'Notifications',
    'dashboard.settings': 'Settings',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'pairing.addChildTitle': 'Add a Child',
    'pairing.noChildrenYet': 'Add a child from your Dashboard first before pairing a device.',
    'pairing.selectChild': 'Select Child',
    'pairing.generateCode': 'Generate Pairing Code',
    'pairing.validFor': 'Valid for',
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications yet.',
    'notifications.markAllRead': 'Mark all as read',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.profile': 'Profile',
    'settings.subscription': 'Subscription',
    'settings.privacy': 'Privacy',
    'settings.logout': 'Log Out',
  },
  AppLocale.ar: {
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'حدث خطأ ما.',
    'common.retry': 'إعادة المحاولة',
    'common.offlineBanner': 'لا يوجد اتصال بالإنترنت',
    'digitalTwin.title': 'التوأم الرقمي',
    'digitalTwin.notARankingTool': 'صورة لتقدّم طفلك الحالي عبر عدة مجالات — وليست درجة لتصنيف الأطفال أو مقارنتهم.',
    'digitalTwin.growthScore': 'مؤشر النمو',
    'digitalTwin.basedOnSubScores': 'بناءً على {{count}} من أصل {{total}} مؤشرات متاحة',
    'digitalTwin.health': 'الصحة',
    'digitalTwin.learning': 'التعلّم',
    'digitalTwin.faith': 'الإيمان',
    'digitalTwin.habits': 'العادات',
    'digitalTwin.social': 'الاجتماعي',
    'digitalTwin.behavior': 'السلوك',
    'digitalTwin.safety': 'الأمان',
    'digitalTwin.notYetAvailable': 'غير متاح بعد',
    'lifeTimeline.title': 'الخط الزمني للحياة',
    'lifeTimeline.all': 'الكل',
    'lifeTimeline.empty': 'لا توجد أحداث بعد.',
    'lifeTimeline.category.health': 'الصحة',
    'lifeTimeline.category.learning': 'التعلّم',
    'lifeTimeline.category.faith': 'الإيمان',
    'lifeTimeline.category.rewards': 'المكافآت',
    'lifeTimeline.category.safety': 'الأمان',
    'lifeTimeline.category.habits': 'العادات',
    'lifeTimeline.category.family': 'الأسرة',
    'habitTracker.title': 'العادات',
    'habitTracker.empty': 'لا توجد عادات بعد.',
    'habitTracker.shared': 'مشتركة',
    'habitTracker.markDone': 'تم الإنجاز',
    'healthTrend.title': 'الصحة',
    'healthTrend.score': 'مؤشر الصحة',
    'healthTrend.hydration': 'الترطيب',
    'learningProgress.title': 'التعليم',
    'pendingApprovals.title': 'بانتظار الموافقة',
    'pendingApprovals.empty': 'لا يوجد شيء ينتظر موافقتك الآن.',
    'pendingApprovals.approve': 'موافقة',
    'pendingApprovals.reject': 'رفض',
    'learningProgress.streak': 'تتابع التعلم',
    'learningProgress.streakDays': '{{count}} يوم',
    'learningProgress.sessions': 'جلسات المذاكرة (30 يوم)',
    'learningProgress.minutes': 'إجمالي الدقائق (30 يوم)',
    'learningProgress.avgScore': 'متوسط الدرجات',
    'learningProgress.notYetAvailable': 'غير متاح بعد',
    'healthTrend.activity': 'النشاط',
    'healthTrend.sleep': 'النوم',
    'healthTrend.meals': 'الوجبات المسجَّلة',
    'healthTrend.minutes': 'دقيقة',
    'healthTrend.hours': 'ساعة',
    'healthTrend.notLogged': 'غير مُسجَّل',
    'healthTrend.logWater': 'سجّل ماء',
    'faithProgress.title': 'الإيمان',
    'faithProgress.empty': 'لا توجد ممارسات بعد.',
    'faithProgress.logToday': 'سجّل اليوم',
    'familyStore.title': 'متجر الأسرة',
    'familyStore.empty': 'لا توجد مكافآت بالمتجر بعد.',
    'familyStore.coins': 'عملة',
    'coaching.title': 'التوجيه',
    'coaching.empty': 'لا توجد توصيات حاليًا.',
    'coaching.track.parent': 'لك',
    'coaching.track.child': 'لطفلك',
    'coaching.track.family': 'للأسرة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'auth.loginTitle': 'دخول الوالدين',
    'auth.loginTagline': 'تابع، احمِ، ووجّه رحلة أطفالك الرقمية',
    'wellbeing.title': 'الرفاهية الرقمية',
    'wellbeing.insightTitle': 'ملاحظة اليوم',
    'wellbeing.noData': 'لا توجد بيانات رفاهية رقمية بعد \u2014 ستظهر بمجرد مزامنة الجهاز ليوم واحد على الأقل.',
    'wellbeing.avgScreenTime': 'متوسط وقت الشاشة',
    'wellbeing.avgPickups': 'متوسط مرات الالتقاط',
    'wellbeing.nightUsage': 'متوسط الاستخدام الليلي',
    'wellbeing.blockedAttempts': 'محاولات محظورة',
    'wellbeing.minutesPerDay': 'دقيقة/يوم',
    'wellbeing.windowNote': 'بناءً على {daysWithData} من آخر {days} يوم',
    'subscription.title': 'الاشتراك',
    'subscription.availablePlans': 'الخطط المتاحة',
    'subscription.trialTitle': 'التجربة المجانية نشطة',
    'subscription.trialBody': 'باقي {days} يوم في فترتك التجريبية',
    'subscription.activeTitle': 'الاشتراك نشط',
    'subscription.activeBody': 'أنت مشترك في خطة {plan}',
    'subscription.pastDueTitle': 'مشكلة في الدفع',
    'subscription.pastDueBody': 'فشلت آخر عملية دفع. برجاء تحديث وسيلة الدفع للحفاظ على اشتراكك نشطًا.',
    'subscription.inactiveTitle': 'لا يوجد اشتراك نشط',
    'subscription.inactiveBody': 'اختر خطة أدناه للاستمرار في استخدام الميزات المميزة.',
    'subscription.noneTitle': 'ابدأ الآن',
    'subscription.noneBody': 'اختر خطة للبدء.',
    'subscription.free': 'مجانًا',
    'subscription.currentPlan': 'خطتك الحالية',
    'subscription.choosePlan': 'اختر الخطة',
    'subscription.cancel': 'إلغاء الاشتراك',
    'subscription.viewHistory': 'عرض تاريخ الفوترة',
    'billingHistory.title': 'تاريخ الفوترة',
    'billingHistory.empty': 'لا توجد فواتير بعد.',
    'support.title': 'المساعدة والدعم',
    'support.faqTitle': 'الأسئلة الشائعة',
    'support.faq.q1': 'إزاي أقرن جهاز طفلي؟',
    'support.faq.a1': 'روح لـ الإعدادات > إضافة طفل في هذا التطبيق، ولّد كود إقران، وبعدها اكتب الكود ده في تطبيق الطفل على جهازه خلال المدة الظاهرة.',
    'support.faq.q2': 'ليه حالة طفلي ظاهرة "غير متصل"؟',
    'support.faq.a2': 'غالبًا معناها إن الجهاز مبعتش نبضة اتصال مؤخرًا \u2014 تأكد إن تحسين البطارية معطَّل وخدمة إمكانية الوصول لسه مفعَّلة على جهاز طفلك.',
    'support.faq.q3': 'إزاي تشتغل حدود وقت الشاشة؟',
    'support.faq.a3': 'الحدود اللي بتحددها بتتزامن مع الجهاز وتُفرَض حتى بدون اتصال إنترنت، باستخدام آخر سياسة اتزامنت بنجاح.',
    'support.faq.q4': 'أقدر أغيّر خطة اشتراكي؟',
    'support.faq.a4': 'أيوه \u2014 روح لـ الإعدادات > الاشتراك عشان تشوف الخطط المتاحة وتغيّر في أي وقت.',
    'support.faq.q5': 'بيانات طفلي آمنة؟',
    'support.faq.a5': 'إحنا بنجمع بس ملخّصات استخدام مُجمَّعة، ومش بنجمع محتوى رسائل خام، صور، أو ضغطات مفاتيح. راجع سياسة الخصوصية لتفاصيل كاملة.',
    'support.stillNeedHelp': 'لسه محتاج مساعدة؟',
    'support.contactBody': 'ابعتلنا رسالة وهنرد عليك بالإيميل.',
    'support.contactButton': 'تواصل معنا',
    'support.contactTitle': 'تواصل مع الدعم',
    'support.email': 'إيميلك',
    'support.subject': 'الموضوع',
    'support.message': 'الرسالة',
    'support.send': 'إرسال الرسالة',
    'support.sentTitle': 'تم إرسال الرسالة!',
    'support.sentBody': 'استلمنا رسالتك وهنرد عليك بالإيميل قريبًا.',
    'dashboard.pairDevice': 'قرن جهاز',
    'createChild.title': 'إضافة طفل',
    'createChild.firstName': 'الاسم الأول',
    'createChild.lastNameOptional': 'اسم العائلة (اختياري)',
    'createChild.dateOfBirth': 'تاريخ الميلاد',
    'createChild.selectDate': 'اختر تاريخ',
    'createChild.consentTitle': 'قبل ما تكمل',
    'createChild.consentBody': 'بإضافة الطفل ده، إنت بتوافق على جمع بيانات أساسية، تتبّع الموقع، مراقبة استخدام التطبيقات، وتحليل السلوك بالذكاء الاصطناعي لحمايته. تقدر تراجع وتغيّر أي من دول في أي وقت من الإعدادات > إدارة الموافقات.',
    'createChild.submit': 'إضافة الطفل',
    'consents.title': 'إدارة الموافقات',
    'consents.selectChild': 'اختر الطفل',
    'consents.noChildren': 'ضيف طفل الأول عشان تقدر تدير إعدادات الموافقة بتاعته.',
    'consents.explanation': 'تحكّم بالظبط في البيانات اللي بتتجمع لكل طفل. تقدر تقفل أي منها في أي وقت \u2014 بعض الميزات ممكن تتوقف لو عملت كده.',
    'consents.type.DATA_COLLECTION.title': 'جمع البيانات الأساسي',
    'consents.type.DATA_COLLECTION.description': 'بيانات الحساب والاستخدام الأساسية اللازمة لعمل التطبيق.',
    'consents.type.LOCATION_TRACKING.title': 'تتبّع الموقع',
    'consents.type.LOCATION_TRACKING.description': 'تتبّع موقع جهاز طفلك.',
    'consents.type.APP_USAGE_MONITORING.title': 'مراقبة استخدام التطبيقات',
    'consents.type.APP_USAGE_MONITORING.description': 'جمع ملخّصات مُجمَّعة لاستخدام التطبيقات \u2014 صفر محتوى خام.',
    'consents.type.AI_BEHAVIOR_ANALYSIS.title': 'تحليل السلوك بالذكاء الاصطناعي',
    'consents.type.AI_BEHAVIOR_ANALYSIS.description': 'خلّي الذكاء الاصطناعي يحلّل الأنماط السلوكية عشان يدّيك رؤى وإرشاد.',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.title': 'تحليل سلوك لوحة المفاتيح',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.description': 'غير متاحة بعد \u2014 محجوزة لميزة أمان مستقبلية تحت مراجعة منفصلة.',
    'consents.type.HEALTH_DATA.title': 'البيانات الصحية',
    'consents.type.HEALTH_DATA.description': 'جمع بيانات صحية زي سجلات شرب المياه والنشاط.',
    'deleteAccount.title': 'حذف الحساب',
    'deleteAccount.warningTitle': 'هذا الإجراء لا يمكن التراجع عنه',
    'deleteAccount.warningBody': 'حذف حسابك هيشيل الوصول لكل ملفات الأطفال، يلغي اشتراكك، ويسجّل خروجك من كل الأجهزة. بياناتك هتتخفى هويتها فورًا.',
    'deleteAccount.confirmCheckbox': 'أنا فاهم إن الإجراء ده نهائي',
    'deleteAccount.currentPassword': 'اكتب كلمة السر الحالية للتأكيد',
    'deleteAccount.submit': 'احذف حسابي نهائيًا',
    'auth.acceptTerms': 'أوافق على شروط الاستخدام وسياسة الخصوصية',
    'redeemCode.entryPoint': 'عندك كود شراكة؟',
    'redeemCode.title': 'استبدال كود',
    'redeemCode.explanation': 'اكتب كود من شريك (زي جهة عملك، بنكك، أو شركة الاتصالات بتاعتك) عشان تفتح ميزة لحسابك.',
    'redeemCode.codeLabel': 'اكتب الكود',
    'redeemCode.submit': 'استبدال الكود',
    'dashboard.notificationsTooltip': 'الإشعارات',
    'dashboard.settingsTooltip': 'الإعدادات',
    'common.done': 'تم',
    'dashboard.firstChildTitle': 'أهلًا بيك! يلا نضيف طفلك الأول',
    'dashboard.firstChildBody': 'ضيف ملف الطفل، وبعدين قرن جهازه عشان تبدأ تحمي وتوجّه رحلته الرقمية.',
    'dashboard.addFirstChild': 'ضيف طفلك الأول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.login': 'دخول',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.createAccount': 'إنشاء حساب جديد',
    'auth.registerTitle': 'إنشاء حساب العائلة',
    'auth.fullName': 'الاسم الكامل',
    'auth.phone': 'الهاتف',
    'auth.register': 'إنشاء الحساب',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'family.setupTitle': 'إعداد عائلتك',
    'family.name': 'اسم العائلة',
    'family.country': 'الدولة',
    'family.numberOfChildren': 'عدد الأطفال',
    'family.continueButton': 'متابعة',
    'dashboard.title': 'الرئيسية',
    'dashboard.familySummary': 'ملخص العائلة',
    'dashboard.children_one': 'طفل واحد',
    'dashboard.children_other': '{{count}} أطفال',
    'dashboard.devices': '{{count}} أجهزة',
    'dashboard.alerts': '{{count}} تنبيهات',
    'dashboard.addChild': 'إضافة طفل',
    'dashboard.viewReports': 'عرض التقارير',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.settings': 'الإعدادات',
    'dashboard.online': 'متصل',
    'dashboard.offline': 'غير متصل',
    'pairing.addChildTitle': 'إضافة طفل',
    'pairing.noChildrenYet': 'أضف طفلًا من لوحة التحكم أولًا قبل إقران جهاز.',
    'pairing.selectChild': 'اختر الطفل',
    'pairing.generateCode': 'إنشاء رمز إقران',
    'pairing.validFor': 'صالح لمدة',
    'notifications.title': 'الإشعارات',
    'notifications.empty': 'لا يوجد إشعارات بعد.',
    'notifications.markAllRead': 'تعليم الكل كمقروء',
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.profile': 'الملف الشخصي',
    'settings.subscription': 'الاشتراك',
    'settings.privacy': 'الخصوصية',
    'settings.logout': 'تسجيل الخروج',
  },
};

/// ARABIC IS THE DEFAULT, not English (audit MA-016).
///
/// CONTEXT §1 makes Arabic the product's FIRST language for the first two
/// markets (Egypt, then Saudi Arabia) — "RTL حقيقي، لا ترجمة". Shipping
/// `AppLocale.en` here meant every child and every parent in those markets
/// opened the app in English and had to go find a language switch, which
/// is the exact opposite of the stated positioning.
///
/// This constant is also the FALLBACK used by `translate()` when a key is
/// missing from the requested locale. Both apps currently have full ar/en
/// key parity, so the flip does not change any resolved string today; if
/// parity ever breaks, an untranslated key now falls back to Arabic rather
/// than surfacing English inside an otherwise-Arabic screen.
const AppLocale defaultLocale = AppLocale.ar;
const List<AppLocale> rtlLocales = [AppLocale.ar];

bool isRtl(AppLocale locale) => rtlLocales.contains(locale);

/// Stable, persistable code for an [AppLocale]. Deliberately the plain
/// ISO-639-1 code so what is written to storage matches what
/// `Locale.languageCode` and Android's `values-<code>` resource
/// qualifiers use — one vocabulary across the whole stack.
String appLocaleCode(AppLocale locale) => switch (locale) {
      AppLocale.en => 'en',
      AppLocale.ar => 'ar',
    };

/// Inverse of [appLocaleCode]. Returns `null` for anything unsupported so
/// callers can decide their own fallback, rather than silently pretending
/// an unknown language is the default.
AppLocale? appLocaleFromCode(String? code) => switch (code) {
      'en' => AppLocale.en,
      'ar' => AppLocale.ar,
      _ => null,
    };

String _resolvePluralKey(String key, int? count, Map<String, String> resources) {
  if (count == null) return key;
  final suffix = count == 1 ? '_one' : '_other';
  final pluralKey = '$key$suffix';
  return resources.containsKey(pluralKey) ? pluralKey : key;
}

String _interpolate(String template, Map<String, Object>? options) {
  if (options == null) return template;
  var result = template;
  for (final entry in options.entries) {
    result = result.replaceAll('{{${entry.key}}}', entry.value.toString());
  }
  return result;
}

/// Same fallback strategy as the Dashboard's `translate()`: requested
/// locale -> default locale -> the raw key itself (never blank).
String translate(AppLocale locale, String key, {int? count, Map<String, Object>? options}) {
  final resources = _resources[locale] ?? _resources[defaultLocale]!;
  final resolvedKey = _resolvePluralKey(key, count, resources);

  final template = resources[resolvedKey] ?? _resources[defaultLocale]![resolvedKey] ?? key;

  final interpolationOptions = <String, Object>{if (count != null) 'count': count, ...?options};
  return _interpolate(template, interpolationOptions);
}
