/// Mirrors apps/admin-dashboard/src/shared/i18n/localizationEngine.ts's
/// design exactly: fallback strategy (requested locale -> default locale
/// -> the raw key itself), simple `_one`/`_other` pluralization,
/// interpolation via `{{token}}`. Resources are embedded as Dart const
/// maps rather than loaded from JSON assets — with no Flutter toolchain
/// available to verify `pubspec.yaml` asset bundling actually works in
/// this environment, embedding is the only path verifiable via static
/// review alone. Migrating to bundled `.arb`/JSON resources (matching
/// the Dashboard's approach exactly) is a real, trivial follow-up once
/// a real `flutter build` can confirm the asset pipeline works.
library;

enum AppLocale { en, ar }

const Map<AppLocale, Map<String, String>> _resources = {
  AppLocale.en: {
    'childRewards.completedHint': 'Every verified achievement, newest first.',
    'childRewards.completedSection': 'Completed goals',
    'childRewards.granted': '{{count}} granted',
    'childRewards.noCompleted': 'Nothing completed yet.',
    'childRewards.streakDays': '{{count}} days',
    'childRewards.streaksHint': 'Recomputed from verified achievements on every read.',
    'childRewards.streaksSection': 'Streaks',
    'evidenceKind.AUDIO': 'Voice recording',
    'evidenceKind.IMAGE': 'Picture',
    'review.evidenceHint': 'Uploaded by your child with this attempt.',
    'review.evidencePlaybackDeferred': 'Opening the file inside the app needs a media player this build does not ship yet.',
    'review.evidenceSection': 'Attached evidence',
    'streak.behaviour': 'Good behaviour',
    'streak.exercise': 'Exercise',
    'streak.learning': 'Learning',
    'streak.quran': 'Quran',
    'streak.reading': 'Reading',
    'achievementStatus.EXPIRED': 'Expired',
    'achievementStatus.IN_PROGRESS': 'In progress',
    'achievementStatus.PENDING_PARENT': 'Waiting for you',
    'achievementStatus.REJECTED': 'Sent back',
    'achievementStatus.REQUESTED': 'Requested',
    'achievementStatus.SUBMITTED': 'Submitted',
    'achievementStatus.VERIFIED': 'Verified',
    'activity.CHORE': 'Chore',
    'activity.CODE_EXERCISE': 'Coding exercise',
    'activity.GENERIC_SESSION': 'Session',
    'activity.MEMORIZE_TEXT': 'Memorise a text',
    'activity.PHYSICAL_ACTIVITY': 'Physical activity',
    'activity.PRACTICE_SESSION': 'Practice session',
    'activity.QURAN_MEMORIZE_AYAH': 'Memorise an ayah',
    'activity.QURAN_MEMORIZE_AYAH_RANGE': 'Memorise a range of ayahs',
    'activity.QURAN_MEMORIZE_JUZ': 'Memorise a juz',
    'activity.QURAN_MEMORIZE_SURAH': 'Memorise a surah',
    'activity.QURAN_RECITATION': 'Recitation',
    'activity.QURAN_REVIEW': 'Review',
    'activity.QURAN_TAFSIR': 'Tafsir',
    'activity.READ_PAGES': 'Read pages',
    'activity.SOLVE_PROBLEMS': 'Solve problems',
    'attemptResult.ESCALATED': 'Escalated to you',
    'attemptResult.FAILED': 'Not yet',
    'attemptResult.PASSED': 'Passed',
    'category.ARABIC': 'Arabic',
    'category.CREATIVITY': 'Creativity',
    'category.ENGLISH': 'English',
    'category.FIQH': 'Fiqh',
    'category.HABITS': 'Habits',
    'category.HADITH': 'Hadith',
    'category.HEALTH': 'Health',
    'category.HOUSEWORK': 'Housework',
    'category.MANNERS': 'Manners',
    'category.MATH': 'Math',
    'category.PROGRAMMING': 'Programming',
    'category.QURAN': 'Quran',
    'category.READING': 'Reading',
    'category.SCIENCE': 'Science',
    'category.SKILLS': 'Skills',
    'category.SPORT': 'Sport',
    'category.STUDY': 'Study',
    'category.VOLUNTEERING': 'Volunteering',
    'childRewards.actionFailedTitle': 'The action did not complete',
    'childRewards.activeBonus': '{{count}} min active',
    'childRewards.bonusMinutes': '{{count}} bonus minutes',
    'childRewards.earnedHint': 'Every row here came from a verified achievement.',
    'childRewards.earnedSection': 'What was achieved',
    'childRewards.emptyBody': 'After the first verified achievement, points and rewards appear here.',
    'childRewards.emptyTitle': 'Nothing earned yet',
    'childRewards.errorTitle': 'Could not load the rewards',
    'childRewards.grantActive': 'Active',
    'childRewards.grantExpired': 'Expired',
    'childRewards.grantExpiresAt': 'Ends at {{date}}',
    'childRewards.grantRevoked': 'Withdrawn',
    'childRewards.level': 'Level',
    'childRewards.noEarned': 'Nothing yet.',
    'childRewards.noGrants': 'No screen-time grants.',
    'childRewards.points': 'Points',
    'childRewards.pointsHint': 'Points are the same ledger balance as XP — one currency, not two.',
    'childRewards.pointsSection': 'Points',
    'childRewards.pointsUnavailable': 'The points balance could not be loaded right now.',
    'childRewards.revoke': 'Withdraw the grant',
    'childRewards.revokeConfirmBody': 'Only the bonus minutes are withdrawn. The reward already recorded in the ledger stays.',
    'childRewards.revokeConfirmTitle': 'Withdraw this grant?',
    'childRewards.screenTimeHint': 'Temporary grants that expire on their own and never edit the base policy.',
    'childRewards.screenTimeSection': 'Screen-time grants',
    'childRewards.title': 'Rewards & points',
    'childRewards.titleForChild': 'Rewards for {{name}}',
    'common.back': 'Back',
    'common.dismiss': 'Dismiss',
    'common.minutesValue': '{{count}} min',
    'common.no': 'No',
    'common.requestId': 'Request ID:',
    'common.yes': 'Yes',
    'difficulty.EASY': 'Easy',
    'difficulty.HARD': 'Hard',
    'difficulty.MEDIUM': 'Medium',
    'frequency.DAILY': 'Daily',
    'frequency.ONCE': 'Once',
    'frequency.WEEKLY': 'Weekly',
    'fulfilmentStatus.APPROVED': 'Approved',
    'fulfilmentStatus.DECLINED': 'Declined',
    'fulfilmentStatus.FULFILLED': 'Delivered',
    'fulfilmentStatus.PENDING': 'Pending',
    'fulfilments.action.APPROVED': 'Approve',
    'fulfilments.action.DECLINED': 'Not this time',
    'fulfilments.action.FULFILLED': 'I handed it over',
    'fulfilments.actionFailedTitle': 'The update did not complete',
    'fulfilments.emptyBody': 'Physical rewards appear here once an achievement is verified.',
    'fulfilments.emptyTitle': 'Nothing to hand over',
    'fulfilments.errorTitle': 'Could not load the hand-over list',
    'fulfilments.filterAll': 'All',
    'fulfilments.moved': 'Updated to: {{status}}',
    'fulfilments.quantity': 'Quantity {{count}}',
    'fulfilments.terminalHint': 'This one is complete — nothing left to do.',
    'fulfilments.title': 'Reward hand-over',
    'goalsHub.childGoals': 'Goals',
    'goalsHub.childRewards': 'Rewards & points',
    'goalsHub.fulfilments': 'Reward hand-over',
    'goalsHub.openGoals': 'Children goals',
    'goalsHub.reviewQueue': 'Waiting for your review',
    'goalsHub.reviewQueueWithCount': 'Waiting for your review ({{count}})',
    'goalsHub.subtitle': 'Start here: set a goal, review what your child achieved, hand over the reward.',
    'goalsHub.title': 'Goals & Rewards',
    // The five values of the backend's `SubscriptionPlanTier`. Read through
    // `LocaleController.has` — a tier this build does not know falls back to
    // `subscription.planUnknown` rather than dropping `ENTERPRISE` into the
    // middle of an Arabic sentence.
    'planTier.BASIC': 'Basic',
    'planTier.ENTERPRISE': 'Enterprise',
    'planTier.FAMILY': 'Family',
    'planTier.FREE': 'Free',
    'planTier.PREMIUM': 'Premium',
    'programDetail.actionFailedTitle': 'The action did not complete',
    'programDetail.amount': 'Amount',
    'programDetail.archive': 'Archive',
    'programDetail.archiveConfirmBody': 'Your child will no longer see it. The history and the rewards already granted are kept.',
    'programDetail.archiveConfirmTitle': 'Archive this goal?',
    'programDetail.archiveHint': 'Archiving deletes nothing — the history and granted rewards stay.',
    'programDetail.emptyTitle': 'Goal not found',
    'programDetail.errorTitle': 'Could not load the goal',
    'programDetail.multiplierValue': 'x{{value}}',
    'programDetail.pause': 'Pause',
    'programDetail.resume': 'Resume',
    'programDetail.rewardSection': 'The reward',
    'programDetail.rulesHint': 'Enforced by the server on every attempt.',
    'programDetail.rulesSection': 'The rules',
    'programDetail.streakCeiling': 'Streak multiplier ceiling',
    'programDetail.title': 'Goal details',
    'programDetail.whatSection': 'The target',
    'programStatus.ACTIVE': 'Active',
    'programStatus.ARCHIVED': 'Archived',
    'programStatus.DRAFT': 'Draft',
    'programStatus.PAUSED': 'Paused',
    'programs.create': 'New goal',
    'programs.emptyBody': 'Create the first goal: memorising a surah, reading, exercise, or anything you want to encourage.',
    'programs.emptyTitle': 'No goals yet',
    'programs.errorTitle': 'Could not load the goals',
    'programs.loading': 'Loading goals...',
    'programs.perDay': '{{count}}/day',
    'programs.title': 'Goals',
    'programs.titleForChild': 'Goals for {{name}}',
    'reasonCode.ARTIFACT_AWAITING_REVIEW': 'Proof received, awaiting review',
    'reasonCode.ARTIFACT_MISSING': 'No proof was attached',
    'reasonCode.ASSESSMENT_BELOW_THRESHOLD': 'Assessment below the threshold',
    'reasonCode.ASSESSMENT_NOT_FOUND': 'No assessment recorded for this subject yet',
    'reasonCode.ASSESSMENT_PASSED': 'Assessment threshold met',
    'reasonCode.ATTEMPTS_EXHAUSTED': 'Automatic attempts used up — escalated to you',
    'reasonCode.AWAITING_PARENT': 'Waiting for your decision',
    'reasonCode.CODE_TESTS_BELOW_THRESHOLD': 'Tests below the threshold',
    'reasonCode.CODE_TESTS_NOT_SUBMITTED': 'Test results were not submitted',
    'reasonCode.CODE_TESTS_PASSED': 'Tests passed',
    'reasonCode.DURATION_NOT_SATISFIED': 'Time not completed yet',
    'reasonCode.DURATION_SATISFIED': 'Required time completed',
    'reasonCode.FOREGROUND_EVIDENCE_MISSING': 'No foreground time was reported',
    'reasonCode.FOREGROUND_EXCEEDS_ELAPSED': 'Reported time exceeded real elapsed time',
    'reasonCode.METHOD_CANNOT_AUTO_APPROVE': 'This method never auto-approves',
    'reasonCode.PARENT_APPROVED': 'You approved it',
    'reasonCode.PARENT_REJECTED': 'You sent it back',
    'reasonCode.PROGRAM_REQUIRES_PARENT_APPROVAL': 'This goal always needs your confirmation',
    'reasonCode.QUIZ_BELOW_THRESHOLD': 'Quiz score below the threshold',
    'reasonCode.QUIZ_NOT_SUBMITTED': 'Quiz answers were not submitted',
    'reasonCode.QUIZ_PASSED': 'Quiz threshold met',
    'reasonCode.RECITATION_AWAITING_REVIEW': 'Recitation received, awaiting review',
    'reasonCode.RECITATION_MISSING': 'No recitation was attached',
    'reasonCode.SELF_CONFIRMED': 'Self-confirmed',
    'reasonCode.SELF_NOT_CONFIRMED': 'Not confirmed yet',
    'reasonCode.UNKNOWN_METHOD': 'Unknown verification method',
    'review.approve': 'Approve and credit the reward',
    'review.attemptNumber': 'Attempt {{number}}',
    'review.attemptsEmptyBody': 'This request reached you without an automatic verification attempt.',
    'review.attemptsEmptyTitle': 'No attempts recorded',
    'review.attemptsErrorTitle': 'Could not load the log',
    'review.attemptsHint': 'Append-only — every attempt, automatic or human.',
    'review.attemptsSection': 'Verification log',
    'review.byParent': 'A parent',
    'review.bySystem': 'The system',
    'review.decidedBy': 'Decided by',
    'review.decisionFailedTitle': 'The decision was not recorded',
    'review.decisionSection': 'Your decision',
    'review.intro': 'Read the verification log, then decide. Nothing is granted before you do.',
    'review.method': 'Method',
    'review.noteHint': 'Saved with the decision in the log.',
    'review.noteLabel': 'A note for your child (optional)',
    'review.reason': 'Reason',
    'review.score': 'Score',
    'review.sendBack': 'Send it back to try again',
    'review.sendBackHint': 'This does not close the goal and does not block tomorrow. No reward is credited for this attempt.',
    'review.title': 'Review an achievement',
    'reviewQueue.attemptNo': 'Attempt {{number}}',
    'reviewQueue.elapsed': '{{count}} min of work',
    'reviewQueue.emptyBody': 'When your child submits an achievement, it appears here.',
    'reviewQueue.emptyTitle': 'Nothing is waiting on you',
    'reviewQueue.errorTitle': 'Could not load the queue',
    'reviewQueue.intro': 'Nothing has been granted yet. The decision is yours.',
    'reviewQueue.loading': 'Loading the queue...',
    'reviewQueue.tapToReview': 'Tap to see the verification log, then decide.',
    'reviewQueue.title': 'Achievements awaiting your review',
    'reviewQueue.unnamedGoal': 'A goal',
    'rewardType.CUSTOM_REWARD': 'Something you choose',
    'rewardType.CUSTOM_REWARD.hint': 'Describe it yourself.',
    'rewardType.DIGITAL_REWARD': 'A digital gift',
    'rewardType.DIGITAL_REWARD.hint': 'Appears in your hand-over list; you deliver it.',
    'rewardType.PARENT_APPROVAL_REWARD': 'Parent approval',
    'rewardType.PARENT_APPROVAL_REWARD.hint': 'Something that needs your explicit yes.',
    'rewardType.PHYSICAL_REWARD': 'A real gift',
    'rewardType.PHYSICAL_REWARD.hint': 'Appears in your hand-over list; you deliver it.',
    'rewardType.POINTS': 'Points',
    'rewardType.POINTS.hint': 'Added to the ledger the moment the achievement is verified.',
    'rewardType.PRIVILEGE': 'A privilege',
    'rewardType.PRIVILEGE.hint': 'An outing, a later bedtime — you decide and you deliver.',
    'rewardType.SCREEN_TIME': 'Extra screen time',
    'rewardType.SCREEN_TIME.hint': 'Bonus minutes that expire on their own. Max 60 per grant.',
    'suggestions.accept': 'Add it as a goal',
    'suggestions.acceptFailedTitle': 'The goal was not added',
    'suggestions.accepted': 'The goal was added.',
    'suggestions.advisoryNotice': 'These are suggestions only. Nothing is created until you tap Add yourself.',
    'suggestions.emptyBody': 'Add a goal or two and the suggestions get sharper.',
    'suggestions.emptyTitle': 'No suggestions right now',
    'suggestions.errorTitle': 'Could not load the suggestions',
    'suggestions.loading': 'Preparing suggestions...',
    'suggestions.title': 'Suggestions',
    'verification.ASSESSMENT_SCORE': 'Assessment score',
    'verification.CODE_CHALLENGE': 'Code challenge',
    'verification.COMPLETION_ARTIFACT': 'Attached proof',
    'verification.DURATION': 'Real working time',
    'verification.DURATION_PLUS_QUIZ': 'Time plus a quiz',
    'verification.PARENT_CONFIRMATION': 'Parent confirmation',
    'verification.QUIZ': 'Short quiz',
    'verification.RECITATION_SUBMISSION': 'Recorded recitation',
    'verification.SELF_CHECK': 'Self check',
    'verification.strength.MODERATE': 'Medium proof',
    'verification.strength.STRONG': 'Strong proof',
    'verification.strength.WEAK': 'Light proof',
    'wizard.allChildren': 'All children',
    'wizard.allChildrenHint': 'Available to every child in the family.',
    'wizard.ayah': 'Ayah',
    'wizard.ayahRangeLabel': 'Ayah range',
    'wizard.catalogueEmptyBody': 'The server returned no categories. Try again shortly.',
    'wizard.catalogueEmptyTitle': 'No categories available',
    'wizard.catalogueErrorTitle': 'Could not load the categories',
    'wizard.childrenErrorTitle': 'Could not load your children',
    'wizard.customDuration': 'Another duration, in minutes',
    'wizard.difficulty': 'Level',
    'wizard.error.activityRequired': 'Pick an activity.',
    'wizard.error.ayahOutOfSurah': 'That ayah is outside this surah.',
    'wizard.error.ayahRangeInverted': 'The last ayah cannot come before the first.',
    'wizard.error.categoryRequired': 'Pick an area first.',
    'wizard.error.durationOutOfRange': 'The duration must be between 1 and 480 minutes.',
    'wizard.error.fromAyahRequired': 'Enter the first ayah.',
    'wizard.error.juzOutOfRange': 'The juz must be between 1 and 30.',
    'wizard.error.maxPerDayInvalid': 'The daily limit must be between 1 and 20.',
    'wizard.error.maxPerWeekInvalid': 'The weekly limit must be between 1 and 140.',
    'wizard.error.minAgeInvalid': 'The minimum age must be between 0 and 18.',
    'wizard.error.passScoreRequired': 'Set a pass score between 1 and 100.',
    'wizard.error.quantityInvalid': 'The quantity must be a positive whole number.',
    'wizard.error.rewardAmountInvalid': 'The reward must be a positive whole number.',
    'wizard.error.screenTimeAboveMax': 'A single screen-time grant cannot exceed 60 minutes.',
    'wizard.error.screenTimeTtlInvalid': 'Validity must be between 1 and 168 hours.',
    'wizard.error.surahRequired': 'Pick a surah.',
    'wizard.error.verificationRequired': 'Choose how this will be verified.',
    'wizard.error.weeklyBelowDaily': 'The weekly limit cannot be lower than the daily one.',
    'wizard.frequency': 'Frequency',
    'wizard.fromAyah': 'From ayah',
    'wizard.fulfilmentNote': 'This reward will appear in your hand-over list once the achievement is verified.',
    'wizard.hint.child': 'Pick one child, or leave it open to every child in the family.',
    'wizard.hint.reward': 'Points are credited automatically. Physical rewards land in your hand-over list.',
    'wizard.hint.rules': 'These limits are enforced by the server on every attempt, not by this app.',
    'wizard.hint.verification': 'Each method carries different weight — the explanation under each one is the real difference.',
    'wizard.isReview': 'This is a review goal',
    'wizard.isReviewHint': 'Revising what was memorised before, not new memorisation.',
    'wizard.juzNumber': 'Juz {{number}}',
    'wizard.loadingCatalogue': 'Loading categories...',
    'wizard.loadingSurahs': 'Loading the surahs...',
    'wizard.maxPerDay': 'Max per day',
    'wizard.maxPerWeek': 'Max per week',
    'wizard.minAge': 'Minimum age (optional)',
    'wizard.moreSurahs': 'and {{count}} more — use the search',
    'wizard.next': 'Next',
    'wizard.noActivitiesBody': 'Pick a different category on the previous step.',
    'wizard.noActivitiesTitle': 'No activities for this category',
    'wizard.noSurahMatch': 'No surah matches that',
    'wizard.passScore': 'Pass score (%)',
    'wizard.preview.ayahRange': 'Ayahs {{from}}-{{to}} of Surah {{name}}',
    'wizard.preview.singleAyah': 'Ayah {{ayah}} of Surah {{name}}',
    'wizard.preview.surah': 'Surah {{name}}',
    'wizard.quantity': 'Quantity',
    'wizard.reference': 'Reference (book or lesson)',
    'wizard.repetitions': 'Repetitions (optional)',
    'wizard.requiresApproval': 'Always needs my confirmation',
    'wizard.requiresApprovalHint': 'Even when automatic verification passes, no reward is granted before you say yes.',
    'wizard.review.activity': 'Activity',
    'wizard.review.category': 'Area',
    'wizard.review.child': 'For',
    'wizard.review.duration': 'Duration',
    'wizard.review.reward': 'Reward',
    'wizard.review.rules': 'Rules',
    'wizard.review.rulesValue': '{{frequency}} · {{perDay}}/day · {{perWeek}}/week',
    'wizard.review.serverNote': 'The server validates every value again before saving.',
    'wizard.review.target': 'Target',
    'wizard.review.verification': 'Verification',
    'wizard.rewardAmount': 'Reward amount',
    'wizard.rewardDescription': 'Reward description',
    'wizard.rewardMinutes': 'Bonus minutes',
    'wizard.save': 'Save the goal',
    'wizard.saveFailedTitle': 'The goal was not saved',
    'wizard.screenTimeNote': 'A screen-time grant expires on its own and never edits the base device policy.',
    'wizard.screenTimeTtl': 'Grant validity, in hours',
    'wizard.searchSurah': 'Search for a surah...',
    'wizard.selectedSurah': 'Surah {{name}}',
    'wizard.singleAyahLabel': 'Ayah number',
    'wizard.step.activity': 'What activity?',
    'wizard.step.category': 'What area?',
    'wizard.step.child': 'Who is this goal for?',
    'wizard.step.duration': 'How long?',
    'wizard.step.review': 'Review and save',
    'wizard.step.reward': 'What is the reward?',
    'wizard.step.rules': 'Repeat rules',
    'wizard.step.target': 'What exactly?',
    'wizard.step.verification': 'How do we verify it?',
    'wizard.surahAyahCount': '{{count}} ayahs',
    'wizard.surahRow': '{{number}} · {{name}}',
    'wizard.surahsEmptyTitle': 'The surah list did not arrive',
    'wizard.surahsErrorTitle': 'Could not load the surahs',
    'wizard.title': 'New goal',
    'wizard.toAyah': 'To ayah',
    'wizard.unit': 'Unit (pages, exercises, ...)',
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong.',
    'common.retry': 'Retry',
    'common.offlineBanner': 'No internet connection',
    'digitalTwin.title': 'Digital Twin',
    'digitalTwin.notARankingTool': 'A picture of your child\u2019s current progress across areas \u2014 not a score for ranking or comparing children.',
    'digitalTwin.growthScore': 'Growth Score',
    'digitalTwin.basedOnSubScores': 'Based on {{count}} of {{total}} available indicators',
    'digitalTwin.health': 'Health',
    'digitalTwin.learning': 'Learning',
    'digitalTwin.faith': 'Faith',
    'digitalTwin.habits': 'Habits',
    'digitalTwin.social': 'Social',
    'digitalTwin.behavior': 'Behavior',
    'digitalTwin.safety': 'Safety',
    'digitalTwin.notYetAvailable': 'Not yet available',
    'lifeTimeline.title': 'Life Timeline',
    'lifeTimeline.all': 'All',
    'lifeTimeline.empty': 'No milestones yet.',
    'lifeTimeline.category.health': 'Health',
    'lifeTimeline.category.learning': 'Learning',
    'lifeTimeline.category.faith': 'Faith',
    'lifeTimeline.category.rewards': 'Rewards',
    'lifeTimeline.category.safety': 'Safety',
    'lifeTimeline.category.habits': 'Habits',
    'lifeTimeline.category.family': 'Family',
    'habitTracker.title': 'Habits',
    'habitTracker.empty': 'No habits yet.',
    'habitTracker.shared': 'Shared',
    'habitTracker.markDone': 'Mark done',
    'healthTrend.title': 'Health',
    'healthTrend.score': 'Health Score',
    'healthTrend.hydration': 'Hydration',
    'learningProgress.title': 'Learning',
    'pendingApprovals.title': 'Pending Approvals',
    'pendingApprovals.empty': 'Nothing waiting for your approval right now.',
    'pendingApprovals.approve': 'Approve',
    'pendingApprovals.reject': 'Decline',
    'learningProgress.streak': 'Learning Streak',
    'learningProgress.streakDays': '{{count}} days',
    'learningProgress.sessions': 'Study sessions (30d)',
    'learningProgress.minutes': 'Total minutes (30d)',
    'learningProgress.avgScore': 'Average score',
    'learningProgress.notYetAvailable': 'Not yet available',
    'healthTrend.activity': 'Activity',
    'healthTrend.sleep': 'Sleep',
    'healthTrend.meals': 'Meals logged',
    'healthTrend.minutes': 'min',
    'healthTrend.hours': 'hrs',
    'healthTrend.notLogged': 'Not logged',
    'healthTrend.logWater': 'Log water',
    'faithProgress.title': 'Faith',
    'faithProgress.empty': 'No practices yet.',
    'faithProgress.logToday': 'Log today',
    'familyStore.title': 'Family Store',
    'familyStore.empty': 'No rewards in the store yet.',
    'familyStore.coins': 'coins',
    'coaching.title': 'Coaching',
    'coaching.empty': 'No recommendations right now.',
    'coaching.track.parent': 'For you',
    'coaching.track.child': 'For your child',
    'coaching.track.family': 'For the family',
    'coaching.track.other': 'Suggestion',
    'lifeIntelligence.actionFailedTitle': 'The action did not complete',
    'healthTrend.millilitres': 'ml',
    // A CHILD-targeted message's `category` is a backend notification type
    // (STREAK_ACHIEVED, HYDRATION_REMINDER, ...). It was rendered raw on the
    // approval card; these are the labels that replaced it, with
    // `messageCategory.other` covering any type this build predates.
    'messageCategory.ACHIEVEMENT_REJECTED': 'Achievement sent back',
    'messageCategory.ACHIEVEMENT_VERIFIED': 'Achievement confirmed',
    'messageCategory.AI_RECOMMENDATION': 'Suggestion',
    'messageCategory.BADGE_EARNED': 'Badge',
    'messageCategory.CHILD_WELLBEING_CHECKIN': 'Checking in',
    'messageCategory.DAILY_GOAL_COMPLETED': 'Goal of the day',
    'messageCategory.EXERCISE_ENCOURAGEMENT': 'Movement',
    'messageCategory.HYDRATION_REMINDER': 'Water reminder',
    'messageCategory.LEARNING_GOAL_ACHIEVED': 'Learning goal',
    'messageCategory.LEVEL_UP': 'New level',
    'messageCategory.REWARD_GRANTED_CHILD': 'Reward',
    'messageCategory.STREAK_ACHIEVED': 'Streak',
    'messageCategory.STUDY_REMINDER': 'Study reminder',
    'messageCategory.other': 'Message',
    // The Digital Twin sub-score `inputs` map. Backend field names, shown
    // to a parent only when one of these labels exists for them.
    'digitalTwinInput.activePractices': 'Active practices',
    'digitalTwinInput.averageAssessmentScore': 'Average score',
    'digitalTwinInput.challengeParticipations': 'Challenges joined',
    'digitalTwinInput.completedHabitDays': 'Days a habit was completed',
    'digitalTwinInput.completedLogs': 'Practices logged',
    'digitalTwinInput.groupActivityCount': 'Group activities',
    'digitalTwinInput.groupBadgeCount': 'Group badges',
    'digitalTwinInput.nutritionLogsCount': 'Meals logged',
    'digitalTwinInput.overallRisk': 'Risk indicator',
    'digitalTwinInput.riskAssessmentCount': 'Safety checks run',
    'digitalTwinInput.sharedHabitCompletions': 'Shared habits completed',
    'digitalTwinInput.sleepHours': 'Sleep hours',
    'digitalTwinInput.streakDays': 'Streak days',
    'digitalTwinInput.totalHabitDays': 'Days counted',
    'digitalTwinInput.totalMinutes': 'Total minutes',
    'digitalTwinInput.totalSessions': 'Study sessions',
    'digitalTwinInput.trustChangeCount': 'Trust changes',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'auth.loginTitle': 'Parent Login',
    'auth.loginTagline': 'Follow, protect, and guide your children\u2019s digital journey',
    'wellbeing.title': 'Digital Wellbeing',
    'wellbeing.insightTitle': "Today's Insight",
    'wellbeing.noData': 'No wellbeing data yet \u2014 it will appear once the device has synced at least one day.',
    'wellbeing.notYetAvailable': 'Not yet available',
    'wellbeing.avgScreenTime': 'Average screen time',
    'wellbeing.avgPickups': 'Average pickups',
    'wellbeing.nightUsage': 'Average night usage',
    'wellbeing.blockedAttempts': 'Blocked attempts',
    'wellbeing.minutesPerDay': 'min/day',
    'wellbeing.windowNote': 'Based on {daysWithData} of the last {days} days',
    'subscription.title': 'Subscription',
    'subscription.availablePlans': 'Available Plans',
    'subscription.trialTitle': 'Free Trial Active',
    'subscription.trialBody': '{days} day(s) remaining in your trial',
    'subscription.activeTitle': 'Subscription Active',
    'subscription.activeBody': 'You are on the {plan} plan',
    // The same fact without naming the tier — used when the server sends a
    // `planTier` this build has no label for. Saying less is correct; naming
    // the raw enum is not.
    'subscription.activeBodyNoPlan': 'Your subscription is active.',
    'subscription.pastDueTitle': 'Payment Issue',
    'subscription.pastDueBody': 'Your last payment failed. Please update your payment method to keep your subscription active.',
    'subscription.inactiveTitle': 'No Active Subscription',
    'subscription.inactiveBody': 'Choose a plan below to continue using premium features.',
    'subscription.noneTitle': 'Get Started',
    'subscription.noneBody': 'Choose a plan to begin.',
    // PHASE D's three statuses. Each is a different fact and none of them is
    // "you have no subscription", which is what all three used to render as.
    'subscription.pendingTitle': 'Payment Pending',
    'subscription.pendingBody':
        'We have your order and the payment has not reached us yet. Your subscription starts as soon as it is confirmed.',
    // Entitlement-bearing: `entitlement.service.ts` grants full access in this
    // state. The notice says so, and asks for the one action that fixes it.
    // The length of the window is server-configured and deliberately not
    // stated here as a number.
    'subscription.graceTitle': 'Your Access Continues',
    'subscription.graceBody':
        'Your last payment did not go through. You keep full access for a short grace period — update your payment method to continue without interruption.',
    'subscription.refundedTitle': 'Payment Refunded',
    'subscription.refundedBody':
        'Your subscription payment was returned and access to the premium features has ended. You can subscribe again whenever you want.',
    'subscription.free': 'Free',
    'subscription.currentPlan': 'Current Plan',
    'subscription.choosePlan': 'Choose Plan',
    'subscription.cancel': 'Cancel Subscription',
    'subscription.viewHistory': 'View Billing History',
    // PHASE G — four DIFFERENT facts, four different sentences. Previously the
    // purchase button always succeeded (it called the MANUAL adapter), so none of
    // these states could occur and none of these strings existed.
    'subscription.purchaseMarketUnknown':
        'We cannot tell which country this account is billed in yet, so we will not guess a price. Please contact support and we will set it up.',
    'subscription.purchaseNotConfigured':
        'This plan is not on sale yet. Pricing has not been published for your country. Nothing has been charged.',
    'subscription.purchaseStoreUnavailable':
        'This plan is sold through the app store, and this version of the app cannot open the store checkout. Please update the app and try again. Nothing has been charged.',
    'subscription.purchaseFailed':
        'The purchase did not complete. Nothing has been charged. Please try again, or contact support if it keeps happening.',
    'billingHistory.title': 'Billing History',
    'billingHistory.empty': 'No invoices yet.',
    'support.title': 'Help & Support',
    'support.faqTitle': 'Frequently Asked Questions',
    'support.faq.q1': 'How do I pair my child\u2019s device?',
    'support.faq.a1': 'Go to Settings > Add Child on this app, generate a pairing code, then enter that code in the Child App on your child\u2019s device within the time shown.',
    'support.faq.q2': 'Why does my child\u2019s status show as offline?',
    'support.faq.a2': 'This usually means the device hasn\u2019t sent a heartbeat recently \u2014 check that the Child App has Battery Optimization disabled and Accessibility Service still enabled on their device.',
    'support.faq.q3': 'How do screen time limits work?',
    'support.faq.a3': 'Limits you set are synced to the device and enforced even without an internet connection, using the last successfully synced policy.',
    'support.faq.q4': 'Can I change my subscription plan?',
    'support.faq.a4': 'Yes \u2014 go to Settings > Subscription to see available plans and switch at any time.',
    'support.faq.q5': 'Is my child\u2019s data private?',
    'support.faq.a5': 'We collect only aggregated usage summaries, never raw message content, photos, or keystrokes. See our Privacy Policy for full details.',
    'support.stillNeedHelp': 'Still need help?',
    'support.contactBody': 'Send us a message and we\u2019ll get back to you by email.',
    'support.contactButton': 'Contact Us',
    'support.contactTitle': 'Contact Support',
    'support.email': 'Your Email',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.send': 'Send Message',
    'support.sentTitle': 'Message Sent!',
    'support.sentBody': 'We\u2019ve received your message and will reply by email soon.',
    // The chrome line above the server's own sentence. It states the OUTCOME
    // \u2014 the message is not on its way \u2014 because the previous version of this
    // screen showed only raw exception text, from which a parent could not
    // tell whether their request had been filed or not.
    'support.sendFailedTitle': 'Your message was not sent',
    'dashboard.pairDevice': 'Pair a Device',
    'createChild.title': 'Add a Child',
    'createChild.firstName': 'First Name',
    'createChild.lastNameOptional': 'Last Name (optional)',
    'createChild.dateOfBirth': 'Date of Birth',
    'createChild.selectDate': 'Select a date',
    'createChild.consentTitle': 'Before you continue',
    'createChild.consentBody': 'By adding this child, you agree to basic data collection, location tracking, app usage monitoring, and AI behavior analysis for their protection. You can review and change any of these anytime in Settings > Manage Consents.',
    'createChild.submit': 'Add Child',
    // This form's own precondition, not the server's — no request is sent
    // without a date, so there is no `messageAr` to render. It replaced a
    // hardcoded English literal on an Arabic-first screen.
    'createChild.dateOfBirthRequired': 'Please select a date of birth.',
    'createChild.saveFailedTitle': 'The child profile was not created',
    'createChild.unnamedChild': 'Child',
    'consents.title': 'Manage Consents',
    'consents.loadFailedTitle': 'We could not load the consent settings',
    'consents.selectChild': 'Select Child',
    'consents.noChildren': 'Add a child first to manage their consent settings.',
    'consents.explanation': 'Control exactly what data is collected for each child. You can turn any of these off at any time \u2014 some features may stop working if you do.',
    'consents.type.DATA_COLLECTION.title': 'Basic Data Collection',
    'consents.type.DATA_COLLECTION.description': 'Core account and usage data needed for the app to function.',
    'consents.type.LOCATION_TRACKING.title': 'Location Tracking',
    'consents.type.LOCATION_TRACKING.description': 'Track your child\u2019s device location.',
    'consents.type.APP_USAGE_MONITORING.title': 'App Usage Monitoring',
    'consents.type.APP_USAGE_MONITORING.description': 'Collect aggregated app usage summaries \u2014 never raw content.',
    'consents.type.AI_BEHAVIOR_ANALYSIS.title': 'AI Behavior Analysis',
    'consents.type.AI_BEHAVIOR_ANALYSIS.description': 'Let AI analyze behavioral patterns to provide insights and coaching.',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.title': 'Keyboard Behavior Analysis',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.description': 'Not yet available \u2014 reserved for a future safety feature under separate review.',
    'consents.type.HEALTH_DATA.title': 'Health Data',
    'consents.type.HEALTH_DATA.description': 'Collect health-related data like hydration and activity logs.',
    'deleteAccount.title': 'Delete Account',
    'deleteAccount.warningTitle': 'This cannot be undone',
    'deleteAccount.warningBody': 'Deleting your account will remove access for every child profile, cancel your subscription, and sign you out of all devices. Your data will be anonymized immediately.',
    'deleteAccount.confirmCheckbox': 'I understand this action is permanent',
    'deleteAccount.currentPassword': 'Enter your current password to confirm',
    'deleteAccount.submit': 'Permanently Delete My Account',
    // TWO TITLES, BECAUSE THE TWO OUTCOMES ARE NOT THE SAME FACT.
    // The server refused (a 4xx that came back through the B3 filter) —
    // nothing was deleted, and saying so plainly is correct. Anything else
    // (offline, a timeout, a 5xx) means the app never got an answer, and
    // claiming the account is intact would be a guess stated as a fact on
    // the one screen where that is least acceptable. The server's own
    // sentence renders under either title and explains why.
    'deleteAccount.errorRefusedTitle': 'Your account was not deleted',
    'deleteAccount.errorUnconfirmedTitle': 'We did not get a confirmation',
    'auth.acceptTerms': 'I agree to the Terms of Service and Privacy Policy',
    // This form's own precondition, not the server's — no request is sent
    // until the box is ticked, so there is no `messageAr` to render and this
    // sentence is the app's to write. It replaced a hardcoded English literal.
    'auth.acceptTermsRequired':
        'Please agree to the Terms of Service and Privacy Policy to continue.',

    'invoiceStatus.PAID': 'Paid',
    'invoiceStatus.OPEN': 'Due',
    'invoiceStatus.DRAFT': 'Not issued yet',
    'invoiceStatus.VOID': 'Cancelled',
    'invoiceStatus.UNCOLLECTIBLE': 'Could not be collected',
    'invoiceStatus.unknown': 'Being processed',

    'redeemCode.entryPoint': 'Have a Partner Code?',
    'redeemCode.title': 'Redeem a Code',
    'redeemCode.explanation': 'Enter a code from a partner (like your employer, bank, or telecom provider) to unlock a benefit for your account.',
    'redeemCode.codeLabel': 'Enter Code',
    'redeemCode.submit': 'Redeem Code',
    // A code can be redeemed ONCE, so the two failures mean opposite things
    // to whoever is holding it. `rejectedTitle` is the server's verdict on
    // the code itself — go find a different one. `notAppliedTitle` covers
    // every case where the server never decided (offline, timeout, 5xx) and
    // the throttle case, where the code is very likely fine and the parent
    // was simply too quick; it says explicitly that nothing was used up, so
    // trying the SAME code again is the right next move.
    'redeemCode.rejectedTitle': 'This code was not accepted',
    'redeemCode.notAppliedTitle': 'The code has not been used — try again shortly',
    // Only when the server applied a benefit and described nothing. Its own
    // sentence carries the real numbers ("extended by 14 day(s)") and wins
    // whenever it is present; this replaced a hardcoded English 'Success!'.
    'redeemCode.successFallback': 'Your code has been applied.',
    'dashboard.notificationsTooltip': 'Notifications',
    'dashboard.settingsTooltip': 'Settings',
    'common.done': 'Done',
    'dashboard.firstChildTitle': 'Welcome! Let\u2019s add your first child',
    'dashboard.firstChildBody': 'Add a child profile, then pair their device to start protecting and guiding their digital journey.',
    'dashboard.addFirstChild': 'Add Your First Child',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login': 'Log In',
    'auth.noAccount': "Don't have an account?",
    'auth.createAccount': 'Create a new account',
    'auth.registerTitle': 'Create Your Family Account',
    'auth.fullName': 'Full Name',
    'auth.phone': 'Phone',
    'auth.register': 'Create Account',
    'auth.haveAccount': 'Already have an account?',
    'family.setupTitle': 'Set Up Your Family',
    'family.name': 'Family Name',
    'family.country': 'Country',
    // The country is not stored on its own anywhere — it chooses the
    // family's TIMEZONE, which is stored and which every business-day
    // boundary is computed from. `family.numberOfChildren` was removed
    // together with the slider it labelled: no backend field accepted it.
    'family.country.EG': 'Egypt',
    'family.country.SA': 'Saudi Arabia',
    'family.timezoneExplainer':
        'Your family’s day will start and end on {{country}} local time — streaks, daily limits and rewards all follow it.',
    'family.continueButton': 'Continue',
    'dashboard.title': 'Home',
    // PHASE E (§6). The parent home has to answer two questions on one
    // screen. These are the words it answers them with.
    'dashboard.needsYouTitle': 'Anything that needs you?',
    'dashboard.needsYouNothing': 'Nothing is waiting for you right now.',
    'dashboard.needsYouReviews': '{{count}} achievements waiting for your review',
    'dashboard.needsYouReviews_one': 'One achievement is waiting for your review',
    'dashboard.needsYouReviews_other': '{{count}} achievements waiting for your review',
    'dashboard.needsYouMessages': '{{count}} messages waiting for your approval',
    'dashboard.needsYouMessages_one': 'One message is waiting for your approval',
    'dashboard.needsYouMessages_other': '{{count}} messages waiting for your approval',
    'dashboard.childStatusTitle': 'Is your child OK today?',
    // The backend's risk enum, phrased as an ANSWER rather than as a
    // severity code. `_RiskChip` used to print the enum itself.
    'riskLevel.LOW': 'All good',
    'riskLevel.MEDIUM': 'Worth a look',
    'riskLevel.HIGH': 'Needs you today',
    'riskLevel.CRITICAL': 'Needs you now',
    'riskLevel.UNKNOWN': 'No data today',
    'dashboard.familySummary': 'Family Summary',
    'dashboard.children': '{{count}} children',
    'dashboard.children_one': '{{count}} child',
    'dashboard.children_other': '{{count}} children',
    'dashboard.devices': '{{count}} devices',
    'dashboard.alerts': '{{count}} alerts',
    'dashboard.addChild': 'Add Child',
    'dashboard.viewReports': 'View Reports',
    'dashboard.notifications': 'Notifications',
    'dashboard.settings': 'Settings',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'pairing.addChildTitle': 'Add a Child',
    'pairing.noChildrenYet': 'Add a child from your Dashboard first before pairing a device.',
    'pairing.selectChild': 'Select Child',
    'pairing.generateCode': 'Generate Pairing Code',
    'pairing.validFor': 'Valid for',
    // The screen used to end at the code. These are the sentences that
    // answer "did it work?" — the question it exists to answer.
    'pairing.waitingTitle': 'Waiting for your child’s device',
    'pairing.waitingBody':
        'Keep this screen open. As soon as the code is entered on your child’s phone, you will see it here.',
    'pairing.connectedTitle': 'Your child’s device is connected',
    'pairing.connectedActiveBody': 'The device is linked to your family and is active.',
    'pairing.connectedPendingBody':
        'The device is linked to your family. It will appear in your device list, where you can follow its status.',
    'pairing.notYetTitle': 'No device has connected yet',
    'pairing.notYetBody':
        'The code is valid for {{minutes}} minutes, and this one has run out. Nothing went wrong — generate a new code whenever you are ready with your child’s phone.',
    'pairing.cannotConfirmTitle': 'The code is ready',
    'pairing.cannotConfirmBody':
        'We could not read your device list just now, so this screen cannot confirm the pairing on its own. The code still works — check your device list afterwards.',
    'pairing.revokeAction': 'Unlink this device',
    'pairing.revokeHint': 'Use this if the code was entered on the wrong phone.',
    'pairing.revokeConfirmTitle': 'Unlink this device?',
    'pairing.revokeConfirmBody':
        'The device will lose access to your family straight away. You can pair it again later with a new code.',
    'pairing.revokedTitle': 'The device was unlinked',
    'pairing.revokedBody': 'It no longer has access to your family. Generate a new code to pair a device again.',
    'pairing.activateAction': 'Confirm and activate the device',
    'pairing.activateHint':
        'This is the last step: once the device is activated, your family plan starts applying on it.',
    'pairing.activatePreparingBody':
        'The device is still finishing its own setup, so there is nothing to confirm yet. It only takes a moment.',
    'pairing.checkAgainAction': 'Check again',
    'pairing.activationNoticeTitle': 'The server’s reply',
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications yet.',
    'notifications.markAllRead': 'Mark all as read',

    // ------------------------------------------------------------------
    // G18 — POST_NOTIFICATIONS priming, shown INSIDE this screen.
    //
    // The permission used to be requested during cold start from
    // SplashScreen, before the parent had seen a single notification. It is
    // asked for here now, where the parent is looking at the exact messages
    // the permission governs — so the explanation is one sentence about
    // something already on screen, not a sales pitch.
    // ------------------------------------------------------------------
    'notifications.permTitle': 'These are not reaching your phone',
    'notifications.permBody':
        'You can read them here, but Android will not show them on your phone until you allow notifications. Nothing else about the app changes.',
    'notifications.permEnable': 'Allow notifications',
    'notifications.permGranted': 'Done — these will reach your phone from now on.',
    'notifications.permDenied':
        'Not allowed. You can still read everything here. To change it later, turn notifications on for ABNY in your phone settings.',

    // The one line `DeepLinkRouter` renders when a notification's destination
    // has no screen this app can open. It is the whole of "visibly and
    // honestly": the tap is never swallowed, and the sentence says exactly
    // where the parent ended up rather than pretending nothing was tapped.
    'deepLink.unavailable':
        'This part of the app is not ready yet — we have kept you in your notifications.',

    // -----------------------------------------------------------------------
    // THE SAFETY SURFACE. Every line here is APP CHROME — the label of a kind
    // of event, the band, and what a parent can do about it. The sentence that
    // says WHAT HAPPENED is the server's (`title`/`body`), rendered verbatim
    // and never through this map.
    //
    // TONE, AND IT IS A REQUIREMENT RATHER THAN A PREFERENCE: calm, specific,
    // and never alarming for its own sake. Each guidance line answers «what can
    // I do», because an alert a parent cannot act on is only anxiety. The
    // wellbeing line additionally states the privacy guarantee out loud, since
    // the server deliberately sends a GENERIC alert on that path and a parent
    // may otherwise assume the app is withholding something.
    // -----------------------------------------------------------------------
    'safety.title': 'Safety & protection',
    'safety.introTitle': 'Protection alerts for your family',
    'safety.introBody':
        'Protection and screen-time alerts, newest first, exactly as they reached you. What your child writes is never shown here.',
    'safety.emptyTitle': 'No alerts',
    'safety.emptyBody':
        'Nothing about protection or screen time has come through. That is the normal state.',
    'safety.errorTitle': 'The alerts could not be shown',
    'safety.notInRecentTitle': 'We could not find that alert',
    'safety.notInRecent':
        'That alert is no longer among the most recent ones. The list below is the latest that reached you.',
    'safety.genericType': 'Protection alert',
    'safety.genericGuidance': 'Check the device at the next convenient moment.',
    'safety.new': 'New',
    'safety.openChild': 'Open the child page',
    'safety.openChildNamed': 'Open the page for {{name}}',
    'safety.whenToday': 'Today {{time}}',
    'safety.whenYesterday': 'Yesterday {{time}}',
    'safety.whenOn': '{{date}} — {{time}}',

    'safetyBand.needsAttention': 'Needs your attention',
    'safetyBand.worthReviewing': 'Worth reviewing',
    'safetyBand.forInformation': 'For your information',

    'safetyType.ACCESSIBILITY_DISABLED': 'Protection is off on the device',
    'safetyType.PROTECTION_BYPASS_ATTEMPT': 'An attempt to turn protection off',
    'safetyType.CHILD_WELLBEING_CHECKIN': 'Check in with your child',
    'safetyType.POLICY_VIOLATION': 'Something to review in the settings',
    'safetyType.SCREEN_TIME_EXCEEDED': 'The screen-time allowance ended',
    'safetyType.RUNTIME_ALERT': 'An alert from the device',

    'safetyGuidance.ACCESSIBILITY_DISABLED':
        'While this service is off, no screen-time limit and no blocking rule is applied. Open the Accessibility settings on the device and turn it back on.',
    'safetyGuidance.PROTECTION_BYPASS_ATTEMPT':
        'An attempt to turn protection off was recorded. Check the device, then make it a calm conversation with your child before changing any setting.',
    'safetyGuidance.CHILD_WELLBEING_CHECKIN':
        'What your child wrote was not stored and is not shown to you — only this general alert was sent. The best next step is a quiet moment and a simple question: how was your day?',
    'safetyGuidance.POLICY_VIOLATION':
        'Nothing needs doing right now. Review the settings for this device when it suits you.',
    'safetyGuidance.SCREEN_TIME_EXCEEDED':
        'The limit was applied on the device automatically. You can review and adjust the time from the child page.',
    'safetyGuidance.RUNTIME_ALERT':
        'The device recorded this alert. Check the device status at the next convenient moment.',

    // -----------------------------------------------------------------------
    // ONE CHILD — the screen `abny://child/<id>` opens, and the host for the
    // three child-scoped screens no link can ever name a child for.
    // -----------------------------------------------------------------------
    'childDetail.title': 'Child page',
    'childDetail.unnamed': 'Your child',
    'childDetail.age': '{{count}} years old',
    'childDetail.age_one': '1 year old',
    'childDetail.age_other': '{{count}} years old',
    'childDetail.inactive': 'Profile not active',
    'childDetail.sectionTitle': 'What would you like to see?',
    'childDetail.sectionSubtitle': 'Three screens about this child alone.',
    'childDetail.progressHint': 'What they are learning and what they have finished.',
    'childDetail.coachHint': 'Practical suggestions for you and for them.',
    'childDetail.screenTimeHint': 'Screen time and digital habits.',
    'childDetail.footnote':
        'Everything here comes from the device and the server. Nothing on this page is decided inside the app.',
    'childDetail.errorTitle': 'The child page could not be opened',
    'childDetail.missingTitle': 'We could not find this child',
    'childDetail.missingBody':
        'The profile may have been removed, or the link points to a child outside your family. Open the dashboard to choose a child.',

    'dashboard.openSafety': 'Safety & protection',
    'childActions.childPage': 'Child page',

    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.profile': 'Profile',
    'settings.subscription': 'Subscription',
    'settings.privacy': 'Privacy',
    'settings.logout': 'Log Out',
  },
  AppLocale.ar: {
    'childRewards.completedHint': 'كل إنجاز متحقّق، الأحدث أولًا.',
    'childRewards.completedSection': 'الأهداف المكتملة',
    'childRewards.granted': 'مُنِح {{count}}',
    'childRewards.noCompleted': 'لم يكتمل شيء بعد.',
    'childRewards.streakDays': '{{count}} يوم',
    'childRewards.streaksHint': 'يُعاد حسابه من الإنجازات المتحقّقة عند كل قراءة.',
    'childRewards.streaksSection': 'التتابع',
    'evidenceKind.AUDIO': 'تسجيل صوتي',
    'evidenceKind.IMAGE': 'صورة',
    'review.evidenceHint': 'رفعه طفلك مع هذه المحاولة.',
    'review.evidencePlaybackDeferred': 'فتح الملف داخل التطبيق يحتاج مشغّل وسائط غير متضمَّن في هذه النسخة بعد.',
    'review.evidenceSection': 'الدليل المرفق',
    'streak.behaviour': 'السلوك',
    'streak.exercise': 'الرياضة',
    'streak.learning': 'التعلّم',
    'streak.quran': 'القرآن',
    'streak.reading': 'القراءة',
    'achievementStatus.EXPIRED': 'انتهت صلاحيته',
    'achievementStatus.IN_PROGRESS': 'قيد العمل',
    'achievementStatus.PENDING_PARENT': 'بانتظار قرارك',
    'achievementStatus.REJECTED': 'أُعيد للمحاولة',
    'achievementStatus.REQUESTED': 'مطلوب',
    'achievementStatus.SUBMITTED': 'أُرسل للتحقّق',
    'achievementStatus.VERIFIED': 'متحقَّق',
    'activity.CHORE': 'مهمة منزلية',
    'activity.CODE_EXERCISE': 'تمرين برمجي',
    'activity.GENERIC_SESSION': 'جلسة',
    'activity.MEMORIZE_TEXT': 'حفظ نص',
    'activity.PHYSICAL_ACTIVITY': 'نشاط بدني',
    'activity.PRACTICE_SESSION': 'جلسة تدريب',
    'activity.QURAN_MEMORIZE_AYAH': 'حفظ آية',
    'activity.QURAN_MEMORIZE_AYAH_RANGE': 'حفظ مجموعة آيات',
    'activity.QURAN_MEMORIZE_JUZ': 'حفظ جزء',
    'activity.QURAN_MEMORIZE_SURAH': 'حفظ سورة',
    'activity.QURAN_RECITATION': 'تلاوة',
    'activity.QURAN_REVIEW': 'مراجعة',
    'activity.QURAN_TAFSIR': 'تفسير',
    'activity.READ_PAGES': 'قراءة صفحات',
    'activity.SOLVE_PROBLEMS': 'حل مسائل',
    'attemptResult.ESCALATED': 'أُحيل إليك',
    'attemptResult.FAILED': 'لم يكتمل',
    'attemptResult.PASSED': 'اجتاز',
    'category.ARABIC': 'عربي',
    'category.CREATIVITY': 'إبداع',
    'category.ENGLISH': 'إنجليزي',
    'category.FIQH': 'فقه',
    'category.HABITS': 'عادات',
    'category.HADITH': 'حديث',
    'category.HEALTH': 'صحة',
    'category.HOUSEWORK': 'أعمال منزلية',
    'category.MANNERS': 'أدب وسلوك',
    'category.MATH': 'رياضيات',
    'category.PROGRAMMING': 'برمجة',
    'category.QURAN': 'قرآن',
    'category.READING': 'قراءة',
    'category.SCIENCE': 'علوم',
    'category.SKILLS': 'مهارات',
    'category.SPORT': 'رياضة',
    'category.STUDY': 'دراسة',
    'category.VOLUNTEERING': 'تطوع',
    'childRewards.actionFailedTitle': 'لم يكتمل الإجراء',
    'childRewards.activeBonus': '{{count}} دقيقة فعّالة',
    'childRewards.bonusMinutes': '{{count}} دقيقة إضافية',
    'childRewards.earnedHint': 'كل صف هنا ناتج عن إنجاز متحقّق.',
    'childRewards.earnedSection': 'ما تحقّق',
    'childRewards.emptyBody': 'بعد أول إنجاز متحقّق، ستظهر النقاط والمكافآت هنا.',
    'childRewards.emptyTitle': 'لا توجد مكافآت بعد',
    'childRewards.errorTitle': 'تعذّر تحميل المكافآت',
    'childRewards.grantActive': 'فعّالة',
    'childRewards.grantExpired': 'منتهية',
    'childRewards.grantExpiresAt': 'تنتهي في {{date}}',
    'childRewards.grantRevoked': 'مسحوبة',
    'childRewards.level': 'المستوى',
    'childRewards.noEarned': 'لا شيء بعد.',
    'childRewards.noGrants': 'لا توجد منح وقت شاشة.',
    'childRewards.points': 'النقاط',
    'childRewards.pointsHint': 'النقاط هي نفسها رصيد الـ XP في السجل — عملة واحدة لا اثنتان.',
    'childRewards.pointsSection': 'النقاط',
    'childRewards.pointsUnavailable': 'تعذّر تحميل رصيد النقاط الآن.',
    'childRewards.revoke': 'سحب المنحة',
    'childRewards.revokeConfirmBody': 'تُسحب الدقائق الإضافية فقط. والمكافأة المُحتسَبة في السجل تبقى كما هي.',
    'childRewards.revokeConfirmTitle': 'سحب هذه المنحة؟',
    'childRewards.screenTimeHint': 'منح مؤقتة تنتهي تلقائيًا، ولا تعدّل السياسة الأساسية.',
    'childRewards.screenTimeSection': 'منح وقت الشاشة',
    'childRewards.title': 'المكافآت والنقاط',
    'childRewards.titleForChild': 'مكافآت {{name}}',
    'common.back': 'رجوع',
    'common.dismiss': 'إغلاق',
    'common.minutesValue': '{{count}} دقيقة',
    'common.no': 'لا',
    'common.requestId': 'رقم الطلب:',
    'common.yes': 'نعم',
    'difficulty.EASY': 'سهل',
    'difficulty.HARD': 'صعب',
    'difficulty.MEDIUM': 'متوسط',
    'frequency.DAILY': 'يومي',
    'frequency.ONCE': 'مرة واحدة',
    'frequency.WEEKLY': 'أسبوعي',
    'fulfilmentStatus.APPROVED': 'معتمد',
    'fulfilmentStatus.DECLINED': 'اعتُذر عنه',
    'fulfilmentStatus.FULFILLED': 'تم التسليم',
    'fulfilmentStatus.PENDING': 'بانتظار الاعتماد',
    'fulfilments.action.APPROVED': 'اعتمد',
    'fulfilments.action.DECLINED': 'ليس هذه المرة',
    'fulfilments.action.FULFILLED': 'سلّمتُها',
    'fulfilments.actionFailedTitle': 'لم يكتمل التحديث',
    'fulfilments.emptyBody': 'تظهر المكافآت الملموسة هنا بعد تحقّق الإنجاز.',
    'fulfilments.emptyTitle': 'لا توجد مكافآت للتسليم',
    'fulfilments.errorTitle': 'تعذّر تحميل قائمة التسليم',
    'fulfilments.filterAll': 'الكل',
    'fulfilments.moved': 'تم التحديث إلى: {{status}}',
    'fulfilments.quantity': 'العدد {{count}}',
    'fulfilments.terminalHint': 'اكتملت هذه المكافأة — لا إجراء متبقٍ.',
    'fulfilments.title': 'تسليم المكافآت',
    'goalsHub.childGoals': 'الأهداف',
    'goalsHub.childRewards': 'المكافآت والنقاط',
    'goalsHub.fulfilments': 'تسليم المكافآت',
    'goalsHub.openGoals': 'أهداف الأبناء',
    'goalsHub.reviewQueue': 'بانتظار مراجعتك',
    'goalsHub.reviewQueueWithCount': 'بانتظار مراجعتك ({{count}})',
    'goalsHub.subtitle': 'ابدأ من هنا: اصنع هدفًا، راجع ما أنجزه طفلك، ثم سلّم المكافأة.',
    'goalsHub.title': 'الأهداف والمكافآت',
    'planTier.BASIC': 'الأساسية',
    'planTier.ENTERPRISE': 'المؤسسات',
    'planTier.FAMILY': 'العائلية',
    'planTier.FREE': 'المجانية',
    'planTier.PREMIUM': 'المميّزة',
    'programDetail.actionFailedTitle': 'لم يكتمل الإجراء',
    'programDetail.amount': 'القيمة',
    'programDetail.archive': 'أرشفة',
    'programDetail.archiveConfirmBody': 'لن يظهر لطفلك بعد الآن، ويبقى السجل والمكافآت الممنوحة كما هي.',
    'programDetail.archiveConfirmTitle': 'أرشفة هذا الهدف؟',
    'programDetail.archiveHint': 'الأرشفة لا تحذف شيئًا — السجل والمكافآت الممنوحة تبقى كما هي.',
    'programDetail.emptyTitle': 'لم يُعثر على الهدف',
    'programDetail.errorTitle': 'تعذّر تحميل الهدف',
    'programDetail.multiplierValue': '×{{value}}',
    'programDetail.pause': 'إيقاف مؤقت',
    'programDetail.resume': 'استئناف',
    'programDetail.rewardSection': 'المكافأة',
    'programDetail.rulesHint': 'يفرضها الخادم عند كل محاولة.',
    'programDetail.rulesSection': 'القواعد',
    'programDetail.streakCeiling': 'سقف مضاعف التتابع',
    'programDetail.title': 'تفاصيل الهدف',
    'programDetail.whatSection': 'المطلوب',
    'programStatus.ACTIVE': 'نشط',
    'programStatus.ARCHIVED': 'مؤرشف',
    'programStatus.DRAFT': 'مسودة',
    'programStatus.PAUSED': 'موقوف مؤقتًا',
    'programs.create': 'هدف جديد',
    'programs.emptyBody': 'أنشئ أول هدف: حفظ سورة، قراءة، رياضة، أو أي شيء تريد تشجيعه عليه.',
    'programs.emptyTitle': 'لا توجد أهداف بعد',
    'programs.errorTitle': 'تعذّر تحميل الأهداف',
    'programs.loading': 'جارٍ تحميل الأهداف…',
    'programs.perDay': '{{count}} مرة يوميًا',
    'programs.title': 'الأهداف',
    'programs.titleForChild': 'أهداف {{name}}',
    'reasonCode.ARTIFACT_AWAITING_REVIEW': 'وصل الدليل وينتظر المراجعة',
    'reasonCode.ARTIFACT_MISSING': 'لم يُرفَق دليل الإنجاز',
    'reasonCode.ASSESSMENT_BELOW_THRESHOLD': 'نتيجة التقييم دون العتبة',
    'reasonCode.ASSESSMENT_NOT_FOUND': 'لا يوجد تقييم مسجَّل لهذه المادة',
    'reasonCode.ASSESSMENT_PASSED': 'اجتاز عتبة التقييم',
    'reasonCode.ATTEMPTS_EXHAUSTED': 'انتهت المحاولات الآلية — أُحيل إليك',
    'reasonCode.AWAITING_PARENT': 'بانتظار قرارك',
    'reasonCode.CODE_TESTS_BELOW_THRESHOLD': 'نتيجة الاختبارات دون العتبة',
    'reasonCode.CODE_TESTS_NOT_SUBMITTED': 'لم تُرسَل نتيجة الاختبارات',
    'reasonCode.CODE_TESTS_PASSED': 'نجحت الاختبارات',
    'reasonCode.DURATION_NOT_SATISFIED': 'لم تكتمل المدة بعد',
    'reasonCode.DURATION_SATISFIED': 'اكتملت المدة المطلوبة',
    'reasonCode.FOREGROUND_EVIDENCE_MISSING': 'لم يصل قياس زمن الاستخدام',
    'reasonCode.FOREGROUND_EXCEEDS_ELAPSED': 'الزمن المُبلَّغ تجاوز الزمن الفعلي',
    'reasonCode.METHOD_CANNOT_AUTO_APPROVE': 'هذه الطريقة لا تُقرّ آليًا',
    'reasonCode.PARENT_APPROVED': 'وافقتَ عليه',
    'reasonCode.PARENT_REJECTED': 'أعدتَه للمحاولة',
    'reasonCode.PROGRAM_REQUIRES_PARENT_APPROVAL': 'هذا الهدف يتطلب تأكيدك دائمًا',
    'reasonCode.QUIZ_BELOW_THRESHOLD': 'النتيجة دون العتبة',
    'reasonCode.QUIZ_NOT_SUBMITTED': 'لم تُرسَل إجابات الاختبار',
    'reasonCode.QUIZ_PASSED': 'اجتاز عتبة الاختبار',
    'reasonCode.RECITATION_AWAITING_REVIEW': 'وصل التسميع وينتظر المراجعة',
    'reasonCode.RECITATION_MISSING': 'لم يُرفَق تسجيل التسميع',
    'reasonCode.SELF_CONFIRMED': 'تأكيد ذاتي',
    'reasonCode.SELF_NOT_CONFIRMED': 'لم يُؤكَّد بعد',
    'reasonCode.UNKNOWN_METHOD': 'طريقة تحقّق غير معروفة',
    'review.approve': 'وافق واحتسب المكافأة',
    'review.attemptNumber': 'المحاولة {{number}}',
    'review.attemptsEmptyBody': 'وصل هذا الطلب إليك دون محاولة تحقّق آلية.',
    'review.attemptsEmptyTitle': 'لا توجد محاولات مسجّلة',
    'review.attemptsErrorTitle': 'تعذّر تحميل سجل المحاولات',
    'review.attemptsHint': 'سجل غير قابل للتعديل — كل محاولة، آلية كانت أم بشرية.',
    'review.attemptsSection': 'سجل التحقّق',
    'review.byParent': 'ولي الأمر',
    'review.bySystem': 'النظام',
    'review.decidedBy': 'مَن قرّر',
    'review.decisionFailedTitle': 'لم يُسجَّل القرار',
    'review.decisionSection': 'قرارك',
    'review.intro': 'اطّلع على سجل التحقّق ثم قرّر. لا يُمنح شيء قبل قرارك.',
    'review.method': 'الطريقة',
    'review.noteHint': 'تُحفَظ مع القرار في السجل.',
    'review.noteLabel': 'ملاحظة لطفلك (اختيارية)',
    'review.reason': 'السبب',
    'review.score': 'النتيجة',
    'review.sendBack': 'أعِده للمحاولة',
    'review.sendBackHint': 'هذا لا يُغلق الهدف ولا يمنع محاولة الغد. ولا تُحتسب مكافأة لهذه المحاولة.',
    'review.title': 'مراجعة إنجاز',
    'reviewQueue.attemptNo': 'المحاولة {{number}}',
    'reviewQueue.elapsed': '{{count}} دقيقة عمل',
    'reviewQueue.emptyBody': 'عندما يُرسل طفلك إنجازًا للتحقّق، سيظهر هنا.',
    'reviewQueue.emptyTitle': 'لا شيء بانتظارك الآن',
    'reviewQueue.errorTitle': 'تعذّر تحميل الطلبات',
    'reviewQueue.intro': 'لم تُمنح أي مكافأة بعد. القرار لك.',
    'reviewQueue.loading': 'جارٍ تحميل الطلبات…',
    'reviewQueue.tapToReview': 'اضغط للاطّلاع على سجل التحقّق ثم القرار.',
    'reviewQueue.title': 'إنجازات بانتظار مراجعتك',
    'reviewQueue.unnamedGoal': 'هدف',
    'rewardType.CUSTOM_REWARD': 'مكافأة تختارها',
    'rewardType.CUSTOM_REWARD.hint': 'اكتب وصفها بنفسك.',
    'rewardType.DIGITAL_REWARD': 'مكافأة رقمية',
    'rewardType.DIGITAL_REWARD.hint': 'تظهر في قائمة التسليم لديك، وأنت من يسلّمها.',
    'rewardType.PARENT_APPROVAL_REWARD': 'موافقة خاصة',
    'rewardType.PARENT_APPROVAL_REWARD.hint': 'شيء يحتاج موافقتك الصريحة.',
    'rewardType.PHYSICAL_REWARD': 'مكافأة ملموسة',
    'rewardType.PHYSICAL_REWARD.hint': 'تظهر في قائمة التسليم لديك، وأنت من يسلّمها.',
    'rewardType.POINTS': 'نقاط',
    'rewardType.POINTS.hint': 'تُضاف إلى السجل فور تحقّق الإنجاز.',
    'rewardType.PRIVILEGE': 'امتياز',
    'rewardType.PRIVILEGE.hint': 'خروجة، أو سهر متأخر — أنت تقرّر وأنت تسلّم.',
    'rewardType.SCREEN_TIME': 'وقت شاشة إضافي',
    'rewardType.SCREEN_TIME.hint': 'دقائق إضافية تنتهي تلقائيًا. الحد الأقصى ٦٠ دقيقة للمنحة.',
    'suggestions.accept': 'أضِفه كهدف',
    'suggestions.acceptFailedTitle': 'لم يُضَف الهدف',
    'suggestions.accepted': 'أُضيف الهدف.',
    'suggestions.advisoryNotice': 'هذه اقتراحات فقط. لا يُنشأ أي هدف حتى تضغط «أضِفه» بنفسك.',
    'suggestions.emptyBody': 'أضِف هدفًا أو اثنين، وستصبح الاقتراحات أدقّ.',
    'suggestions.emptyTitle': 'لا توجد اقتراحات الآن',
    'suggestions.errorTitle': 'تعذّر تحميل الاقتراحات',
    'suggestions.loading': 'جارٍ تحضير الاقتراحات…',
    'suggestions.title': 'اقتراحات',
    'verification.ASSESSMENT_SCORE': 'درجة تقييم دراسي',
    'verification.CODE_CHALLENGE': 'تحدٍّ برمجي',
    'verification.COMPLETION_ARTIFACT': 'دليل إنجاز مرفق',
    'verification.DURATION': 'مدة العمل الفعلية',
    'verification.DURATION_PLUS_QUIZ': 'مدة مع اختبار',
    'verification.PARENT_CONFIRMATION': 'تأكيد الوالد',
    'verification.QUIZ': 'اختبار قصير',
    'verification.RECITATION_SUBMISSION': 'تسميع مُسجَّل',
    'verification.SELF_CHECK': 'تأكيد ذاتي',
    'verification.strength.MODERATE': 'دليل متوسط',
    'verification.strength.STRONG': 'دليل قوي',
    'verification.strength.WEAK': 'دليل خفيف',
    'wizard.allChildren': 'كل الأبناء',
    'wizard.allChildrenHint': 'متاح لكل طفل في العائلة.',
    'wizard.ayah': 'الآية',
    'wizard.ayahRangeLabel': 'نطاق الآيات',
    'wizard.catalogueEmptyBody': 'لم يُرجع الخادم أي تصنيف. حاول مجددًا بعد قليل.',
    'wizard.catalogueEmptyTitle': 'لا توجد تصنيفات متاحة',
    'wizard.catalogueErrorTitle': 'تعذّر تحميل التصنيفات',
    'wizard.childrenErrorTitle': 'تعذّر تحميل قائمة الأبناء',
    'wizard.customDuration': 'مدة أخرى بالدقائق',
    'wizard.difficulty': 'المستوى',
    'wizard.error.activityRequired': 'اختر النشاط.',
    'wizard.error.ayahOutOfSurah': 'رقم الآية خارج حدود هذه السورة.',
    'wizard.error.ayahRangeInverted': 'الآية الأخيرة يجب ألا تسبق الآية الأولى.',
    'wizard.error.categoryRequired': 'اختر المجال أولًا.',
    'wizard.error.durationOutOfRange': 'المدة يجب أن تكون بين دقيقة و٤٨٠ دقيقة.',
    'wizard.error.fromAyahRequired': 'أدخل رقم الآية الأولى.',
    'wizard.error.juzOutOfRange': 'رقم الجزء يجب أن يكون بين ١ و٣٠.',
    'wizard.error.maxPerDayInvalid': 'الحد اليومي يجب أن يكون بين ١ و٢٠.',
    'wizard.error.maxPerWeekInvalid': 'الحد الأسبوعي يجب أن يكون بين ١ و١٤٠.',
    'wizard.error.minAgeInvalid': 'أقل عمر يجب أن يكون بين ٠ و١٨.',
    'wizard.error.passScoreRequired': 'حدّد درجة نجاح بين ١ و١٠٠.',
    'wizard.error.quantityInvalid': 'الكمية يجب أن تكون عددًا صحيحًا موجبًا.',
    'wizard.error.rewardAmountInvalid': 'قيمة المكافأة يجب أن تكون عددًا صحيحًا موجبًا.',
    'wizard.error.screenTimeAboveMax': 'الحد الأقصى لمنحة وقت الشاشة الواحدة ٦٠ دقيقة.',
    'wizard.error.screenTimeTtlInvalid': 'مدة الصلاحية يجب أن تكون بين ساعة و١٦٨ ساعة.',
    'wizard.error.surahRequired': 'اختر السورة.',
    'wizard.error.verificationRequired': 'اختر طريقة التحقّق.',
    'wizard.error.weeklyBelowDaily': 'الحد الأسبوعي لا يصح أن يقل عن الحد اليومي.',
    'wizard.frequency': 'التكرار',
    'wizard.fromAyah': 'من الآية',
    'wizard.fulfilmentNote': 'ستظهر هذه المكافأة في قائمة التسليم لديك بعد تحقّق الإنجاز.',
    'wizard.hint.child': 'اختر طفلًا بعينه، أو اترك الهدف متاحًا لكل الأبناء.',
    'wizard.hint.reward': 'النقاط تُحتسب تلقائيًا. المكافآت الملموسة تظهر في قائمة التسليم لديك.',
    'wizard.hint.rules': 'هذه الحدود يفرضها الخادم عند كل محاولة، لا التطبيق.',
    'wizard.hint.verification': 'لكل طريقة وزن مختلف — والشرح تحت كل خيار هو الفارق الحقيقي.',
    'wizard.isReview': 'هذا هدف مراجعة',
    'wizard.isReviewHint': 'مراجعة لما حُفِظ سابقًا، لا حفظ جديد.',
    'wizard.juzNumber': 'الجزء {{number}}',
    'wizard.loadingCatalogue': 'جارٍ تحميل التصنيفات…',
    'wizard.loadingSurahs': 'جارٍ تحميل السور…',
    'wizard.maxPerDay': 'الحد الأقصى يوميًا',
    'wizard.maxPerWeek': 'الحد الأقصى أسبوعيًا',
    'wizard.minAge': 'أقل عمر (اختياري)',
    'wizard.moreSurahs': 'و{{count}} سورة أخرى — استخدم البحث',
    'wizard.next': 'التالي',
    'wizard.noActivitiesBody': 'اختر تصنيفًا آخر من الخطوة السابقة.',
    'wizard.noActivitiesTitle': 'لا توجد أنشطة لهذا التصنيف',
    'wizard.noSurahMatch': 'لا توجد سورة بهذا الاسم',
    'wizard.passScore': 'درجة النجاح (%)',
    'wizard.preview.ayahRange': 'الآيات {{from}}–{{to}} من سورة {{name}}',
    'wizard.preview.singleAyah': 'الآية {{ayah}} من سورة {{name}}',
    'wizard.preview.surah': 'سورة {{name}}',
    'wizard.quantity': 'الكمية',
    'wizard.reference': 'المرجع (اسم الكتاب أو الدرس)',
    'wizard.repetitions': 'عدد التكرارات (اختياري)',
    'wizard.requiresApproval': 'يتطلب تأكيدي دائمًا',
    'wizard.requiresApprovalHint': 'حتى لو نجح التحقّق الآلي، لا تُمنح المكافأة قبل موافقتك.',
    'wizard.review.activity': 'النشاط',
    'wizard.review.category': 'المجال',
    'wizard.review.child': 'لِمن',
    'wizard.review.duration': 'المدة',
    'wizard.review.reward': 'المكافأة',
    'wizard.review.rules': 'القواعد',
    'wizard.review.rulesValue': '{{frequency}} · {{perDay}} يوميًا · {{perWeek}} أسبوعيًا',
    'wizard.review.serverNote': 'يتحقّق الخادم من كل قيمة مرة أخرى قبل الحفظ.',
    'wizard.review.target': 'المطلوب',
    'wizard.review.verification': 'التحقّق',
    'wizard.rewardAmount': 'قيمة المكافأة',
    'wizard.rewardDescription': 'وصف المكافأة',
    'wizard.rewardMinutes': 'الدقائق الإضافية',
    'wizard.save': 'حفظ الهدف',
    'wizard.saveFailedTitle': 'لم يُحفَظ الهدف',
    'wizard.screenTimeNote': 'منحة وقت الشاشة تنتهي تلقائيًا ولا تعدّل سياسة الجهاز الأساسية.',
    'wizard.screenTimeTtl': 'صلاحية المنحة بالساعات',
    'wizard.searchSurah': 'ابحث عن سورة…',
    'wizard.selectedSurah': 'سورة {{name}}',
    'wizard.singleAyahLabel': 'رقم الآية',
    'wizard.step.activity': 'ما النشاط؟',
    'wizard.step.category': 'ما مجال الهدف؟',
    'wizard.step.child': 'لمن هذا الهدف؟',
    'wizard.step.duration': 'كم من الوقت؟',
    'wizard.step.review': 'مراجعة وحفظ',
    'wizard.step.reward': 'ما المكافأة؟',
    'wizard.step.rules': 'قواعد التكرار',
    'wizard.step.target': 'ما المطلوب تحديدًا؟',
    'wizard.step.verification': 'كيف نتحقّق من الإنجاز؟',
    'wizard.surahAyahCount': '{{count}} آية',
    'wizard.surahRow': '{{number}} · {{name}}',
    'wizard.surahsEmptyTitle': 'لم تصل قائمة السور',
    'wizard.surahsErrorTitle': 'تعذّر تحميل السور',
    'wizard.title': 'هدف جديد',
    'wizard.toAyah': 'إلى الآية',
    'wizard.unit': 'الوحدة (صفحة، تمرين، …)',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'حدث خطأ ما.',
    'common.retry': 'إعادة المحاولة',
    'common.offlineBanner': 'لا يوجد اتصال بالإنترنت',
    'digitalTwin.title': 'التوأم الرقمي',
    'digitalTwin.notARankingTool': 'صورة لتقدّم طفلك الحالي عبر عدة مجالات — وليست درجة لتصنيف الأطفال أو مقارنتهم.',
    'digitalTwin.growthScore': 'مؤشر النمو',
    'digitalTwin.basedOnSubScores': 'بناءً على {{count}} من أصل {{total}} مؤشرات متاحة',
    'digitalTwin.health': 'الصحة',
    'digitalTwin.learning': 'التعلّم',
    'digitalTwin.faith': 'الإيمان',
    'digitalTwin.habits': 'العادات',
    'digitalTwin.social': 'الاجتماعي',
    'digitalTwin.behavior': 'السلوك',
    'digitalTwin.safety': 'الأمان',
    'digitalTwin.notYetAvailable': 'غير متاح بعد',
    'lifeTimeline.title': 'الخط الزمني للحياة',
    'lifeTimeline.all': 'الكل',
    'lifeTimeline.empty': 'لا توجد أحداث بعد.',
    'lifeTimeline.category.health': 'الصحة',
    'lifeTimeline.category.learning': 'التعلّم',
    'lifeTimeline.category.faith': 'الإيمان',
    'lifeTimeline.category.rewards': 'المكافآت',
    'lifeTimeline.category.safety': 'الأمان',
    'lifeTimeline.category.habits': 'العادات',
    'lifeTimeline.category.family': 'الأسرة',
    'habitTracker.title': 'العادات',
    'habitTracker.empty': 'لا توجد عادات بعد.',
    'habitTracker.shared': 'مشتركة',
    'habitTracker.markDone': 'تم الإنجاز',
    'healthTrend.title': 'الصحة',
    'healthTrend.score': 'مؤشر الصحة',
    'healthTrend.hydration': 'الترطيب',
    'learningProgress.title': 'التعليم',
    'pendingApprovals.title': 'بانتظار الموافقة',
    'pendingApprovals.empty': 'لا يوجد شيء ينتظر موافقتك الآن.',
    'pendingApprovals.approve': 'موافقة',
    'pendingApprovals.reject': 'رفض',
    'learningProgress.streak': 'تتابع التعلم',
    'learningProgress.streakDays': '{{count}} يوم',
    'learningProgress.sessions': 'جلسات المذاكرة (30 يوم)',
    'learningProgress.minutes': 'إجمالي الدقائق (30 يوم)',
    'learningProgress.avgScore': 'متوسط الدرجات',
    'learningProgress.notYetAvailable': 'غير متاح بعد',
    'healthTrend.activity': 'النشاط',
    'healthTrend.sleep': 'النوم',
    'healthTrend.meals': 'الوجبات المسجَّلة',
    'healthTrend.minutes': 'دقيقة',
    'healthTrend.hours': 'ساعة',
    'healthTrend.notLogged': 'غير مُسجَّل',
    'healthTrend.logWater': 'سجّل ماء',
    'faithProgress.title': 'الإيمان',
    'faithProgress.empty': 'لا توجد ممارسات بعد.',
    'faithProgress.logToday': 'سجّل اليوم',
    'familyStore.title': 'متجر الأسرة',
    'familyStore.empty': 'لا توجد مكافآت بالمتجر بعد.',
    'familyStore.coins': 'عملة',
    'coaching.title': 'التوجيه',
    'coaching.empty': 'لا توجد توصيات حاليًا.',
    'coaching.track.parent': 'لك',
    'coaching.track.child': 'لطفلك',
    'coaching.track.family': 'للأسرة',
    'coaching.track.other': 'اقتراح',
    'lifeIntelligence.actionFailedTitle': 'لم تكتمل العملية',
    'healthTrend.millilitres': 'مل',
    'messageCategory.ACHIEVEMENT_REJECTED': 'إنجاز أُعيد',
    'messageCategory.ACHIEVEMENT_VERIFIED': 'إنجاز مُعتمد',
    'messageCategory.AI_RECOMMENDATION': 'اقتراح',
    'messageCategory.BADGE_EARNED': 'شارة',
    'messageCategory.CHILD_WELLBEING_CHECKIN': 'اطمئنان',
    'messageCategory.DAILY_GOAL_COMPLETED': 'هدف اليوم',
    'messageCategory.EXERCISE_ENCOURAGEMENT': 'حركة ونشاط',
    'messageCategory.HYDRATION_REMINDER': 'تذكير بالماء',
    'messageCategory.LEARNING_GOAL_ACHIEVED': 'هدف تعليمي',
    'messageCategory.LEVEL_UP': 'مستوى جديد',
    'messageCategory.REWARD_GRANTED_CHILD': 'مكافأة',
    'messageCategory.STREAK_ACHIEVED': 'مواظبة',
    'messageCategory.STUDY_REMINDER': 'تذكير بالمذاكرة',
    'messageCategory.other': 'رسالة',
    'digitalTwinInput.activePractices': 'ممارسات نشطة',
    'digitalTwinInput.averageAssessmentScore': 'متوسّط الدرجات',
    'digitalTwinInput.challengeParticipations': 'تحديات شارك فيها',
    'digitalTwinInput.completedHabitDays': 'أيام أُنجزت فيها عادة',
    'digitalTwinInput.completedLogs': 'ممارسات مُسجَّلة',
    'digitalTwinInput.groupActivityCount': 'أنشطة جماعية',
    'digitalTwinInput.groupBadgeCount': 'شارات جماعية',
    'digitalTwinInput.nutritionLogsCount': 'وجبات مُسجَّلة',
    'digitalTwinInput.overallRisk': 'مؤشّر المخاطر',
    'digitalTwinInput.riskAssessmentCount': 'مرات فحص الأمان',
    'digitalTwinInput.sharedHabitCompletions': 'عادات مشتركة أُنجزت',
    'digitalTwinInput.sleepHours': 'ساعات النوم',
    'digitalTwinInput.streakDays': 'أيام المواظبة',
    'digitalTwinInput.totalHabitDays': 'الأيام المحسوبة',
    'digitalTwinInput.totalMinutes': 'إجمالي الدقائق',
    'digitalTwinInput.totalSessions': 'جلسات المذاكرة',
    'digitalTwinInput.trustChangeCount': 'تغيّرات الثقة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'auth.loginTitle': 'دخول الوالدين',
    'auth.loginTagline': 'تابع، احمِ، ووجّه رحلة أطفالك الرقمية',
    'wellbeing.title': 'الرفاهية الرقمية',
    'wellbeing.insightTitle': 'ملاحظة اليوم',
    'wellbeing.noData': 'لا توجد بيانات رفاهية رقمية بعد \u2014 ستظهر بمجرد مزامنة الجهاز ليوم واحد على الأقل.',
    'wellbeing.notYetAvailable': 'غير متاح بعد',
    'wellbeing.avgScreenTime': 'متوسط وقت الشاشة',
    'wellbeing.avgPickups': 'متوسط مرات الالتقاط',
    'wellbeing.nightUsage': 'متوسط الاستخدام الليلي',
    'wellbeing.blockedAttempts': 'محاولات محظورة',
    'wellbeing.minutesPerDay': 'دقيقة/يوم',
    'wellbeing.windowNote': 'بناءً على {daysWithData} من آخر {days} يوم',
    'subscription.title': 'الاشتراك',
    'subscription.availablePlans': 'الخطط المتاحة',
    'subscription.trialTitle': 'التجربة المجانية نشطة',
    'subscription.trialBody': 'باقي {days} يوم في فترتك التجريبية',
    'subscription.activeTitle': 'الاشتراك نشط',
    'subscription.activeBody': 'أنت مشترك في خطة {plan}',
    'subscription.activeBodyNoPlan': 'اشتراكك نشط.',
    'subscription.pastDueTitle': 'مشكلة في الدفع',
    'subscription.pastDueBody': 'فشلت آخر عملية دفع. برجاء تحديث وسيلة الدفع للحفاظ على اشتراكك نشطًا.',
    'subscription.inactiveTitle': 'لا يوجد اشتراك نشط',
    'subscription.inactiveBody': 'اختر خطة أدناه للاستمرار في استخدام الميزات المميزة.',
    'subscription.noneTitle': 'ابدأ الآن',
    'subscription.noneBody': 'اختر خطة للبدء.',
    'subscription.pendingTitle': 'بانتظار إتمام الدفع',
    'subscription.pendingBody':
        'سجّلنا طلبك ولم يصلنا الدفع بعد. يبدأ اشتراكك فور تأكيد العملية.',
    'subscription.graceTitle': 'وصولك مستمر',
    'subscription.graceBody':
        'لم تكتمل آخر عملية دفع، ووصولك إلى الميزات كامل خلال مهلة سماح قصيرة. حدّث وسيلة الدفع للاستمرار دون انقطاع.',
    'subscription.refundedTitle': 'تم رد المبلغ',
    'subscription.refundedBody':
        'أعدنا مبلغ اشتراكك، وانتهى الوصول إلى الميزات المميزة. يمكنك الاشتراك من جديد في أي وقت.',
    'subscription.free': 'مجانًا',
    'subscription.currentPlan': 'خطتك الحالية',
    'subscription.choosePlan': 'اختر الخطة',
    'subscription.cancel': 'إلغاء الاشتراك',
    'subscription.viewHistory': 'عرض تاريخ الفوترة',
    // PHASE G — العربية أولًا، وكل حالة جملة مختلفة: «لا نعرف بلد الفاتورة»
    // و«لم يُنشر سعر بعد» و«لا يستطيع هذا الإصدار فتح المتجر» ثلاث حقائق
    // مختلفة، وكلها تنتهي بـ«لم يُخصم شيء» لأن ذلك هو ما يطمئن الوالد فعلًا.
    'subscription.purchaseMarketUnknown':
        'لم نتعرّف بعد على بلد الفاتورة لهذا الحساب، ولن نخمّن سعرًا. تواصل مع الدعم وسنضبطها لك.',
    'subscription.purchaseNotConfigured':
        'هذه الخطة غير معروضة للبيع بعد — لم يُنشر سعرها في بلدك. لم يُخصم أي مبلغ.',
    'subscription.purchaseStoreUnavailable':
        'تُباع هذه الخطة عبر متجر التطبيقات، وهذا الإصدار من التطبيق لا يستطيع فتح صفحة الدفع في المتجر. حدّث التطبيق ثم أعد المحاولة. لم يُخصم أي مبلغ.',
    'subscription.purchaseFailed':
        'لم تكتمل عملية الشراء، ولم يُخصم أي مبلغ. أعد المحاولة، أو تواصل مع الدعم إن تكرّر الأمر.',
    'billingHistory.title': 'تاريخ الفوترة',
    'billingHistory.empty': 'لا توجد فواتير بعد.',
    'support.title': 'المساعدة والدعم',
    'support.faqTitle': 'الأسئلة الشائعة',
    'support.faq.q1': 'إزاي أقرن جهاز طفلي؟',
    'support.faq.a1': 'روح لـ الإعدادات > إضافة طفل في هذا التطبيق، ولّد كود إقران، وبعدها اكتب الكود ده في تطبيق الطفل على جهازه خلال المدة الظاهرة.',
    'support.faq.q2': 'ليه حالة طفلي ظاهرة "غير متصل"؟',
    'support.faq.a2': 'غالبًا معناها إن الجهاز مبعتش نبضة اتصال مؤخرًا \u2014 تأكد إن تحسين البطارية معطَّل وخدمة إمكانية الوصول لسه مفعَّلة على جهاز طفلك.',
    'support.faq.q3': 'إزاي تشتغل حدود وقت الشاشة؟',
    'support.faq.a3': 'الحدود اللي بتحددها بتتزامن مع الجهاز وتُفرَض حتى بدون اتصال إنترنت، باستخدام آخر سياسة اتزامنت بنجاح.',
    'support.faq.q4': 'أقدر أغيّر خطة اشتراكي؟',
    'support.faq.a4': 'أيوه \u2014 روح لـ الإعدادات > الاشتراك عشان تشوف الخطط المتاحة وتغيّر في أي وقت.',
    'support.faq.q5': 'بيانات طفلي آمنة؟',
    'support.faq.a5': 'إحنا بنجمع بس ملخّصات استخدام مُجمَّعة، ومش بنجمع محتوى رسائل خام، صور، أو ضغطات مفاتيح. راجع سياسة الخصوصية لتفاصيل كاملة.',
    'support.stillNeedHelp': 'لسه محتاج مساعدة؟',
    'support.contactBody': 'ابعتلنا رسالة وهنرد عليك بالإيميل.',
    'support.contactButton': 'تواصل معنا',
    'support.contactTitle': 'تواصل مع الدعم',
    'support.email': 'إيميلك',
    'support.subject': 'الموضوع',
    'support.message': 'الرسالة',
    'support.send': 'إرسال الرسالة',
    'support.sentTitle': 'تم إرسال الرسالة!',
    'support.sentBody': 'استلمنا رسالتك وهنرد عليك بالإيميل قريبًا.',
    'support.sendFailedTitle': 'رسالتك ما اتبعتتش',
    'dashboard.pairDevice': 'قرن جهاز',
    'createChild.title': 'إضافة طفل',
    'createChild.firstName': 'الاسم الأول',
    'createChild.lastNameOptional': 'اسم العائلة (اختياري)',
    'createChild.dateOfBirth': 'تاريخ الميلاد',
    'createChild.selectDate': 'اختر تاريخ',
    'createChild.consentTitle': 'قبل ما تكمل',
    'createChild.consentBody': 'بإضافة الطفل ده، إنت بتوافق على جمع بيانات أساسية، تتبّع الموقع، مراقبة استخدام التطبيقات، وتحليل السلوك بالذكاء الاصطناعي لحمايته. تقدر تراجع وتغيّر أي من دول في أي وقت من الإعدادات > إدارة الموافقات.',
    'createChild.submit': 'إضافة الطفل',
    'createChild.dateOfBirthRequired': 'من فضلك اختر تاريخ الميلاد.',
    'createChild.saveFailedTitle': 'ملف الطفل ما اتعملش',
    'createChild.unnamedChild': 'طفل',
    'consents.title': 'إدارة الموافقات',
    'consents.loadFailedTitle': 'تعذّر تحميل إعدادات الموافقات',
    'consents.selectChild': 'اختر الطفل',
    'consents.noChildren': 'ضيف طفل الأول عشان تقدر تدير إعدادات الموافقة بتاعته.',
    'consents.explanation': 'تحكّم بالظبط في البيانات اللي بتتجمع لكل طفل. تقدر تقفل أي منها في أي وقت \u2014 بعض الميزات ممكن تتوقف لو عملت كده.',
    'consents.type.DATA_COLLECTION.title': 'جمع البيانات الأساسي',
    'consents.type.DATA_COLLECTION.description': 'بيانات الحساب والاستخدام الأساسية اللازمة لعمل التطبيق.',
    'consents.type.LOCATION_TRACKING.title': 'تتبّع الموقع',
    'consents.type.LOCATION_TRACKING.description': 'تتبّع موقع جهاز طفلك.',
    'consents.type.APP_USAGE_MONITORING.title': 'مراقبة استخدام التطبيقات',
    'consents.type.APP_USAGE_MONITORING.description': 'جمع ملخّصات مُجمَّعة لاستخدام التطبيقات \u2014 صفر محتوى خام.',
    'consents.type.AI_BEHAVIOR_ANALYSIS.title': 'تحليل السلوك بالذكاء الاصطناعي',
    'consents.type.AI_BEHAVIOR_ANALYSIS.description': 'خلّي الذكاء الاصطناعي يحلّل الأنماط السلوكية عشان يدّيك رؤى وإرشاد.',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.title': 'تحليل سلوك لوحة المفاتيح',
    'consents.type.KEYBOARD_BEHAVIOR_ANALYSIS.description': 'غير متاحة بعد \u2014 محجوزة لميزة أمان مستقبلية تحت مراجعة منفصلة.',
    'consents.type.HEALTH_DATA.title': 'البيانات الصحية',
    'consents.type.HEALTH_DATA.description': 'جمع بيانات صحية زي سجلات شرب المياه والنشاط.',
    'deleteAccount.title': 'حذف الحساب',
    'deleteAccount.warningTitle': 'هذا الإجراء لا يمكن التراجع عنه',
    'deleteAccount.warningBody': 'حذف حسابك هيشيل الوصول لكل ملفات الأطفال، يلغي اشتراكك، ويسجّل خروجك من كل الأجهزة. بياناتك هتتخفى هويتها فورًا.',
    'deleteAccount.confirmCheckbox': 'أنا فاهم إن الإجراء ده نهائي',
    'deleteAccount.currentPassword': 'اكتب كلمة السر الحالية للتأكيد',
    'deleteAccount.submit': 'احذف حسابي نهائيًا',
    'deleteAccount.errorRefusedTitle': 'لم يتم حذف حسابك',
    'deleteAccount.errorUnconfirmedTitle': 'لم يصلنا تأكيد بحذف الحساب',
    'auth.acceptTerms': 'أوافق على شروط الاستخدام وسياسة الخصوصية',
    'auth.acceptTermsRequired':
        'من فضلك وافق على شروط الاستخدام وسياسة الخصوصية للمتابعة.',

    'invoiceStatus.PAID': 'مدفوعة',
    'invoiceStatus.OPEN': 'مستحقّة',
    'invoiceStatus.DRAFT': 'لم تُصدر بعد',
    'invoiceStatus.VOID': 'ملغاة',
    'invoiceStatus.UNCOLLECTIBLE': 'تعذّر تحصيلها',
    'invoiceStatus.unknown': 'قيد المعالجة',

    'redeemCode.entryPoint': 'عندك كود شراكة؟',
    'redeemCode.title': 'استبدال كود',
    'redeemCode.explanation': 'اكتب كود من شريك (زي جهة عملك، بنكك، أو شركة الاتصالات بتاعتك) عشان تفتح ميزة لحسابك.',
    'redeemCode.codeLabel': 'اكتب الكود',
    'redeemCode.submit': 'استبدال الكود',
    'redeemCode.rejectedTitle': 'الكود ده مش مقبول',
    'redeemCode.notAppliedTitle': 'الكود لسه ما اتستخدمش — جرّب تاني بعد شوية',
    'redeemCode.successFallback': 'تم تفعيل الكود.',
    'dashboard.notificationsTooltip': 'الإشعارات',
    'dashboard.settingsTooltip': 'الإعدادات',
    'common.done': 'تم',
    'dashboard.firstChildTitle': 'أهلًا بيك! يلا نضيف طفلك الأول',
    'dashboard.firstChildBody': 'ضيف ملف الطفل، وبعدين قرن جهازه عشان تبدأ تحمي وتوجّه رحلته الرقمية.',
    'dashboard.addFirstChild': 'ضيف طفلك الأول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.login': 'دخول',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.createAccount': 'إنشاء حساب جديد',
    'auth.registerTitle': 'إنشاء حساب العائلة',
    'auth.fullName': 'الاسم الكامل',
    'auth.phone': 'الهاتف',
    'auth.register': 'إنشاء الحساب',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'family.setupTitle': 'إعداد عائلتك',
    'family.name': 'اسم العائلة',
    'family.country': 'الدولة',
    'family.country.EG': 'مصر',
    'family.country.SA': 'السعودية',
    'family.timezoneExplainer':
        'سيبدأ يوم عائلتك وينتهي بتوقيت {{country}} المحلي — تتبعه سلاسل الإنجاز والحدود اليومية والمكافآت.',
    'family.continueButton': 'متابعة',
    'dashboard.title': 'الرئيسية',
    // PHASE E (§6) — العربية أولًا: هذه هي الإجابتان اللتان تُفتح بهما الشاشة.
    'dashboard.needsYouTitle': 'هل هناك شيء يحتاج مني؟',
    'dashboard.needsYouNothing': 'لا شيء ينتظرك الآن.',
    'dashboard.needsYouReviews': '{{count}} إنجازات تنتظر مراجعتك',
    'dashboard.needsYouReviews_one': 'إنجاز واحد ينتظر مراجعتك',
    'dashboard.needsYouReviews_other': '{{count}} إنجازات تنتظر مراجعتك',
    'dashboard.needsYouMessages': '{{count}} رسائل تنتظر موافقتك',
    'dashboard.needsYouMessages_one': 'رسالة واحدة تنتظر موافقتك',
    'dashboard.needsYouMessages_other': '{{count}} رسائل تنتظر موافقتك',
    'dashboard.childStatusTitle': 'هل ابنك بخير اليوم؟',
    // enum المخاطر من الـ backend، مصاغًا كإجابة لا كدرجة خطورة.
    'riskLevel.LOW': 'كل شيء تمام',
    'riskLevel.MEDIUM': 'يستحق نظرة',
    'riskLevel.HIGH': 'يحتاج منك اليوم',
    'riskLevel.CRITICAL': 'يحتاج منك الآن',
    'riskLevel.UNKNOWN': 'لا توجد بيانات اليوم',
    'dashboard.familySummary': 'ملخص العائلة',
    // F2: the BASE key was missing from Arabic while _one/_other were
    // present. Latent rather than active (every call site passes a
    // count, so _resolvePluralKey never falls back to the base key) —
    // but since F1 made Arabic the DEFAULT locale, a missing Arabic key
    // no longer degrades to English: translate() falls back to the same
    // Arabic map and then to the RAW KEY, which is what the user would
    // read on screen. Parity is now enforced by
    // scripts/verify_l10n_parity.py.
    'dashboard.children': '{{count}} أطفال',
    'dashboard.children_one': 'طفل واحد',
    'dashboard.children_other': '{{count}} أطفال',
    'dashboard.devices': '{{count}} أجهزة',
    'dashboard.alerts': '{{count}} تنبيهات',
    'dashboard.addChild': 'إضافة طفل',
    'dashboard.viewReports': 'عرض التقارير',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.settings': 'الإعدادات',
    'dashboard.online': 'متصل',
    'dashboard.offline': 'غير متصل',
    'pairing.addChildTitle': 'إضافة طفل',
    'pairing.noChildrenYet': 'أضف طفلًا من لوحة التحكم أولًا قبل إقران جهاز.',
    'pairing.selectChild': 'اختر الطفل',
    'pairing.generateCode': 'إنشاء رمز إقران',
    'pairing.validFor': 'صالح لمدة',
    'pairing.waitingTitle': 'في انتظار جهاز طفلك',
    'pairing.waitingBody':
        'أبقِ هذه الشاشة مفتوحة. بمجرد إدخال الرمز على هاتف طفلك ستظهر النتيجة هنا.',
    'pairing.connectedTitle': 'تم اتصال جهاز طفلك',
    'pairing.connectedActiveBody': 'الجهاز مرتبط بعائلتك وحالته نشطة.',
    'pairing.connectedPendingBody':
        'الجهاز مرتبط بعائلتك، وسيظهر في قائمة الأجهزة حيث يمكنك متابعة حالته.',
    'pairing.notYetTitle': 'لم يتصل أي جهاز بعد',
    'pairing.notYetBody':
        'الرمز صالح لمدة {{minutes}} دقائق، وقد انتهت مدة هذا الرمز. لم يحدث أي خطأ — أنشئ رمزًا جديدًا متى كان هاتف طفلك بين يديك.',
    'pairing.cannotConfirmTitle': 'الرمز جاهز',
    'pairing.cannotConfirmBody':
        'تعذّرت قراءة قائمة أجهزتك في هذه اللحظة، لذا لا تستطيع هذه الشاشة تأكيد الإقران بنفسها. الرمز يعمل كالمعتاد — راجع قائمة الأجهزة بعد ذلك.',
    'pairing.revokeAction': 'إلغاء ربط هذا الجهاز',
    'pairing.revokeHint': 'استخدم هذا إذا أُدخل الرمز على هاتف غير المقصود.',
    'pairing.revokeConfirmTitle': 'إلغاء ربط هذا الجهاز؟',
    'pairing.revokeConfirmBody':
        'سيفقد الجهاز الوصول إلى عائلتك فورًا، ويمكنك إقرانه مجددًا لاحقًا برمز جديد.',
    'pairing.revokedTitle': 'تم إلغاء ربط الجهاز',
    'pairing.revokedBody': 'لم يعد لديه وصول إلى عائلتك. أنشئ رمزًا جديدًا لإقران جهاز مرة أخرى.',
    'pairing.activateAction': 'تأكيد الجهاز وتفعيله',
    'pairing.activateHint':
        'هذه هي الخطوة الأخيرة: بعد التفعيل تبدأ خطة عائلتك في العمل على هذا الجهاز.',
    'pairing.activatePreparingBody':
        'الجهاز ما زال يُكمل تجهيز نفسه، فلا يوجد ما تؤكّده الآن. الأمر لا يستغرق سوى لحظات.',
    'pairing.checkAgainAction': 'تحقّق مرة أخرى',
    'pairing.activationNoticeTitle': 'ردّ الخادم',
    'notifications.title': 'الإشعارات',
    'notifications.empty': 'لا يوجد إشعارات بعد.',
    'notifications.markAllRead': 'تعليم الكل كمقروء',

    // ------------------------------------------------------------------
    // G18 — تمهيد إذن الإشعارات، يظهر داخل هذه الشاشة نفسها.
    //
    // كان الإذن يُطلب عند بدء التطبيق من شاشة البداية، قبل أن يرى الأب
    // إشعارًا واحدًا. أصبح يُطلب هنا، حيث ينظر الأب إلى الرسائل نفسها
    // التي يحكمها الإذن — فيصبح الشرح جملة واحدة عن شيء أمامه على
    // الشاشة، لا محاولة إقناع.
    // ------------------------------------------------------------------
    'notifications.permTitle': 'هذه الرسائل لا تصل إلى هاتفك',
    'notifications.permBody':
        'تستطيع قراءتها هنا، لكن أندرويد لن يعرضها على هاتفك حتى تسمح بالإشعارات. لا يتغير أي شيء آخر في التطبيق.',
    'notifications.permEnable': 'اسمح بالإشعارات',
    'notifications.permGranted': 'تمّ — ستصل هذه الرسائل إلى هاتفك من الآن.',
    'notifications.permDenied':
        'لم يُسمح بها. تستطيع قراءة كل شيء هنا كما هو. ولتغيير ذلك لاحقًا، شغّل إشعارات «ابني» من إعدادات هاتفك.',

    'deepLink.unavailable':
        'هذا الجزء من التطبيق ليس جاهزًا بعد — أبقيناك في صندوق الإشعارات.',

    // -----------------------------------------------------------------------
    // سطح الأمان والحماية. كل سطر هنا نصٌّ يخصّ التطبيق نفسه — اسم نوع الحدث،
    // ودرجة الاهتمام، وما يمكن للأب أو الأم فعله. أمّا الجملة التي تصف ما حدث
    // فهي من الخادم (`title` / `body`) وتُعرض كما هي ولا تمرّ من هنا أبدًا.
    //
    // النبرة شرطٌ لا تفضيل: هادئة ومحدّدة ولا تُثير القلق بلا داعٍ. كل سطر
    // إرشاد يجيب على «ماذا أفعل الآن؟»، لأنّ تنبيهًا بلا خطوة عملية ليس إلا
    // قلقًا. وسطر الاطمئنان يذكر ضمانة الخصوصية صراحةً، لأنّ الخادم يرسل
    // تنبيهًا عامًّا عن قصد في هذا المسار.
    // -----------------------------------------------------------------------
    'safety.title': 'الأمان والحماية',
    'safety.introTitle': 'ما يخصّ حماية أطفالك',
    'safety.introBody':
        'تنبيهات الحماية ووقت الشاشة كما وصلتك، الأحدث أولًا. ولا نعرض هنا ما يكتبه طفلك.',
    'safety.emptyTitle': 'لا توجد تنبيهات',
    'safety.emptyBody':
        'لم يصلك أي تنبيه يخصّ الحماية أو وقت الشاشة. وهذا هو الوضع الطبيعي.',
    'safety.errorTitle': 'تعذّر عرض التنبيهات',
    'safety.notInRecentTitle': 'لم نعثر على هذا التنبيه',
    'safety.notInRecent':
        'هذا التنبيه لم يعد ضمن أحدث التنبيهات. والقائمة أدناه هي آخر ما وصلك.',
    'safety.genericType': 'تنبيه يخصّ الحماية',
    'safety.genericGuidance': 'راجع الجهاز في أول وقت مناسب لك.',
    'safety.new': 'جديد',
    'safety.openChild': 'افتح صفحة الطفل',
    'safety.openChildNamed': 'افتح صفحة {{name}}',
    'safety.whenToday': 'اليوم {{time}}',
    'safety.whenYesterday': 'أمس {{time}}',
    'safety.whenOn': '{{date}} — {{time}}',

    'safetyBand.needsAttention': 'يحتاج انتباهك',
    'safetyBand.worthReviewing': 'يستحق المراجعة',
    'safetyBand.forInformation': 'للعلم',

    'safetyType.ACCESSIBILITY_DISABLED': 'الحماية متوقّفة على الجهاز',
    'safetyType.PROTECTION_BYPASS_ATTEMPT': 'محاولة لإيقاف الحماية',
    'safetyType.CHILD_WELLBEING_CHECKIN': 'اطمئنّ على طفلك',
    'safetyType.POLICY_VIOLATION': 'أمر يستحق مراجعتك في الإعدادات',
    'safetyType.SCREEN_TIME_EXCEEDED': 'انتهى وقت الشاشة المخصّص',
    'safetyType.RUNTIME_ALERT': 'تنبيه من الجهاز',

    'safetyGuidance.ACCESSIBILITY_DISABLED':
        'ما دامت هذه الخدمة متوقّفة، لا يُطبَّق أي حدٍّ لوقت الشاشة ولا أي قاعدة حجب. افتح إعدادات إمكانية الوصول على الجهاز وأعد تفعيلها.',
    'safetyGuidance.PROTECTION_BYPASS_ATTEMPT':
        'سُجِّلت محاولة لإيقاف الحماية. تحقّق من الجهاز، ثم اجعلها حديثًا هادئًا مع طفلك قبل تغيير أي إعداد.',
    'safetyGuidance.CHILD_WELLBEING_CHECKIN':
        'ما كتبه طفلك لم يُحفَظ ولا يُعرض لك — وصلك تنبيه عام فقط. وأفضل خطوة الآن وقتٌ هادئ وسؤال بسيط: كيف كان يومك؟',
    'safetyGuidance.POLICY_VIOLATION':
        'لا حاجة إلى إجراء فوري. راجع إعدادات هذا الجهاز حين يناسبك.',
    'safetyGuidance.SCREEN_TIME_EXCEEDED':
        'طُبِّق الحد تلقائيًا على الجهاز. ويمكنك مراجعة الوقت وتعديله من صفحة الطفل.',
    'safetyGuidance.RUNTIME_ALERT':
        'سجّل الجهاز هذا التنبيه. راجع حالة الجهاز في أول وقت مناسب لك.',

    // -----------------------------------------------------------------------
    // صفحة طفل واحد — ما يفتحه `abny://child/<id>`، وهي المضيف للشاشات الثلاث
    // التي لا يستطيع أي رابط أن يسمّي لها طفلًا.
    // -----------------------------------------------------------------------
    'childDetail.title': 'صفحة الطفل',
    'childDetail.unnamed': 'طفلك',
    'childDetail.age': '{{count}} سنة',
    'childDetail.age_one': 'سنة واحدة',
    'childDetail.age_other': '{{count}} سنة',
    'childDetail.inactive': 'ملف غير مفعّل',
    'childDetail.sectionTitle': 'ماذا تريد أن ترى؟',
    'childDetail.sectionSubtitle': 'ثلاث شاشات تخصّ هذا الطفل وحده.',
    'childDetail.progressHint': 'ما يتعلّمه وما أنجزه.',
    'childDetail.coachHint': 'اقتراحات عملية لك ولطفلك.',
    'childDetail.screenTimeHint': 'وقت الشاشة والعادات الرقمية.',
    'childDetail.footnote':
        'كل ما تراه هنا يأتي من الجهاز ومن الخادم، ولا يُقرَّر داخل التطبيق.',
    'childDetail.errorTitle': 'تعذّر فتح صفحة الطفل',
    'childDetail.missingTitle': 'لم نعثر على هذا الطفل',
    'childDetail.missingBody':
        'قد يكون الملف قد حُذف، أو أنّ الرابط يشير إلى طفل خارج عائلتك. افتح لوحة التحكم لاختيار طفل.',

    'dashboard.openSafety': 'الأمان والحماية',
    'childActions.childPage': 'صفحة الطفل',

    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.profile': 'الملف الشخصي',
    'settings.subscription': 'الاشتراك',
    'settings.privacy': 'الخصوصية',
    'settings.logout': 'تسجيل الخروج',
  },
};

/// ARABIC IS THE DEFAULT, not English (audit MA-016).
///
/// CONTEXT §1 makes Arabic the product's FIRST language for the first two
/// markets (Egypt, then Saudi Arabia) — "RTL حقيقي، لا ترجمة". Shipping
/// `AppLocale.en` here meant every child and every parent in those markets
/// opened the app in English and had to go find a language switch, which
/// is the exact opposite of the stated positioning.
///
/// This constant is also the FALLBACK used by `translate()` when a key is
/// missing from the requested locale. Both apps currently have full ar/en
/// key parity, so the flip does not change any resolved string today; if
/// parity ever breaks, an untranslated key now falls back to Arabic rather
/// than surfacing English inside an otherwise-Arabic screen.
const AppLocale defaultLocale = AppLocale.ar;
const List<AppLocale> rtlLocales = [AppLocale.ar];

bool isRtl(AppLocale locale) => rtlLocales.contains(locale);

/// Stable, persistable code for an [AppLocale]. Deliberately the plain
/// ISO-639-1 code so what is written to storage matches what
/// `Locale.languageCode` and Android's `values-<code>` resource
/// qualifiers use — one vocabulary across the whole stack.
String appLocaleCode(AppLocale locale) => switch (locale) {
      AppLocale.en => 'en',
      AppLocale.ar => 'ar',
    };

/// Inverse of [appLocaleCode]. Returns `null` for anything unsupported so
/// callers can decide their own fallback, rather than silently pretending
/// an unknown language is the default.
AppLocale? appLocaleFromCode(String? code) => switch (code) {
      'en' => AppLocale.en,
      'ar' => AppLocale.ar,
      _ => null,
    };

String _resolvePluralKey(String key, int? count, Map<String, String> resources) {
  if (count == null) return key;
  final suffix = count == 1 ? '_one' : '_other';
  final pluralKey = '$key$suffix';
  return resources.containsKey(pluralKey) ? pluralKey : key;
}

String _interpolate(String template, Map<String, Object>? options) {
  if (options == null) return template;
  var result = template;
  for (final entry in options.entries) {
    result = result.replaceAll('{{${entry.key}}}', entry.value.toString());
  }
  return result;
}

/// Same fallback strategy as the Dashboard's `translate()`: requested
/// locale -> default locale -> the raw key itself (never blank).
String translate(AppLocale locale, String key, {int? count, Map<String, Object>? options}) {
  final resources = _resources[locale] ?? _resources[defaultLocale]!;
  final resolvedKey = _resolvePluralKey(key, count, resources);

  final template = resources[resolvedKey] ?? _resources[defaultLocale]![resolvedKey] ?? key;

  final interpolationOptions = <String, Object>{if (count != null) 'count': count, ...?options};
  return _interpolate(template, interpolationOptions);
}

/// Whether [key] resolves to a real resource, in [locale] or in the default
/// locale.
///
/// EXISTS FOR ONE SITUATION ONLY: a key built from a BACKEND value, such as
/// `t('category.${habit['category']}')`. `translate` answers a missing key
/// with the key itself, which on screen reads «category.WHATEVER» — a raw
/// backend value with a prefix glued on, i.e. exactly the thing that must
/// never reach a parent. A call site that interpolates a server value asks
/// this first and chooses its own fallback when the answer is no.
///
/// Do NOT use this for a literal key. A literal key that is missing is a bug
/// `verify_l10n_parity.py` already catches at commit time; guarding it here
/// would hide it instead.
bool hasTranslation(AppLocale locale, String key) {
  final resources = _resources[locale];
  if (resources != null && resources.containsKey(key)) return true;
  return _resources[defaultLocale]!.containsKey(key);
}
