/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * ============================================================================
 * GOLDEN E2E-07 — THE SUBSCRIPTION. PLAN -> TRIAL -> ACTIVE -> ENTITLEMENT ->
 * FEATURE ACCESS.
 * ============================================================================
 *
 * THE PRODUCT LOOP THIS PROTECTS. J13 of the fifteen journeys, and the only one
 * that moves money:
 *
 *   a parent sees the plans and the price for THEIR market, VAT broken out
 *     -> starts the trial, and the paid features open immediately;
 *     -> buys, through the App Store, and the SERVER — never the app — decides
 *        that the purchase is real: the token is verified with Apple, the
 *        household is resolved from Apple's own account reference rather than
 *        from the session, the product is mapped through OUR catalogue and the
 *        amount is compared against OUR price;
 *     -> an `Entitlement` row is written, and FEATURE ACCESS FOLLOWS THAT ROW.
 *        Not "which provider paid", not a client flag, not a cached receipt;
 *     -> the provider redelivers its webhook, as providers do, and NOTHING
 *        changes: not the transaction, not the entitlement, not the money;
 *     -> and a purchase whose amount does not match the catalogue is REJECTED,
 *        not clamped, not warned about, not accepted at the smaller figure.
 *
 * ============================ WHAT IS SUBSTITUTED ============================
 *
 * BLOCKED — no App Store Connect account exists in this environment: no Issuer
 * ID, no Key ID, no `.p8`, no bundle id, and none of them may be invented. So
 * REAL APPLE SANDBOX VERIFICATION IS NOT EXECUTED and this scenario does not
 * claim it. What is substituted is exactly two things, and no more:
 *
 *   APPLE'S HTTP RESPONSES  — `fetchImpl`, the provider's injected HTTP
 *                             boundary, returns App Store Server API shapes.
 *   APPLE'S SIGNING KEY     — a locally generated three-certificate ECDSA chain
 *                             from `test/billing/apple-chain.fixture.ts`, with
 *                             the verifier pinned to THAT root.
 *
 * WHAT IS NOT SUBSTITUTED: `AppleJwsVerifier` runs as written — the chain walk,
 * the ES256 check, the root pin, the bundle-id comparison; and every step that
 * matters commercially — `PaymentVerificationService`'s seven checks,
 * `PricingService.assertAmountMatches`, `EntitlementService.grantForPlan`,
 * `PaymentWebhookService`'s dedupe, and the HTTP layer including raw-body
 * signature handling — is the real thing against a real PostgreSQL.
 *
 * So this scenario proves THE LOGIC IS CORRECT. It does not prove
 * interoperability with Apple's real certificates, and the report says so in
 * those words.
 *
 * ON THE FIXTURES. Migration 0014 deliberately seeds NO prices and NO plan
 * definitions — pricing is a business decision the migration refuses to invent.
 * This scenario seeds the CONTEXT §6 proposed numbers for Egypt so that there is
 * something for the tamper check to compare against; the seeding is fixture
 * setup and is labelled as such.
 */
import {
  P,
  asParent,
  bootGoldenWorld,
  describeGolden,
  type GoldenHousehold,
  type GoldenWorld,
} from './golden-world';
import { AppleStoreKitProvider } from '../../src/modules/billing/infrastructure/adapters/apple-storekit.provider';
import type { FetchLike } from '../../src/modules/billing/infrastructure/apple/app-store-server-api.client';
import type {
  IAppleJwsRenewalInfoPayload,
  IAppleJwsTransactionPayload,
} from '../../src/modules/billing/infrastructure/apple/apple-storekit.types';
import { appleTestChain, signAppleJws } from '../billing/apple-chain.fixture';
import type { ConfigService } from '@nestjs/config';

import request = require('supertest');

const BUNDLE_ID = 'com.abny.app';
const STORE_PRODUCT_ID = 'com.abny.premium.monthly.eg';
/** CONTEXT §6: Premium in Egypt, 179 EGP/month, VAT 14% inclusive. */
const PREMIUM_EG_MINOR = 17_900;

const chain = appleTestChain();

/**
 * THIS SCENARIO RUNS ON THE REAL CLOCK, unlike the four reward scenarios, and
 * the reason is a property of what it verifies rather than a convenience.
 *
 * The reward loops own `Date` because quiet hours and the family business day
 * decide what they observe. Nothing here is time-of-day dependent — but the
 * test certificate chain is generated by `openssl` AT RUN TIME, so its
 * `notBefore` is the real present moment. A faked clock set one day earlier
 * would put every certificate outside its own validity window and
 * `AppleJwsVerifier` would reject it — correctly, for a reason that has nothing
 * to do with subscriptions.
 */
const NOW = new Date();
const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;

/**
 * A PER-RUN SUFFIX ON EVERY PROVIDER IDENTIFIER, and it is a property of the
 * product rather than of the harness: `payment_transactions
 * (provider, provider_transaction_id)` is UNIQUE ACROSS FAMILIES, because an
 * Apple transaction id is globally unique and two households claiming the same
 * one is precisely the cross-tenant purchase this table exists to refuse. A
 * scenario that reused a fixed id would collide with its own previous run and
 * report a 500 that looks like a payment defect and is not.
 */
const RUN = Math.random().toString(36).slice(2, 10);

/** APPLE'S KEY MATERIAL AND NOTHING ELSE. The verifier is pinned to the test
 * root, exactly as `apple-storekit.provider.spec.ts` does it. */
function appleConfig(): ConfigService {
  const values: Record<string, string | undefined> = {
    APPLE_ISSUER_ID: '57246542-96fe-1a63-e053-0824d011072a',
    APPLE_KEY_ID: '2X9R4HXF34',
    APPLE_PRIVATE_KEY: chain.leafPrivateKeyPem,
    APPLE_BUNDLE_ID: BUNDLE_ID,
    APPLE_ROOT_CA_G3_FINGERPRINT: chain.rootFingerprint,
  };
  return { get: (key: string) => values[key] } as unknown as ConfigService;
}

/** MOCKS APPLE'S HTTP RESPONSES. Nothing else. */
function fetchReturning(bodies: Record<string, unknown>): FetchLike {
  return async (url: string) => {
    const match = Object.keys(bodies).find((fragment) => url.includes(fragment));
    if (!match) return { ok: false, status: 404, text: async () => '{}' };
    return { ok: true, status: 200, text: async () => JSON.stringify(bodies[match]) };
  };
}

function transaction(overrides: Partial<IAppleJwsTransactionPayload> = {}): IAppleJwsTransactionPayload {
  return {
    transactionId: `20000007${RUN}01`,
    originalTransactionId: `20000007${RUN}00`,
    bundleId: BUNDLE_ID,
    productId: STORE_PRODUCT_ID,
    purchaseDate: NOW.getTime(),
    originalPurchaseDate: NOW.getTime(),
    expiresDate: NOW.getTime() + THIRTY_DAYS_MS,
    type: 'Auto-Renewable Subscription',
    inAppOwnershipType: 'PURCHASED',
    signedDate: NOW.getTime(),
    environment: 'Production',
    storefront: 'EGY',
    // MILLI-units: 179000 milli-EGP = 179.00 EGP = 17900 minor units.
    price: 179_000,
    currency: 'EGP',
    ...overrides,
  };
}

function renewalInfo(): IAppleJwsRenewalInfoPayload {
  return {
    originalTransactionId: `20000007${RUN}00`,
    productId: STORE_PRODUCT_ID,
    autoRenewStatus: 1,
    signedDate: NOW.getTime(),
    environment: 'Production',
  };
}

function statusResponse(txn: IAppleJwsTransactionPayload) {
  return {
    environment: 'Production',
    bundleId: BUNDLE_ID,
    data: [
      {
        subscriptionGroupIdentifier: 'group-1',
        lastTransactions: [
          {
            originalTransactionId: txn.originalTransactionId,
            status: 1,
            signedTransactionInfo: signAppleJws(txn),
            signedRenewalInfo: signAppleJws(renewalInfo()),
          },
        ],
      },
    ],
  };
}

/** An App Store Server Notification V2 body: `{"signedPayload": "<JWS>"}`. */
function notificationBody(notificationUUID: string, txn: IAppleJwsTransactionPayload): string {
  return JSON.stringify({
    signedPayload: signAppleJws({
      notificationType: 'DID_RENEW',
      notificationUUID,
      version: '2.0',
      signedDate: NOW.getTime(),
      data: {
        bundleId: BUNDLE_ID,
        environment: 'Production',
        signedTransactionInfo: signAppleJws(txn),
        signedRenewalInfo: signAppleJws(renewalInfo()),
        status: 1,
      },
    }),
  });
}

describeGolden('GOLDEN E2E-07 — a household subscribes, and access follows the entitlement row', () => {
  let world: GoldenWorld;
  let home: GoldenHousehold;

  beforeAll(async () => {
    world = await bootGoldenWorld('golden E2E-07 (subscription)', (builder) =>
      // THE ONE SUBSTITUTION IN THE ENTIRE GOLDEN SUITE, made here in the
      // scenario rather than in the shared harness so it is impossible to miss.
      builder
        .overrideProvider(AppleStoreKitProvider)
        .useValue(
          new AppleStoreKitProvider(
            appleConfig(),
            fetchReturning({ '/inApps/v1/subscriptions/': statusResponse(transaction()) }),
          ),
        ),
    );
    home = await world.register('e2e07');

    // ---- FIXTURES: the catalogue migration 0014 deliberately does not seed --
    await world.sys('seed the plan definitions', async () => {
      await world.prisma.planDefinition.deleteMany({ where: {} });
      await world.prisma.planDefinition.createMany({
        data: [
          { tier: 'FREE', name: 'Free', priceCents: 0, currency: 'EGP', features: [] },
          {
            tier: 'PREMIUM',
            name: 'Premium',
            priceCents: 17_900,
            currency: 'EGP',
            features: [
              'multiple_children',
              'family_insights',
              'ai_diagnostics',
              'priority_support',
              'unlimited_devices_per_child',
            ],
          },
        ],
      });
      await world.prisma.subscriptionPrice.deleteMany({ where: { storeProductId: STORE_PRODUCT_ID } });
      await world.prisma.subscriptionPrice.create({
        data: {
          planTier: 'PREMIUM',
          countryCode: 'EG',
          currencyCode: 'EGP',
          billingPeriod: 'MONTHLY',
          amountMinor: PREMIUM_EG_MINOR,
          vatMode: 'INCLUSIVE',
          storeProductId: STORE_PRODUCT_ID,
          isActive: true,
        },
      });
    });
  }, 180_000);

  /**
   * THE FIXTURES ARE REMOVED AGAIN, and this is not tidiness.
   *
   * `subscription_prices` and `plan_definitions` are PLATFORM reference tables,
   * not tenant data, so a row this scenario seeds is visible to every other
   * suite in the same `--runInBand` run. `payment-idempotency.integration.spec.ts`
   * asserts, deliberately, that migration 0014 seeds NO prices — «the commercial
   * decision has not been made» — and a golden scenario that left its own 179
   * EGP behind would make that assertion fail and look like a migration defect.
   *
   * Measured, not guessed: it DID fail exactly that way on the first full run.
   */
  afterAll(async () => {
    if (world) {
      await world.sys('remove the seeded catalogue', async () => {
        await world.prisma.subscriptionPrice.deleteMany({ where: { storeProductId: STORE_PRODUCT_ID } });
        await world.prisma.planDefinition.deleteMany({ where: { tier: { in: ['FREE', 'PREMIUM'] } } });
      });
      await world.close();
    }
  });

  const entitlementRows = (): Promise<any[]> =>
    world.sys('read the entitlements', () =>
      world.prisma.entitlement.findMany({ where: { familyId: home.familyId } }),
    );

  const transactionRows = (): Promise<any[]> =>
    world.sys('read the payment transactions', () =>
      world.prisma.paymentTransaction.findMany({ where: { familyId: home.familyId } }),
    );

  /** The product question, asked over HTTP: may this household add a second
   * child? `ChildrenService` gates it on the `multiple_children` feature. */
  async function addASecondChild(name: string): Promise<number> {
    const res = await request(world.http)
      .post(`${P}/children`)
      .set(asParent(home))
      .send({ firstName: name, dateOfBirth: '2016-05-05' });
    return res.status;
  }

  // =========================================================================
  // ACT I — THE PLAN, AND WHAT A FREE HOUSEHOLD CANNOT DO
  // =========================================================================

  it('ACT I — the parent sees the plans and the Egyptian price with VAT broken out', async () => {
    const plans = await request(world.http).get(`${P}/billing/plans`).set(asParent(home));
    expect(plans.status).toBe(200);
    expect(plans.body.map((p: any) => p.tier)).toEqual(expect.arrayContaining(['FREE', 'PREMIUM']));

    const catalogue = await request(world.http).get(`${P}/billing/catalogue/EG`).set(asParent(home));
    expect(catalogue.status).toBe(200);
    const premium = catalogue.body.find((entry: any) => entry.planTier === 'PREMIUM');
    expect(premium).toBeDefined();
    // The CURRENCY IS NOT A PARAMETER. It follows from the country, so a caller
    // cannot ask for Egyptian prices denominated in SAR — there is no way to
    // express it.
    expect(premium.currency).toBe('EGP');
    expect(premium.grossMinor).toBe(PREMIUM_EG_MINOR);
    expect(premium.vatBasisPoints).toBe(1_400);
    // Inclusive VAT: gross = net + vat, and the arithmetic is broken out rather
    // than left for a client to guess at.
    expect(premium.netMinor + premium.vatMinor).toBe(premium.grossMinor);
  });

  it('ACT I — a FREE household has no entitlements, and the paid feature is closed', async () => {
    const entitlements = await request(world.http).get(`${P}/billing/entitlements`).set(asParent(home));
    expect(entitlements.status).toBe(200);
    expect(entitlements.body.features).toEqual([]);
    expect(entitlements.body.planTier).toBeNull();

    // FEATURE ACCESS FOLLOWS ENTITLEMENT — measured on a real endpoint, not on
    // a service call. A second child is a paid capability.
    expect(await addASecondChild('طفل ثانٍ')).toBe(403);
  });

  // =========================================================================
  // ACT II — THE TRIAL
  // =========================================================================

  it('ACT II — starting the trial opens the paid feature immediately', async () => {
    const trial = await request(world.http).post(`${P}/billing/trial/start`).set(asParent(home)).send({});
    expect([200, 201]).toContain(trial.status);
    expect(trial.body.status).toBe('TRIALING');
    expect(trial.body.planTier).toBe('PREMIUM');

    const subscription = await request(world.http).get(`${P}/billing/subscription`).set(asParent(home));
    expect(subscription.body.isInTrial).toBe(true);
    expect(subscription.body.trialDaysRemaining).toBeGreaterThan(0);

    // The same request that was 403 one second ago.
    expect(await addASecondChild('طفل ثانٍ')).toBe(201);
  });

  it('ACT II — a family gets exactly one trial in its lifetime', async () => {
    const second = await request(world.http).post(`${P}/billing/trial/start`).set(asParent(home)).send({});
    expect(second.status).toBe(409);
  });

  // =========================================================================
  // ACT III — THE PURCHASE, VERIFIED WITH APPLE AND NOT WITH THE APP
  // =========================================================================

  it('ACT III — a verified App Store purchase grants an entitlement, and the response says what happened', async () => {
    const purchase = await request(world.http)
      .post(`${P}/billing/purchases/verify`)
      .set(asParent(home))
      .send({ provider: 'APPLE_IAP', providerToken: signAppleJws(transaction()) });

    expect(purchase.status).toBe(201);
    expect(purchase.body.verified).toBe(true);
    expect(purchase.body.wasDuplicate).toBe(false);
    expect(purchase.body.entitlementGranted).toBe(true);
    expect(purchase.body.status).toBe('ACTIVE');

    // THE MONEY IS A ROW, and it carries what OUR catalogue says it is worth,
    // split for VAT, not what the client claimed.
    const transactions = await transactionRows();
    expect(transactions).toHaveLength(1);
    expect(transactions[0].provider).toBe('APPLE_IAP');
    expect(transactions[0].grossAmountMinor).toBe(PREMIUM_EG_MINOR);
    expect(transactions[0].currency).toBe('EGP');
    expect(transactions[0].countryCode).toBe('EG');
    expect(transactions[0].planTier).toBe('PREMIUM');
    expect(transactions[0].status).toBe('SUCCEEDED');
  });

  it('ACT III — the entitlement is what feature access reads, and it names its source', async () => {
    const rows = await entitlementRows();
    expect(rows.length).toBe(5);
    expect(rows.map((r) => r.featureKey).sort()).toEqual(
      ['ai_diagnostics', 'family_insights', 'multiple_children', 'priority_support', 'unlimited_devices_per_child'].sort(),
    );
    for (const row of rows) {
      expect(row.status).toBe('ACTIVE');
      // `source` is recorded for accounting and the refund rule — «a Play
      // purchase is refunded only through Play» — and NO access decision reads
      // it. A Fawry kiosk payment and an App Store tap reach the same code.
      expect(row.source).toBe('APPLE_IAP');
      expect(row.validUntil).not.toBeNull();
    }

    const described = await request(world.http).get(`${P}/billing/entitlements`).set(asParent(home));
    expect(described.body.planTier).toBe('PREMIUM');
    expect(described.body.features).toEqual(expect.arrayContaining(['multiple_children']));
    expect(described.body.source).toBe('APPLE_IAP');
    expect(new Date(described.body.validUntil).getTime()).toBeGreaterThan(NOW.getTime());
  });

  // =========================================================================
  // ACT IV — THE PROVIDER REDELIVERS, AND NOTHING CHANGES
  // =========================================================================

  it('ACT IV — a duplicate provider webhook is acknowledged with 200 and changes NOTHING', async () => {
    const uuid = `golden-e2e07-notification-${RUN}`;
    const body = notificationBody(uuid, transaction());

    const before = {
      transactions: (await transactionRows()).length,
      entitlements: (await entitlementRows()).map((r) => `${r.featureKey}:${r.validUntil?.toISOString?.() ?? r.validUntil}`),
    };

    const first = await request(world.http)
      .post(`${P}/webhooks/payments/apple`)
      .set('content-type', 'application/json')
      .send(body);
    expect(first.status).toBe(200);
    expect(first.body.received).toBe(true);

    const second = await request(world.http)
      .post(`${P}/webhooks/payments/apple`)
      .set('content-type', 'application/json')
      .send(body);
    // 200 AND NOT REPROCESSED. Anything other than an immediate 200 makes the
    // provider retry a redelivery forever.
    expect(second.status).toBe(200);
    expect(second.body.outcome).toBe('DUPLICATE');

    const after = {
      transactions: (await transactionRows()).length,
      entitlements: (await entitlementRows()).map((r) => `${r.featureKey}:${r.validUntil?.toISOString?.() ?? r.validUntil}`),
    };
    expect(after.transactions).toBe(before.transactions);
    expect(after.entitlements.sort()).toEqual(before.entitlements.sort());

    // Exactly one dedupe row for Apple's own stable notification id.
    const events = await world.sys('read the webhook events', () =>
      world.prisma.paymentWebhookEvent.findMany({ where: { providerEventId: uuid } }),
    );
    expect(events).toHaveLength(1);
  });

  it('ACT IV — a webhook whose signature does not verify is a 400, and the response is not an oracle', async () => {
    const forged = JSON.stringify({ signedPayload: 'not.a.jws' });
    const res = await request(world.http)
      .post(`${P}/webhooks/payments/apple`)
      .set('content-type', 'application/json')
      .send(forged);

    expect(res.status).toBe(400);
    // Deliberately says nothing about WHY, so it cannot be used to construct a
    // valid signature one probe at a time.
    expect(JSON.stringify(res.body)).not.toContain('fingerprint');
    expect(JSON.stringify(res.body)).not.toContain('x5c');

    expect(await transactionRows()).toHaveLength(1);
  });

  // =========================================================================
  // ACT V — A TAMPERED AMOUNT IS REJECTED, NOT ACCEPTED AT THE SMALLER FIGURE
  // =========================================================================

  it('ACT V — a purchase reporting 1.00 EGP for a 179.00 EGP plan is REJECTED', async () => {
    const before = (await transactionRows()).length;

    const tampered = await request(world.http)
      .post(`${P}/billing/purchases/verify`)
      .set(asParent(home))
      .send({
        provider: 'APPLE_IAP',
        providerToken: signAppleJws(
          transaction({ transactionId: `20000007${RUN}02`, price: 1_000 }),
        ),
      });

    expect(tampered.status).toBe(400);
    expect(JSON.stringify(tampered.body)).toContain('Amount mismatch');

    // Not clamped, not warned about, not taken at the smaller figure: no row.
    expect(await transactionRows()).toHaveLength(before);
  });

  it('ACT V — a purchase reporting the right amount in the WRONG CURRENCY is a separate rejection', async () => {
    const before = (await transactionRows()).length;

    const tampered = await request(world.http)
      .post(`${P}/billing/purchases/verify`)
      .set(asParent(home))
      .send({
        provider: 'APPLE_IAP',
        providerToken: signAppleJws(
          transaction({ transactionId: `20000007${RUN}03`, currency: 'USD' }),
        ),
      });

    expect(tampered.status).toBe(400);
    expect(JSON.stringify(tampered.body)).toContain('Currency mismatch');
    expect(await transactionRows()).toHaveLength(before);
  });

  it('ACT V — a store product that is not in OUR catalogue grants nothing', async () => {
    const unknown = await request(world.http)
      .post(`${P}/billing/purchases/verify`)
      .set(asParent(home))
      .send({
        provider: 'APPLE_IAP',
        providerToken: signAppleJws(
          transaction({ transactionId: `20000007${RUN}04`, productId: 'com.abny.unmapped.monthly' }),
        ),
      });

    expect(unknown.status).toBe(400);
    // The entitlement follows OUR catalogue, never a string the store sent —
    // so a renamed product is a configuration error, not a free upgrade.
    expect(JSON.stringify(unknown.body)).toContain('not mapped');
  });

  it('ACT V — and after all of that, the household still holds exactly the entitlement it paid for', async () => {
    const described = await request(world.http).get(`${P}/billing/entitlements`).set(asParent(home));
    expect(described.body.planTier).toBe('PREMIUM');
    expect((await entitlementRows()).length).toBe(5);
    expect(await transactionRows()).toHaveLength(1);
  });
});
