import { AppleJwsVerifier, unsafeDecodeJwsPayload } from '../../src/modules/billing/infrastructure/apple/apple-jws.verifier';
import {
  appleTestChain,
  buildAlgNoneJws,
  buildForeignChainJws,
  signAppleJws,
  tamperPayload,
} from './apple-chain.fixture';

/**
 * PHASE D — THE VERIFICATION LOGIC ITSELF, UNDER TEST.
 *
 * Nothing here is mocked. `AppleJwsVerifier` is the production class, running
 * its production code path, against a real ECDSA certificate chain generated by
 * openssl (see `apple-chain.fixture.ts` for why a locally generated chain is
 * the honest substitute for Apple's key material, and for what that does and
 * does not prove).
 *
 * EVERY POSITIVE ASSERTION HERE HAS A NEGATIVE CONTROL. A suite that only signs
 * correctly and asserts success would pass unchanged against a verifier whose
 * body was `return {verified: true}` — which is precisely the failure mode this
 * whole module exists to prevent.
 */
describe('AppleJwsVerifier', () => {
  const chain = appleTestChain();
  const verifier = () => new AppleJwsVerifier({ rootFingerprintSha256: chain.rootFingerprint });

  const samplePayload = {
    transactionId: 'txn-1',
    originalTransactionId: 'orig-1',
    bundleId: 'com.abny.app',
    productId: 'com.abny.premium.monthly',
    price: 99_000,
    currency: 'EGP',
  };

  describe('the happy path', () => {
    it('verifies a genuine ES256 JWS whose chain terminates at the pinned root', () => {
      const result = verifier().verify<typeof samplePayload>(signAppleJws(samplePayload));
      expect(result.verified).toBe(true);
      expect(result.payload?.transactionId).toBe('txn-1');
      expect(result.reason).toBeNull();
    });

    it('returns a SHA-256 digest of the exact bytes verified, so a dispute can be re-checked', () => {
      const jws = signAppleJws(samplePayload);
      const first = verifier().verify(jws);
      const second = verifier().verify(jws);
      expect(first.digest).toMatch(/^[0-9a-f]{64}$/);
      expect(first.digest).toBe(second.digest);
      expect(verifier().verify(signAppleJws({ ...samplePayload, transactionId: 'txn-2' })).digest).not.toBe(
        first.digest,
      );
    });
  });

  describe('NEGATIVE CONTROLS — every one of these must be refused', () => {
    it('refuses a payload tampered with AFTER signing (the tampered-amount attack)', () => {
      const genuine = signAppleJws(samplePayload);
      const tampered = tamperPayload(genuine, (p) => {
        p.price = 1;
      });
      const result = verifier().verify(tampered);
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('signature does not verify');
    });

    it('refuses a valid, internally consistent chain that is not the pinned root — THE POINT OF THE PIN', () => {
      // This chain verifies perfectly: the leaf was issued by the intermediate,
      // the intermediate by the root, the root is self-signed, the intermediate
      // carries the WWDR OID, and the signature is genuine. It is simply not
      // Apple's. A verifier that walked the chain but skipped the fingerprint
      // comparison would accept this, and an attacker would need nothing more
      // than openssl to mint any receipt they liked.
      const result = verifier().verify(buildForeignChainJws(samplePayload));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('pinned Apple root');
    });

    it('refuses alg:"none"', () => {
      const result = verifier().verify(buildAlgNoneJws(samplePayload));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('Unsupported JWS alg');
    });

    it('refuses an HS256 algorithm-confusion downgrade', () => {
      const result = verifier().verify(buildAlgNoneJws(samplePayload, 'HS256'));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('Unsupported JWS alg');
    });

    it('refuses a JWS with no x5c chain at all', () => {
      const header = Buffer.from(JSON.stringify({ alg: 'ES256' })).toString('base64url');
      const result = verifier().verify(`${header}.e30.AAAA`);
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('x5c');
    });

    it('refuses a truncated chain (leaf + root, no intermediate)', () => {
      const shortChain = { x5c: [chain.x5c[0], chain.x5c[2]], leafPrivateKeyPem: chain.leafPrivateKeyPem };
      const result = verifier().verify(signAppleJws(samplePayload, shortChain));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('at least 3 certificates');
    });

    it('refuses a chain whose links do not actually sign each other', () => {
      // Leaf from the primary chain, intermediate and root from the foreign one.
      // Issuer/subject STRING comparison — which a surprising amount of
      // published sample code does — would not catch this, because an attacker
      // controls those strings. `cert.verify(issuerKey)` does.
      const spliced = {
        x5c: [chain.x5c[0], chain.foreign.x5c[1], chain.foreign.x5c[2]],
        leafPrivateKeyPem: chain.leafPrivateKeyPem,
      };
      const result = verifier().verify(signAppleJws(samplePayload, spliced));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('not issued by');
    });

    it('refuses everything when the root fingerprint is not configured — rather than skipping the check', () => {
      const unconfigured = new AppleJwsVerifier({ rootFingerprintSha256: null });
      expect(unconfigured.isConfigured()).toBe(false);
      const result = unconfigured.verify(signAppleJws(samplePayload));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('APPLE_ROOT_CA_G3_FINGERPRINT is not configured');
    });

    it('refuses a certificate outside its validity window', () => {
      // The fixture chain is valid for ten years, so the clock is moved rather
      // than the certificate. Twenty years on, every certificate has expired.
      const future = new AppleJwsVerifier({
        rootFingerprintSha256: chain.rootFingerprint,
        now: () => new Date(Date.now() + 20 * 365 * 86_400_000),
      });
      const result = future.verify(signAppleJws(samplePayload));
      expect(result.verified).toBe(false);
      expect(result.reason).toContain('validity window');
    });

    it('refuses a malformed JWS', () => {
      expect(verifier().verify('not-a-jws').verified).toBe(false);
      expect(verifier().verify('a.b').verified).toBe(false);
    });
  });

  describe('fingerprint normalisation', () => {
    it('accepts the openssl colon-separated form and a bare hex string alike', () => {
      const bare = chain.rootFingerprint.replace(/:/g, '');
      const lower = chain.rootFingerprint.toLowerCase();
      for (const form of [chain.rootFingerprint, bare, lower]) {
        expect(new AppleJwsVerifier({ rootFingerprintSha256: form }).verify(signAppleJws(samplePayload)).verified).toBe(
          true,
        );
      }
    });
  });

  describe('unsafeDecodeJwsPayload', () => {
    it('reads a payload without verifying — which is why it is named that way', () => {
      // Its ONE legitimate use is reading `notificationUUID` so the dedupe row
      // can be written before verification runs. It returns a payload for a
      // FORGED token too, which is exactly why nothing may derive an
      // entitlement from its output.
      const forged = buildForeignChainJws({ notificationUUID: 'uuid-1' });
      expect(unsafeDecodeJwsPayload<{ notificationUUID: string }>(forged)?.notificationUUID).toBe('uuid-1');
      expect(verifier().verify(forged).verified).toBe(false);
    });

    it('returns null for junk rather than throwing', () => {
      expect(unsafeDecodeJwsPayload('nonsense')).toBeNull();
    });
  });
});
